<a href="https://colab.research.google.com/github/amzad-786githumb/AIR_LLM_Research/blob/main/00_Project_Configuration.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# ============================================================
# CELL 00.1 — AIR-LLM PROJECT CONFIGURATION
# ============================================================

PROJECT_NAME = "AIR-LLM Research Project"
PROJECT_CODE = "AIR-LLM"
PROJECT_VERSION = "1.0"
EXPERIMENT_VERSION = "AIR-LLM-v1"

print("=" * 100)
print("AIR-LLM — PROJECT CONFIGURATION")
print("=" * 100)
print(f"Project          : {PROJECT_NAME}")
print(f"Project Code     : {PROJECT_CODE}")
print(f"Project Version  : {PROJECT_VERSION}")
print(f"Experiment       : {EXPERIMENT_VERSION}")
print("=" * 100)

====================================================================================================
AIR-LLM — PROJECT CONFIGURATION
====================================================================================================
Project          : AIR-LLM Research Project
Project Code     : AIR-LLM
Project Version  : 1.0
Experiment       : AIR-LLM-v1
====================================================================================================

In [2]:
# ============================================================
# CELL 00.1.1 — ENVIRONMENT SETUP
# ============================================================

import os
import sys
import json
import random
import platform
import warnings
import subprocess
from pathlib import Path
from datetime import datetime, timezone

warnings.filterwarnings("ignore")

print("=" * 100)
print("AIR-LLM RESEARCH PROJECT")
print("00 — PROJECT CONFIGURATION")
print("=" * 100)

print(f"Python      : {sys.version.split()[0]}")
print(f"Platform    : {platform.platform()}")
print(f"Execution   : {datetime.now(timezone.utc).isoformat()}")
print("=" * 100)

====================================================================================================
AIR-LLM RESEARCH PROJECT
00 — PROJECT CONFIGURATION
====================================================================================================
Python      : 3.12.13
Platform    : Linux-6.6.122+-x86_64-with-glibc2.35
Execution   : 2026-08-18T13:35:49.553705+00:00
====================================================================================================

In [3]:
# ============================================================
# CELL 00.1.3 — CORE LIBRARY IMPORTS
# ============================================================

import numpy as np
import pandas as pd
import scipy
import sklearn
import yaml

from sklearn import __version__ as SKLEARN_VERSION

print("Core libraries imported successfully.")

Core libraries imported successfully.

In [4]:
# ============================================================
# CELL 00.1.4 — PYTORCH ENVIRONMENT
# ============================================================

try:
    import torch

    TORCH_AVAILABLE = True
    TORCH_VERSION = torch.__version__

except ImportError:

    torch = None
    TORCH_AVAILABLE = False
    TORCH_VERSION = None

print(f"PyTorch available : {TORCH_AVAILABLE}")
print(f"PyTorch version   : {TORCH_VERSION}")

PyTorch available : True
PyTorch version   : 2.11.0+cpu

In [5]:
# ============================================================
# CELL 00.2.1 — PACKAGE VERSION REGISTRY
# ============================================================

PACKAGE_VERSIONS = {

    "python": platform.python_version(),

    "numpy": np.__version__,

    "pandas": pd.__version__,

    "scipy": scipy.__version__,

    "scikit_learn": SKLEARN_VERSION,

    "pyyaml": yaml.__version__,

    "torch": TORCH_VERSION
}

PACKAGE_VERSION_DF = pd.DataFrame(
    [
        {
            "package": package,
            "version": version
        }
        for package, version
        in PACKAGE_VERSIONS.items()
    ]
)

display(PACKAGE_VERSION_DF)

print("Package versions captured successfully.")

        package     version
0        python     3.12.13
1         numpy       2.0.2
2        pandas       2.2.2
3         scipy      1.16.3
4  scikit_learn       1.6.1
5        pyyaml       6.0.3
6         torch  2.11.0+cpu

Package versions captured successfully.

In [6]:
# ============================================================
# CELL 00.2.2 — HARDWARE / RUNTIME INFORMATION
# ============================================================

if TORCH_AVAILABLE:

    DEVICE = (
        "cuda"
        if torch.cuda.is_available()
        else "cpu"
    )

    if torch.cuda.is_available():

        GPU_NAME = torch.cuda.get_device_name(0)
        GPU_COUNT = torch.cuda.device_count()
        CUDA_VERSION = torch.version.cuda

    else:

        GPU_NAME = "CPU"
        GPU_COUNT = 0
        CUDA_VERSION = None

else:

    DEVICE = "cpu"
    GPU_NAME = "CPU"
    GPU_COUNT = 0
    CUDA_VERSION = None


RUNTIME_INFO = {

    "python_version":
        PACKAGE_VERSIONS["python"],

    "platform":
        platform.platform(),

    "processor":
        platform.processor(),

    "device":
        DEVICE,

    "gpu_name":
        GPU_NAME,

    "gpu_count":
        GPU_COUNT,

    "cuda_version":
        CUDA_VERSION
}

print("=" * 100)
print("RUNTIME INFORMATION")
print("=" * 100)

for key, value in RUNTIME_INFO.items():
    print(f"{key:20s}: {value}")

====================================================================================================
RUNTIME INFORMATION
====================================================================================================
python_version      : 3.12.13
platform            : Linux-6.6.122+-x86_64-with-glibc2.35
processor           : x86_64
device              : cpu
gpu_name            : CPU
gpu_count           : 0
cuda_version        : None

In [7]:
# ============================================================
# CELL 00.3.1 — GLOBAL RANDOM SEED
# ============================================================

SEED = 42

os.environ["PYTHONHASHSEED"] = str(SEED)

random.seed(SEED)
np.random.seed(SEED)

if TORCH_AVAILABLE:
    torch.manual_seed(SEED)

    if torch.cuda.is_available():
        torch.cuda.manual_seed(SEED)
        torch.cuda.manual_seed_all(SEED)

print(f"Global random seed: {SEED}")

Global random seed: 42

In [8]:
# ============================================================
# CELL 00.3.2 — PYTORCH REPRODUCIBILITY
# ============================================================

PYTORCH_REPRODUCIBILITY = {
    "seed": SEED,
    "deterministic": True,
    "benchmark": False
}

if TORCH_AVAILABLE:

    torch.use_deterministic_algorithms(True, warn_only=True)

    if torch.cuda.is_available():
        torch.backends.cudnn.deterministic = True
        torch.backends.cudnn.benchmark = False

print("PyTorch reproducibility configuration applied.")

PyTorch reproducibility configuration applied.

In [9]:
# ============================================================
# CELL 00.4.1 — GOOGLE DRIVE
# ============================================================

from google.colab import drive

DRIVE_ROOT = Path("/content/drive")
MYDRIVE_ROOT = DRIVE_ROOT / "MyDrive"

drive.mount(
    str(DRIVE_ROOT),
    force_remount=False
)

if not MYDRIVE_ROOT.exists():
    raise RuntimeError(
        f"Google Drive mounted, but MyDrive was not found: {MYDRIVE_ROOT}"
    )

print("=" * 100)
print("GOOGLE DRIVE STATUS")
print("=" * 100)
print(f"Drive root : {DRIVE_ROOT}")
print(f"MyDrive    : {MYDRIVE_ROOT}")
print(f"Mounted    : {DRIVE_ROOT.exists()}")
print(f"Writable   : {os.access(MYDRIVE_ROOT, os.W_OK)}")

if not os.access(MYDRIVE_ROOT, os.W_OK):
    raise PermissionError(
        f"MyDrive is not writable: {MYDRIVE_ROOT}"
    )

print("Google Drive mounted and writable.")

Mounted at /content/drive
====================================================================================================
GOOGLE DRIVE STATUS
====================================================================================================
Drive root : /content/drive
MyDrive    : /content/drive/MyDrive
Mounted    : True
Writable   : True
Google Drive mounted and writable.

In [10]:
# ============================================================
# CELL 00.4.2 — PROJECT ROOT
# ============================================================

PROJECT_ROOT = MYDRIVE_ROOT / "AIR_LLM_Research"

PROJECT_ROOT.mkdir(
    parents=True,
    exist_ok=True
)

if not PROJECT_ROOT.exists() or not PROJECT_ROOT.is_dir():
    raise RuntimeError(
        f"Project root could not be created or accessed: {PROJECT_ROOT}"
    )

if not os.access(PROJECT_ROOT, os.W_OK):
    raise PermissionError(
        f"Project root is not writable: {PROJECT_ROOT}"
    )

print("=" * 100)
print("PROJECT ROOT")
print("=" * 100)
print(f"Project Root : {PROJECT_ROOT}")
print(f"Exists       : {PROJECT_ROOT.exists()}")
print(f"Directory    : {PROJECT_ROOT.is_dir()}")
print(f"Writable     : {os.access(PROJECT_ROOT, os.W_OK)}")

====================================================================================================
PROJECT ROOT
====================================================================================================
Project Root : /content/drive/MyDrive/AIR_LLM_Research
Exists       : True
Directory    : True
Writable     : True

In [11]:
# ============================================================
# CELL 00.4.3 — PROJECT IDENTITY
# ============================================================

PROJECT_NAME = "AIR-LLM Research Project"

PROJECT_CODE = "AIR-LLM"

PROJECT_VERSION = "1.0"

EXPERIMENT_VERSION = "AIR-LLM-v1"

CONFIGURATION_VERSION = "CONFIG-v1"

print("=" * 100)
print("PROJECT IDENTITY")
print("=" * 100)

print(f"Project              : {PROJECT_NAME}")
print(f"Project Code         : {PROJECT_CODE}")
print(f"Project Version      : {PROJECT_VERSION}")
print(f"Experiment Version   : {EXPERIMENT_VERSION}")
print(f"Configuration        : {CONFIGURATION_VERSION}")
print(f"Project Root         : {PROJECT_ROOT}")

====================================================================================================
PROJECT IDENTITY
====================================================================================================
Project              : AIR-LLM Research Project
Project Code         : AIR-LLM
Project Version      : 1.0
Experiment Version   : AIR-LLM-v1
Configuration        : CONFIG-v1
Project Root         : /content/drive/MyDrive/AIR_LLM_Research

In [12]:
# ============================================================
# CELL 00.5.1 — DATASET REGISTRY
# ============================================================

DATASET_REGISTRY = {

    "adult_income": {
        "dataset_name": "Adult Income",
        "raw_file": "adult_income.csv",
        "processed_file": "adult_income_processed.csv",
        "target": "income",
        "task": "classification",
        "domain": "socioeconomic",
        "expected_mixed_type": True
    },

    "bank_marketing": {
        "dataset_name": "Bank Marketing",
        "raw_file": "bank_marketing.csv",
        "processed_file": "bank_marketing_processed.csv",
        "target": "y",
        "task": "classification",
        "domain": "financial_marketing",
        "expected_mixed_type": True
    },

    "diabetes_130us": {
        "dataset_name": "Diabetes 130-US Hospitals",
        "raw_file": "diabetes_130us.csv",
        "processed_file": "diabetes_130us_processed.csv",
        "target": "readmitted",
        "task": "classification",
        "domain": "healthcare",
        "expected_mixed_type": True
    }
}

DATASETS = list(DATASET_REGISTRY.keys())

# ------------------------------------------------------------
# Canonical persistent dataset directories
# ------------------------------------------------------------

RAW_DATA_DIR = PROJECT_ROOT / "01_Raw_Data"
PROCESSED_DATA_DIR = PROJECT_ROOT / "02_Preprocessed_Data"

RAW_DATA_DIR.mkdir(parents=True, exist_ok=True)
PROCESSED_DATA_DIR.mkdir(parents=True, exist_ok=True)

# ------------------------------------------------------------
# Add canonical paths to the registry
# ------------------------------------------------------------

for dataset_id, metadata in DATASET_REGISTRY.items():

    metadata["raw_path"] = (
        RAW_DATA_DIR / metadata["raw_file"]
    )

    metadata["processed_path"] = (
        PROCESSED_DATA_DIR / metadata["processed_file"]
    )

# ------------------------------------------------------------
# Display registry
# ------------------------------------------------------------

print("=" * 100)
print("DATASET REGISTRY")
print("=" * 100)

for dataset_id, metadata in DATASET_REGISTRY.items():

    print(f"\nDataset ID       : {dataset_id}")
    print(f"Dataset Name     : {metadata['dataset_name']}")
    print(f"Target           : {metadata['target']}")
    print(f"Raw Path         : {metadata['raw_path']}")
    print(f"Processed Path   : {metadata['processed_path']}")

====================================================================================================
DATASET REGISTRY
====================================================================================================

Dataset ID       : adult_income
Dataset Name     : Adult Income
Target           : income
Raw Path         : /content/drive/MyDrive/AIR_LLM_Research/01_Raw_Data/adult_income.csv
Processed Path   : /content/drive/MyDrive/AIR_LLM_Research/02_Preprocessed_Data/adult_income_processed.csv

Dataset ID       : bank_marketing
Dataset Name     : Bank Marketing
Target           : y
Raw Path         : /content/drive/MyDrive/AIR_LLM_Research/01_Raw_Data/bank_marketing.csv
Processed Path   : /content/drive/MyDrive/AIR_LLM_Research/02_Preprocessed_Data/bank_marketing_processed.csv

Dataset ID       : diabetes_130us
Dataset Name     : Diabetes 130-US Hospitals
Target           : readmitted
Raw Path         : /content/drive/MyDrive/AIR_LLM_Research/01_Raw_Data/diabetes_130us.csv
Processed Path   : /content/drive/MyDrive/AIR_LLM_Research/02_Preprocessed_Data/diabetes_130us_processed.csv

In [13]:
# ============================================================
# CELL 00.5.2 — DATASET PATH REGISTRY
# ============================================================

DATASET_PATHS = {}

for dataset_id, metadata in DATASET_REGISTRY.items():

    DATASET_PATHS[dataset_id] = {
        "raw": metadata["raw_path"],
        "processed": metadata["processed_path"]
    }

print("=" * 100)
print("DATASET PATH REGISTRY")
print("=" * 100)

for dataset_id, paths in DATASET_PATHS.items():

    print(f"\n{dataset_id}")
    print(f"  Raw       : {paths['raw']}")
    print(f"  Processed : {paths['processed']}")

====================================================================================================
DATASET PATH REGISTRY
====================================================================================================

adult_income
  Raw       : /content/drive/MyDrive/AIR_LLM_Research/01_Raw_Data/adult_income.csv
  Processed : /content/drive/MyDrive/AIR_LLM_Research/02_Preprocessed_Data/adult_income_processed.csv

bank_marketing
  Raw       : /content/drive/MyDrive/AIR_LLM_Research/01_Raw_Data/bank_marketing.csv
  Processed : /content/drive/MyDrive/AIR_LLM_Research/02_Preprocessed_Data/bank_marketing_processed.csv

diabetes_130us
  Raw       : /content/drive/MyDrive/AIR_LLM_Research/01_Raw_Data/diabetes_130us.csv
  Processed : /content/drive/MyDrive/AIR_LLM_Research/02_Preprocessed_Data/diabetes_130us_processed.csv

In [14]:
# ============================================================
# CELL 00.5.3 — DATASET REGISTRY VALIDATION
# ============================================================

REQUIRED_DATASET_FIELDS = [
    "dataset_name",
    "raw_file",
    "processed_file",
    "target",
    "task",
    "domain",
    "expected_mixed_type",
    "raw_path",
    "processed_path"
]

EXPECTED_DATASETS = {
    "adult_income",
    "bank_marketing",
    "diabetes_130us"
}

for dataset_id, metadata in DATASET_REGISTRY.items():

    for field in REQUIRED_DATASET_FIELDS:

        assert field in metadata, (
            f"{dataset_id}: missing field '{field}'"
        )

    assert metadata["task"] == "classification"

    assert metadata["raw_path"] == (
        RAW_DATA_DIR / metadata["raw_file"]
    )

    assert metadata["processed_path"] == (
        PROCESSED_DATA_DIR / metadata["processed_file"]
    )

assert set(DATASETS) == EXPECTED_DATASETS

assert set(DATASET_PATHS.keys()) == EXPECTED_DATASETS

for dataset_id in EXPECTED_DATASETS:

    assert DATASET_PATHS[dataset_id]["raw"] == (
        DATASET_REGISTRY[dataset_id]["raw_path"]
    )

    assert DATASET_PATHS[dataset_id]["processed"] == (
        DATASET_REGISTRY[dataset_id]["processed_path"]
    )

print("=" * 100)
print("DATASET REGISTRY VALIDATION")
print("=" * 100)
print("Dataset registry validation: PASSED")
print(f"Datasets validated   : {len(DATASET_REGISTRY)}")
print(f"Expected datasets    : {len(EXPECTED_DATASETS)}")
print("Path consistency     : PASSED")

====================================================================================================
DATASET REGISTRY VALIDATION
====================================================================================================
Dataset registry validation: PASSED
Datasets validated   : 3
Expected datasets    : 3
Path consistency     : PASSED

In [15]:
# ============================================================
# CELL 00.6.1 — FEATURE / TARGET CONFIGURATION
# ============================================================

FEATURE_TARGET_REGISTRY = {

    "adult_income": {

        "target": "income",

        "numeric_features": None,

        "categorical_features": None,

        "excluded_features": [],

        "feature_detection": "automatic",

        "target_excluded_from_imputation": True
    },

    "bank_marketing": {

        "target": "y",

        "numeric_features": None,

        "categorical_features": None,

        "excluded_features": [],

        "feature_detection": "automatic",

        "target_excluded_from_imputation": True
    },

    "diabetes_130us": {

        "target": "readmitted",

        "numeric_features": None,

        "categorical_features": None,

        "excluded_features": [],

        "feature_detection": "automatic",

        "target_excluded_from_imputation": True
    }
}

for dataset_id, config in FEATURE_TARGET_REGISTRY.items():

    assert dataset_id in DATASET_REGISTRY

    assert (
        config["target"]
        == DATASET_REGISTRY[dataset_id]["target"]
    )

print("=" * 100)
print("FEATURE / TARGET CONFIGURATION")
print("=" * 100)

for dataset_id, config in FEATURE_TARGET_REGISTRY.items():

    print(
        f"{dataset_id:20s} | "
        f"Target: {config['target']:15s} | "
        f"Automatic feature detection: "
        f"{config['feature_detection']}"
    )

====================================================================================================
FEATURE / TARGET CONFIGURATION
====================================================================================================
adult_income         | Target: income          | Automatic feature detection: automatic
bank_marketing       | Target: y               | Automatic feature detection: automatic
diabetes_130us       | Target: readmitted      | Automatic feature detection: automatic

In [16]:
# ============================================================
# CELL 00.6.2 — FEATURE TYPE DETECTION POLICY
# ============================================================

FEATURE_TYPE_POLICY = {

    "numeric_detection": {

        "method": "pandas_numeric_dtype"
    },

    "categorical_detection": {

        "method":
            "object_category_bool_string_dtype"
    },

    "target_handling": {

        "exclude_from_imputation": True
    },

    "identifier_handling": {

        "detect_and_flag": True,

        "automatic_imputation": False
    },

    "constant_features": {

        "detect": True,

        "flag": True
    }
}

print(
    json.dumps(
        FEATURE_TYPE_POLICY,
        indent=4
    )
)

{
    "numeric_detection": {
        "method": "pandas_numeric_dtype"
    },
    "categorical_detection": {
        "method": "object_category_bool_string_dtype"
    },
    "target_handling": {
        "exclude_from_imputation": true
    },
    "identifier_handling": {
        "detect_and_flag": true,
        "automatic_imputation": false
    },
    "constant_features": {
        "detect": true,
        "flag": true
    }
}

In [17]:
# ============================================================
# CELL 00.7.1 — MISSINGNESS CONFIGURATION
# ============================================================

MISSINGNESS_CONFIG = {

    "mechanisms": [
        "MCAR",
        "MAR",
        "MNAR"
    ],

    "rates": [
        0.10,
        0.20,
        0.30,
        0.40,
        0.50
    ],

    "repetitions": 5,

    "random_seed": SEED,

    "target_excluded": True,

    "preserve_original_data": True,

    "feature_level_generation": True,

    "same_scenario_across_methods": True,

    "same_scenario_across_datasets": False,

    "missingness_indicator_saved": True
}

print("=" * 100)
print("MISSINGNESS CONFIGURATION")
print("=" * 100)

for key, value in MISSINGNESS_CONFIG.items():
    print(f"{key:35s}: {value}")

====================================================================================================
MISSINGNESS CONFIGURATION
====================================================================================================
mechanisms                         : ['MCAR', 'MAR', 'MNAR']
rates                              : [0.1, 0.2, 0.3, 0.4, 0.5]
repetitions                        : 5
random_seed                        : 42
target_excluded                    : True
preserve_original_data             : True
feature_level_generation           : True
same_scenario_across_methods       : True
same_scenario_across_datasets      : False
missingness_indicator_saved        : True

In [18]:
# ============================================================
# CELL 00.7.2 — DATA SPLIT CONFIGURATION
# ============================================================

SPLIT_CONFIG = {

    "train_size": 0.70,

    "validation_size": 0.15,

    "test_size": 0.15,

    "random_state": SEED,

    "stratify_target": True,

    "preserve_test_ground_truth": True
}

assert np.isclose(
    SPLIT_CONFIG["train_size"]
    + SPLIT_CONFIG["validation_size"]
    + SPLIT_CONFIG["test_size"],
    1.0
)

print("Train      :", SPLIT_CONFIG["train_size"])
print("Validation :", SPLIT_CONFIG["validation_size"])
print("Test       :", SPLIT_CONFIG["test_size"])

Train      : 0.7
Validation : 0.15
Test       : 0.15

In [19]:
# ============================================================
# CELL 00.7.3 — MISSINGNESS VALIDATION
# ============================================================

VALID_MISSINGNESS_MECHANISMS = {
    "MCAR",
    "MAR",
    "MNAR"
}

assert set(
    MISSINGNESS_CONFIG["mechanisms"]
).issubset(
    VALID_MISSINGNESS_MECHANISMS
), (
    "Invalid missingness mechanism detected."
)

assert len(
    MISSINGNESS_CONFIG["mechanisms"]
) == len(
    set(MISSINGNESS_CONFIG["mechanisms"])
), (
    "Duplicate missingness mechanisms detected."
)

assert all(
    0 < rate < 1
    for rate in MISSINGNESS_CONFIG["rates"]
), (
    "Missingness rates must be strictly between 0 and 1."
)

assert len(
    MISSINGNESS_CONFIG["rates"]
) == len(
    set(MISSINGNESS_CONFIG["rates"])
), (
    "Duplicate missingness rates detected."
)

assert (
    MISSINGNESS_CONFIG["rates"]
    == sorted(MISSINGNESS_CONFIG["rates"])
), (
    "Missingness rates must be in ascending order."
)

assert (
    MISSINGNESS_CONFIG["repetitions"] >= 1
), (
    "Repetitions must be at least 1."
)

assert (
    MISSINGNESS_CONFIG["target_excluded"] is True
), (
    "Target must be excluded from missingness generation."
)

assert (
    MISSINGNESS_CONFIG["preserve_original_data"] is True
), (
    "Original complete data must be preserved."
)

assert (
    MISSINGNESS_CONFIG["same_scenario_across_methods"] is True
), (
    "The same missingness scenario must be used across methods."
)

assert (
    MISSINGNESS_CONFIG["same_scenario_across_datasets"] is False
), (
    "Missingness scenarios must be generated independently per dataset."
)

assert (
    MISSINGNESS_CONFIG["missingness_indicator_saved"] is True
), (
    "Missingness indicators must be persisted."
)

print("Missingness configuration validation: PASSED")
print(
    "Mechanisms:",
    ", ".join(MISSINGNESS_CONFIG["mechanisms"])
)
print(
    "Rates:",
    MISSINGNESS_CONFIG["rates"]
)
print(
    "Repetitions:",
    MISSINGNESS_CONFIG["repetitions"]
)

Missingness configuration validation: PASSED
Mechanisms: MCAR, MAR, MNAR
Rates: [0.1, 0.2, 0.3, 0.4, 0.5]
Repetitions: 5

In [20]:
# ============================================================
# CELL 00.8.1 — CANDIDATE STRATEGY REGISTRY
# ============================================================

CANDIDATE_STRATEGY_REGISTRY = {

    "Mean": {
        "family": "statistical",
        "supported_types": ["numerical"],
        "multivariate": False,
        "nonlinear": False,
        "requires_training": False
    },

    "Median": {
        "family": "statistical",
        "supported_types": ["numerical"],
        "multivariate": False,
        "nonlinear": False,
        "requires_training": False
    },

    "Mode": {
        "family": "statistical",
        "supported_types": ["categorical"],
        "multivariate": False,
        "nonlinear": False,
        "requires_training": False
    },

    "KNN": {
        "family": "machine_learning",
        "supported_types": ["numerical", "categorical"],
        "multivariate": True,
        "nonlinear": False,
        "nonparametric": True,
        "requires_training": False
    },

    "IterativeImputer": {
        "family": "machine_learning",
        "supported_types": ["numerical"],
        "multivariate": True,
        "nonlinear": False,
        "nonparametric": False,
        "requires_training": True
    },

    "RandomForest": {
        "family": "machine_learning",
        "supported_types": ["numerical", "categorical"],
        "multivariate": True,
        "nonlinear": True,
        "nonparametric": False,
        "requires_training": True
    },

    "MissForest": {
        "family": "machine_learning",
        "supported_types": ["numerical", "categorical"],
        "multivariate": True,
        "nonlinear": True,
        "nonparametric": False,
        "requires_training": True
    }
}

CANDIDATE_STRATEGIES = list(
    CANDIDATE_STRATEGY_REGISTRY.keys()
)

print("=" * 100)
print("CANDIDATE STRATEGY REGISTRY")
print("=" * 100)

for method, properties in CANDIDATE_STRATEGY_REGISTRY.items():

    print(
        f"{method:22s} | "
        f"{properties['family']:18s} | "
        f"Types: {properties['supported_types']} | "
        f"Multivariate: {properties['multivariate']} | "
        f"Nonlinear: {properties['nonlinear']}"
    )

====================================================================================================
CANDIDATE STRATEGY REGISTRY
====================================================================================================
Mean                   | statistical        | Types: ['numerical'] | Multivariate: False | Nonlinear: False
Median                 | statistical        | Types: ['numerical'] | Multivariate: False | Nonlinear: False
Mode                   | statistical        | Types: ['categorical'] | Multivariate: False | Nonlinear: False
KNN                    | machine_learning   | Types: ['numerical', 'categorical'] | Multivariate: True | Nonlinear: False
IterativeImputer       | machine_learning   | Types: ['numerical'] | Multivariate: True | Nonlinear: False
RandomForest           | machine_learning   | Types: ['numerical', 'categorical'] | Multivariate: True | Nonlinear: True
MissForest             | machine_learning   | Types: ['numerical', 'categorical'] | Multivariate: True | Nonlinear: True

In [21]:
# ============================================================
# CELL 00.8.2 — STRATEGY SELECTION POLICY
# ============================================================

STRATEGY_SELECTION_POLICY = {

    "selection_granularity":
        "feature_level",

    "candidate_pool":
        "all_compatible_methods",

    "llm_role":
        "recommendation_and_reasoning",

    "empirical_validation":
        True,

    "final_selection":
        "best_supported_strategy",

    "fallback_strategy":
        "best_empirical_candidate",

    "target_imputation":
        False,

    "selection_explanation":
        True
}

print(
    json.dumps(
        STRATEGY_SELECTION_POLICY,
        indent=4
    )
)

{
    "selection_granularity": "feature_level",
    "candidate_pool": "all_compatible_methods",
    "llm_role": "recommendation_and_reasoning",
    "empirical_validation": true,
    "final_selection": "best_supported_strategy",
    "fallback_strategy": "best_empirical_candidate",
    "target_imputation": false,
    "selection_explanation": true
}

In [22]:
# ============================================================
# CELL 00.9.1 — LLM CONFIGURATION
# ============================================================

LLM_CONFIG = {

    "enabled": True,

    "temperature": 0.0,

    "deterministic": True,

    "feature_level_reasoning": True,

    "data_evidence_required": True,

    "missingness_mechanism_required": True,

    "feature_type_required": True,

    "missingness_rate_required": True,

    "candidate_capability_matching": True,

    "strategy_justification_required": True,

    "confidence_required": True,

    "explanation_required": True,

    "structured_output": True,

    "single_final_recommendation": True,

    "fallback_to_empirical_evidence": True,

    "max_recommendations": 1,

    "api_key_storage":
        "environment_variable_only",

    "api_key_persistence":
        False
}

print("=" * 100)
print("LLM CONFIGURATION")
print("=" * 100)

for key, value in LLM_CONFIG.items():

    print(f"{key:40s}: {value}")

====================================================================================================
LLM CONFIGURATION
====================================================================================================
enabled                                 : True
temperature                             : 0.0
deterministic                           : True
feature_level_reasoning                 : True
data_evidence_required                  : True
missingness_mechanism_required          : True
feature_type_required                   : True
missingness_rate_required               : True
candidate_capability_matching           : True
strategy_justification_required         : True
confidence_required                     : True
explanation_required                    : True
structured_output                       : True
single_final_recommendation             : True
fallback_to_empirical_evidence          : True
max_recommendations                     : 1
api_key_storage                         : environment_variable_only
api_key_persistence                     : False

In [23]:
# ============================================================
# CELL 00.9.2 — LLM DECISION OUTPUT SCHEMA
# ============================================================

LLM_OUTPUT_SCHEMA = {

    "dataset_id": "string",

    "feature": "string",

    "feature_type": "numerical|categorical",

    "missingness_mechanism": "MCAR|MAR|MNAR",

    "missingness_rate": "float",

    "data_evidence": "string",

    "candidate_strategies": "list[string]",

    "recommended_strategy": "string",

    "reasoning": "string",

    "confidence": "float",

    "alternative_strategy": "string|null",

    "final_decision": "string",

    "fallback_used": "boolean"
}

print("=" * 100)
print("LLM DECISION OUTPUT SCHEMA")
print("=" * 100)

print(
    json.dumps(
        LLM_OUTPUT_SCHEMA,
        indent=4
    )
)

====================================================================================================
LLM DECISION OUTPUT SCHEMA
====================================================================================================
{
    "dataset_id": "string",
    "feature": "string",
    "feature_type": "numerical|categorical",
    "missingness_mechanism": "MCAR|MAR|MNAR",
    "missingness_rate": "float",
    "data_evidence": "string",
    "candidate_strategies": "list[string]",
    "recommended_strategy": "string",
    "reasoning": "string",
    "confidence": "float",
    "alternative_strategy": "string|null",
    "final_decision": "string",
    "fallback_used": "boolean"
}

In [24]:
# ============================================================
# CELL 00.10.1 — IMPUTATION EVALUATION
# ============================================================

EVALUATION_METRICS = {

    "numerical": [
        "MAE",
        "RMSE"
    ],

    "categorical": [
        "Accuracy",
        "Macro_F1"
    ],

    "distribution": [
        "KS",
        "Wasserstein"
    ],

    "relationship": [
        "Correlation_Preservation"
    ],

    "downstream": [
        "Accuracy",
        "Macro_F1",
        "ROC_AUC"
    ]
}

print("=" * 100)
print("EVALUATION METRICS")
print("=" * 100)

for category, metrics in EVALUATION_METRICS.items():

    print(f"\n{category.upper()}")

    for metric in metrics:

        print(f"  • {metric}")

====================================================================================================
EVALUATION METRICS
====================================================================================================

NUMERICAL
  • MAE
  • RMSE

CATEGORICAL
  • Accuracy
  • Macro_F1

DISTRIBUTION
  • KS
  • Wasserstein

RELATIONSHIP
  • Correlation_Preservation

DOWNSTREAM
  • Accuracy
  • Macro_F1
  • ROC_AUC

In [25]:
# ============================================================
# CELL 00.10.2 — STATISTICAL EVALUATION CONFIGURATION
# ============================================================

STATISTICAL_CONFIG = {

    "alpha": 0.05,

    "confidence_level": 0.95,

    "paired_comparison": True,

    "multiple_comparison_correction": "Holm",

    "effect_size": True,

    "confidence_interval": True,

    "report_mean": True,

    "report_standard_deviation": True,

    "report_median": True
}

print(
    json.dumps(
        STATISTICAL_CONFIG,
        indent=4
    )
)

{
    "alpha": 0.05,
    "confidence_level": 0.95,
    "paired_comparison": true,
    "multiple_comparison_correction": "Holm",
    "effect_size": true,
    "confidence_interval": true,
    "report_mean": true,
    "report_standard_deviation": true,
    "report_median": true
}

In [26]:
# ============================================================
# CELL 00.10.3 — ROBUSTNESS EVALUATION
# ============================================================

ROBUSTNESS_CONFIG = {

    "enabled": True,

    "cross_dataset": True,

    "cross_missingness_rate": True,

    "cross_missingness_mechanism": True,

    "method_consistency": True,

    "mean_rank": True,

    "rank_variability": True,

    "failure_rate": True,

    "performance_variability": True
}

print(
    json.dumps(
        ROBUSTNESS_CONFIG,
        indent=4
    )
)

{
    "enabled": true,
    "cross_dataset": true,
    "cross_missingness_rate": true,
    "cross_missingness_mechanism": true,
    "method_consistency": true,
    "mean_rank": true,
    "rank_variability": true,
    "failure_rate": true,
    "performance_variability": true
}

In [27]:
# ============================================================
# CELL 00.11.1 — UTILITY WEIGHTS
# ============================================================

UTILITY_WEIGHTS = {

    "imputation_accuracy": 0.45,

    "distribution_fidelity": 0.20,

    "downstream_utility": 0.20,

    "robustness": 0.15
}

UTILITY_WEIGHT_SUM = sum(
    UTILITY_WEIGHTS.values()
)

assert np.isclose(
    UTILITY_WEIGHT_SUM,
    1.0
), "Utility weights must sum to 1.0."

assert all(
    0.0 <= weight <= 1.0
    for weight in UTILITY_WEIGHTS.values()
), "All utility weights must be between 0 and 1."

print("=" * 100)
print("UTILITY WEIGHTS")
print("=" * 100)

for criterion, weight in UTILITY_WEIGHTS.items():

    print(
        f"{criterion:30s}: {weight:.2f}"
    )

print(
    f"\nTotal: {UTILITY_WEIGHT_SUM:.2f}"
)

====================================================================================================
UTILITY WEIGHTS
====================================================================================================
imputation_accuracy           : 0.45
distribution_fidelity         : 0.20
downstream_utility            : 0.20
robustness                    : 0.15

Total: 1.00

In [28]:
# ============================================================
# CELL 00.11.2 — UTILITY SCORE DEFINITION
# ============================================================

UTILITY_SCORE_DEFINITION = {

    "formula":
        "U = Σ(w_i × normalized_score_i)",

    "higher_is_better": [
        "imputation_accuracy",
        "distribution_fidelity",
        "downstream_utility",
        "robustness"
    ],

    "lower_is_better_raw_metrics": [
        "MAE",
        "RMSE",
        "KS",
        "Wasserstein"
    ],

    "normalization":
        "metric-specific normalization before aggregation",

    "aggregation":
        "weighted multi-criteria score",

    "primary_use":
        "secondary_analysis_only",

    "weight_sum":
        1.0
}

assert np.isclose(
    UTILITY_SCORE_DEFINITION["weight_sum"],
    UTILITY_WEIGHT_SUM
)

assert set(
    UTILITY_SCORE_DEFINITION["higher_is_better"]
) == set(
    UTILITY_WEIGHTS.keys()
)

print("=" * 100)
print("UTILITY SCORE DEFINITION")
print("=" * 100)

print(
    json.dumps(
        UTILITY_SCORE_DEFINITION,
        indent=4
    )
)

====================================================================================================
UTILITY SCORE DEFINITION
====================================================================================================
{
    "formula": "U = \u03a3(w_i \u00d7 normalized_score_i)",
    "higher_is_better": [
        "imputation_accuracy",
        "distribution_fidelity",
        "downstream_utility",
        "robustness"
    ],
    "lower_is_better_raw_metrics": [
        "MAE",
        "RMSE",
        "KS",
        "Wasserstein"
    ],
    "normalization": "metric-specific normalization before aggregation",
    "aggregation": "weighted multi-criteria score",
    "primary_use": "secondary_analysis_only",
    "weight_sum": 1.0
}

In [29]:
# ============================================================
# CELL 00.12.1 — CONFIDENCE THRESHOLDS
# ============================================================

CONFIDENCE_THRESHOLDS = {

    "high": 0.80,

    "medium": 0.60,

    "low": 0.00,

    "minimum_selection_confidence": 0.60,

    "minimum_evidence_confidence": 0.60
}

assert (
    0.0
    <= CONFIDENCE_THRESHOLDS["low"]
    <= CONFIDENCE_THRESHOLDS["medium"]
    <= CONFIDENCE_THRESHOLDS["high"]
    <= 1.0
)

assert (
    0.0
    <= CONFIDENCE_THRESHOLDS[
        "minimum_selection_confidence"
    ]
    <= 1.0
)

print("=" * 100)
print("CONFIDENCE THRESHOLDS")
print("=" * 100)

for key, value in CONFIDENCE_THRESHOLDS.items():

    print(
        f"{key:40s}: {value:.2f}"
    )

====================================================================================================
CONFIDENCE THRESHOLDS
====================================================================================================
high                                    : 0.80
medium                                  : 0.60
low                                     : 0.00
minimum_selection_confidence            : 0.60
minimum_evidence_confidence             : 0.60

In [30]:
# ============================================================
# CELL 00.12.2 — CONFIDENCE DECISION POLICY
# ============================================================

CONFIDENCE_POLICY = {

    "high":
        "accept recommendation",

    "medium":
        "accept only with empirical support",

    "low":
        "use empirical fallback",

    "below_minimum":
        "reject standalone LLM recommendation",

    "empirical_validation_required":
        True
}

print(
    json.dumps(
        CONFIDENCE_POLICY,
        indent=4
    )
)

{
    "high": "accept recommendation",
    "medium": "accept only with empirical support",
    "low": "use empirical fallback",
    "below_minimum": "reject standalone LLM recommendation",
    "empirical_validation_required": true
}

In [31]:
# ============================================================
# CELL 00.13.1 — EXPERIMENT SCENARIO REGISTRY
# ============================================================

EXPERIMENT_SCENARIO_REGISTRY = {}

scenario_number = 1

for mechanism in MISSINGNESS_CONFIG["mechanisms"]:

    for rate in MISSINGNESS_CONFIG["rates"]:

        scenario_id = f"S{scenario_number:02d}"

        # Deterministic unique seed for each scenario
        scenario_seed = (
            SEED
            + scenario_number
        )

        EXPERIMENT_SCENARIO_REGISTRY[
            scenario_id
        ] = {

            "scenario_id":
                scenario_id,

            "mechanism":
                mechanism,

            "missingness_rate":
                rate,

            "repetitions":
                MISSINGNESS_CONFIG["repetitions"],

            "target_excluded":
                MISSINGNESS_CONFIG["target_excluded"],

            "random_seed":
                scenario_seed,

            "same_scenario_across_methods":
                MISSINGNESS_CONFIG[
                    "same_scenario_across_methods"
                ]
        }

        scenario_number += 1


SCENARIO_REGISTRY_DF = pd.DataFrame(
    EXPERIMENT_SCENARIO_REGISTRY
).T.reset_index(drop=True)

display(SCENARIO_REGISTRY_DF)

print("=" * 100)
print("EXPERIMENT SCENARIO REGISTRY")
print("=" * 100)

print(
    f"Total experimental scenarios: "
    f"{len(EXPERIMENT_SCENARIO_REGISTRY)}"
)

print(
    f"Repetitions per scenario    : "
    f"{MISSINGNESS_CONFIG['repetitions']}"
)

,scenario_id,mechanism,missingness_rate,repetitions,target_excluded,random_seed,same_scenario_across_methods
0,S01,MCAR,0.1,5,True,43,True
1,S02,MCAR,0.2,5,True,44,True
2,S03,MCAR,0.3,5,True,45,True
3,S04,MCAR,0.4,5,True,46,True
4,S05,MCAR,0.5,5,True,47,True
5,S06,MAR,0.1,5,True,48,True
6,S07,MAR,0.2,5,True,49,True
7,S08,MAR,0.3,5,True,50,True
8,S09,MAR,0.4,5,True,51,True
9,S10,MAR,0.5,5,True,52,True
10,S11,MNAR,0.1,5,True,53,True
11,S12,MNAR,0.2,5,True,54,True
12,S13,MNAR,0.3,5,True,55,True
13,S14,MNAR,0.4,5,True,56,True
14,S15,MNAR,0.5,5,True,57,True

====================================================================================================
EXPERIMENT SCENARIO REGISTRY
====================================================================================================
Total experimental scenarios: 15
Repetitions per scenario    : 5

In [32]:
# ============================================================
# CELL 00.13.2 — COMPLETE EXPERIMENTAL DESIGN
# ============================================================

TOTAL_SCENARIOS = len(
    EXPERIMENT_SCENARIO_REGISTRY
)

TOTAL_REPETITIONS = (
    TOTAL_SCENARIOS
    * MISSINGNESS_CONFIG["repetitions"]
)

TOTAL_EXPERIMENT_RUNS = (
    len(DATASETS)
    * TOTAL_REPETITIONS
)

EXPERIMENT_DESIGN = {

    "datasets":
        DATASETS,

    "n_datasets":
        len(DATASETS),

    "missingness_mechanisms":
        MISSINGNESS_CONFIG["mechanisms"],

    "n_mechanisms":
        len(MISSINGNESS_CONFIG["mechanisms"]),

    "missingness_rates":
        MISSINGNESS_CONFIG["rates"],

    "n_rates":
        len(MISSINGNESS_CONFIG["rates"]),

    "scenarios_per_dataset":
        TOTAL_SCENARIOS,

    "repetitions_per_scenario":
        MISSINGNESS_CONFIG["repetitions"],

    "candidate_strategies":
        CANDIDATE_STRATEGIES,

    "n_candidate_strategies":
        len(CANDIDATE_STRATEGIES),

    "feature_level_selection":
        STRATEGY_SELECTION_POLICY[
            "selection_granularity"
        ] == "feature_level",

    "target_excluded":
        MISSINGNESS_CONFIG["target_excluded"],

    "same_scenario_across_methods":
        MISSINGNESS_CONFIG[
            "same_scenario_across_methods"
        ],

    "same_scenario_across_datasets":
        MISSINGNESS_CONFIG[
            "same_scenario_across_datasets"
        ]
}

print("=" * 100)
print("COMPLETE EXPERIMENTAL DESIGN")
print("=" * 100)

for key, value in EXPERIMENT_DESIGN.items():
    print(f"{key:35s}: {value}")

print("-" * 100)
print(f"Total scenarios per dataset : {TOTAL_SCENARIOS}")
print(f"Total repetitions           : {TOTAL_REPETITIONS}")
print(f"Total experiment runs       : {TOTAL_EXPERIMENT_RUNS}")

====================================================================================================
COMPLETE EXPERIMENTAL DESIGN
====================================================================================================
datasets                           : ['adult_income', 'bank_marketing', 'diabetes_130us']
n_datasets                         : 3
missingness_mechanisms             : ['MCAR', 'MAR', 'MNAR']
n_mechanisms                       : 3
missingness_rates                  : [0.1, 0.2, 0.3, 0.4, 0.5]
n_rates                            : 5
scenarios_per_dataset              : 15
repetitions_per_scenario           : 5
candidate_strategies               : ['Mean', 'Median', 'Mode', 'KNN', 'IterativeImputer', 'RandomForest', 'MissForest']
n_candidate_strategies             : 7
feature_level_selection            : True
target_excluded                    : True
same_scenario_across_methods       : True
same_scenario_across_datasets      : False
----------------------------------------------------------------------------------------------------
Total scenarios per dataset : 15
Total repetitions           : 75
Total experiment runs       : 225

In [33]:
# ============================================================
# CELL 00.13.3 — SCENARIO VALIDATION
# ============================================================

EXPECTED_SCENARIO_COUNT = (
    len(MISSINGNESS_CONFIG["mechanisms"])
    * len(MISSINGNESS_CONFIG["rates"])
)

assert (
    len(EXPERIMENT_SCENARIO_REGISTRY)
    == EXPECTED_SCENARIO_COUNT
), (
    "Scenario count does not match the configured "
    "missingness mechanisms × rates."
)

for scenario_number, (
    scenario_id,
    scenario
) in enumerate(
    EXPERIMENT_SCENARIO_REGISTRY.items(),
    start=1
):

    assert (
        scenario["scenario_id"]
        == scenario_id
    )

    assert (
        scenario["mechanism"]
        in {"MCAR", "MAR", "MNAR"}
    )

    assert (
        scenario["missingness_rate"]
        in MISSINGNESS_CONFIG["rates"]
    )

    assert (
        scenario["repetitions"]
        == MISSINGNESS_CONFIG["repetitions"]
    )

    expected_seed = SEED + scenario_number

    assert (
        scenario["random_seed"]
        == expected_seed
    ), (
        f"{scenario_id}: unexpected scenario seed."
    )

    assert (
        scenario["target_excluded"]
        == MISSINGNESS_CONFIG["target_excluded"]
    )

    assert (
        scenario["same_scenario_across_methods"]
        == MISSINGNESS_CONFIG[
            "same_scenario_across_methods"
        ]
    )

print("=" * 100)
print("SCENARIO VALIDATION")
print("=" * 100)
print("Experiment scenario validation: PASSED")
print(f"Validated scenarios: {len(EXPERIMENT_SCENARIO_REGISTRY)}")

====================================================================================================
SCENARIO VALIDATION
====================================================================================================
Experiment scenario validation: PASSED
Validated scenarios: 15

In [45]:
# ============================================================
# CELL 00.14.1 — PROJECT DIRECTORY CONFIGURATION
# ============================================================

DIRECTORIES = {

    "root":
        PROJECT_ROOT,

    "config":
        PROJECT_ROOT / "config",

    "data":
        PROJECT_ROOT / "data",

    "data_raw":
        PROJECT_ROOT / "data" / "raw",

    "data_processed":
        PROJECT_ROOT / "data" / "processed",

    "data_reference":
        PROJECT_ROOT / "data" / "reference",

    "experiments":
        PROJECT_ROOT / "experiments",

    "missingness":
        PROJECT_ROOT / "experiments" / "missingness",

    "imputation":
        PROJECT_ROOT / "experiments" / "imputation",

    "llm":
        PROJECT_ROOT / "experiments" / "llm",

    "evaluation":
        PROJECT_ROOT / "experiments" / "evaluation",

    "robustness":
        PROJECT_ROOT / "experiments" / "robustness",

    "models":
        PROJECT_ROOT / "models",

    "results":
        PROJECT_ROOT / "results",

    "results_raw":
        PROJECT_ROOT / "results" / "raw",

    "results_processed":
        PROJECT_ROOT / "results" / "processed",

    "tables":
        PROJECT_ROOT / "results" / "tables",

    "figures":
        PROJECT_ROOT / "results" / "figures",

    "reports":
        PROJECT_ROOT / "reports",

    "logs":
        PROJECT_ROOT / "logs",

    "artifacts":
        PROJECT_ROOT / "artifacts"
}


# ------------------------------------------------------------
# CREATE / VERIFY DIRECTORIES
# ------------------------------------------------------------

for name, path in DIRECTORIES.items():

    path = Path(path)

    path.mkdir(
        parents=True,
        exist_ok=True
    )

    DIRECTORIES[name] = path


# ------------------------------------------------------------
# VALIDATION
# ------------------------------------------------------------

assert "artifacts" in DIRECTORIES

assert (
    DIRECTORIES["artifacts"].exists()
)

assert (
    DIRECTORIES["artifacts"].is_dir()
)


print("=" * 100)
print("PROJECT DIRECTORIES CREATED / VERIFIED")
print("=" * 100)

for name, path in DIRECTORIES.items():

    print(
        f"{name:25s}: {path}"
    )

print("=" * 100)
print("Directory configuration validation: PASSED")

====================================================================================================
PROJECT DIRECTORIES CREATED / VERIFIED
====================================================================================================
root                     : /content/drive/MyDrive/AIR_LLM_Research
config                   : /content/drive/MyDrive/AIR_LLM_Research/config
data                     : /content/drive/MyDrive/AIR_LLM_Research/data
data_raw                 : /content/drive/MyDrive/AIR_LLM_Research/data/raw
data_processed           : /content/drive/MyDrive/AIR_LLM_Research/data/processed
data_reference           : /content/drive/MyDrive/AIR_LLM_Research/data/reference
experiments              : /content/drive/MyDrive/AIR_LLM_Research/experiments
missingness              : /content/drive/MyDrive/AIR_LLM_Research/experiments/missingness
imputation               : /content/drive/MyDrive/AIR_LLM_Research/experiments/imputation
llm                      : /content/drive/MyDrive/AIR_LLM_Research/experiments/llm
evaluation               : /content/drive/MyDrive/AIR_LLM_Research/experiments/evaluation
robustness               : /content/drive/MyDrive/AIR_LLM_Research/experiments/robustness
models                   : /content/drive/MyDrive/AIR_LLM_Research/models
results                  : /content/drive/MyDrive/AIR_LLM_Research/results
results_raw              : /content/drive/MyDrive/AIR_LLM_Research/results/raw
results_processed        : /content/drive/MyDrive/AIR_LLM_Research/results/processed
tables                   : /content/drive/MyDrive/AIR_LLM_Research/results/tables
figures                  : /content/drive/MyDrive/AIR_LLM_Research/results/figures
reports                  : /content/drive/MyDrive/AIR_LLM_Research/reports
logs                     : /content/drive/MyDrive/AIR_LLM_Research/logs
artifacts                : /content/drive/MyDrive/AIR_LLM_Research/artifacts
====================================================================================================
Directory configuration validation: PASSED

In [46]:
# ============================================================
# CELL 00.14.2 — DIRECTORY VALIDATION
# ============================================================

DIRECTORY_VALIDATION = []

for name, path in DIRECTORIES.items():

    DIRECTORY_VALIDATION.append({

        "directory":
            name,

        "path":
            str(path),

        "exists":
            path.exists(),

        "is_directory":
            path.is_dir(),

        "writable":
            os.access(path, os.W_OK)
    })

DIRECTORY_VALIDATION_DF = pd.DataFrame(
    DIRECTORY_VALIDATION
)

display(DIRECTORY_VALIDATION_DF)

assert (
    DIRECTORY_VALIDATION_DF["exists"].all()
), "One or more project directories do not exist."

assert (
    DIRECTORY_VALIDATION_DF["is_directory"].all()
), "One or more project paths are not directories."

assert (
    DIRECTORY_VALIDATION_DF["writable"].all()
), "One or more project directories are not writable."

print("=" * 100)
print("DIRECTORY VALIDATION")
print("=" * 100)
print("All project directories exist, are directories, and are writable.")

,directory,path,exists,is_directory,writable
0,root,/content/drive/MyDrive/AIR_LLM_Research,True,True,True
1,config,/content/drive/MyDrive/AIR_LLM_Research/config,True,True,True
2,data,/content/drive/MyDrive/AIR_LLM_Research/data,True,True,True
3,data_raw,/content/drive/MyDrive/AIR_LLM_Research/data/raw,True,True,True
4,data_processed,/content/drive/MyDrive/AIR_LLM_Research/data/p...,True,True,True
5,data_reference,/content/drive/MyDrive/AIR_LLM_Research/data/r...,True,True,True
6,experiments,/content/drive/MyDrive/AIR_LLM_Research/experi...,True,True,True
7,missingness,/content/drive/MyDrive/AIR_LLM_Research/experi...,True,True,True
8,imputation,/content/drive/MyDrive/AIR_LLM_Research/experi...,True,True,True
9,llm,/content/drive/MyDrive/AIR_LLM_Research/experi...,True,True,True
10,evaluation,/content/drive/MyDrive/AIR_LLM_Research/experi...,True,True,True
11,robustness,/content/drive/MyDrive/AIR_LLM_Research/experi...,True,True,True
12,models,/content/drive/MyDrive/AIR_LLM_Research/models,True,True,True
13,results,/content/drive/MyDrive/AIR_LLM_Research/results,True,True,True
14,results_raw,/content/drive/MyDrive/AIR_LLM_Research/result...,True,True,True
15,results_processed,/content/drive/MyDrive/AIR_LLM_Research/result...,True,True,True
16,tables,/content/drive/MyDrive/AIR_LLM_Research/result...,True,True,True
17,figures,/content/drive/MyDrive/AIR_LLM_Research/result...,True,True,True
18,reports,/content/drive/MyDrive/AIR_LLM_Research/reports,True,True,True
19,logs,/content/drive/MyDrive/AIR_LLM_Research/logs,True,True,True
20,artifacts,/content/drive/MyDrive/AIR_LLM_Research/artifacts,True,True,True

====================================================================================================
DIRECTORY VALIDATION
====================================================================================================
All project directories exist, are directories, and are writable.

In [47]:
# ============================================================
# CELL 00.15.1 — MASTER CONFIGURATION
# ============================================================

SERIALIZABLE_DATASET_REGISTRY = {}

for dataset_id, metadata in DATASET_REGISTRY.items():

    SERIALIZABLE_DATASET_REGISTRY[dataset_id] = {
        key: (
            str(value)
            if isinstance(value, Path)
            else value
        )
        for key, value in metadata.items()
    }

MASTER_CONFIG = {

    "project": {

        "name":
            PROJECT_NAME,

        "code":
            PROJECT_CODE,

        "version":
            PROJECT_VERSION,

        "experiment_version":
            EXPERIMENT_VERSION,

        "configuration_version":
            CONFIGURATION_VERSION
    },

    "environment": {

        "packages":
            PACKAGE_VERSIONS,

        "runtime":
            RUNTIME_INFO
    },

    "reproducibility": {

        "seed":
            SEED,

        "pytorch":
            PYTORCH_REPRODUCIBILITY
    },

    "project_root":
        str(PROJECT_ROOT),

    "directories": {
        name: str(path)
        for name, path
        in DIRECTORIES.items()
    },

    "datasets":
        SERIALIZABLE_DATASET_REGISTRY,

    "dataset_paths": {

        dataset_id: {

            key: str(value)

            for key, value
            in paths.items()
        }

        for dataset_id, paths
        in DATASET_PATHS.items()
    },

    "feature_target":
        FEATURE_TARGET_REGISTRY,

    "feature_type_policy":
        FEATURE_TYPE_POLICY,

    "missingness":
        MISSINGNESS_CONFIG,

    "split":
        SPLIT_CONFIG,

    "candidate_strategies":
        CANDIDATE_STRATEGY_REGISTRY,

    "strategy_selection_policy":
        STRATEGY_SELECTION_POLICY,

    "llm":
        LLM_CONFIG,

    "llm_output_schema":
        LLM_OUTPUT_SCHEMA,

    "evaluation":
        EVALUATION_METRICS,

    "statistical":
        STATISTICAL_CONFIG,

    "robustness":
        ROBUSTNESS_CONFIG,

    "utility_weights":
        UTILITY_WEIGHTS,

    "utility_score_definition":
        UTILITY_SCORE_DEFINITION,

    "confidence_thresholds":
        CONFIDENCE_THRESHOLDS,

    "confidence_policy":
        CONFIDENCE_POLICY,

    "experiment_scenarios":
        EXPERIMENT_SCENARIO_REGISTRY,

    "experiment_design":
        EXPERIMENT_DESIGN,

    "notebook_registry": {

        "00":
            "00_Project_Configuration.ipynb",

        "01":
            "01_Dataset_Preparation.ipynb",

        "02":
            "02_Data_Preprocessing_and_Splitting.ipynb",

        "03":
            "03_Missingness_Generation.ipynb",

        "04":
            "04_Candidate_Imputation_Methods.ipynb",

        "05":
            "05_LLM_Recommendation_and_Strategy_Selection.ipynb",

        "06":
            "06_AIR_LLM_Imputation.ipynb",

        "07":
            "07_Imputation_Evaluation.ipynb",

        "08":
            "08_Dataset_Wise_Analysis.ipynb",

        "09":
            "09_Cross_Dataset_Robustness_and_Interpretation.ipynb",

        "10":
            "10_Final_Research_Reporting.ipynb"
    }
}

print("=" * 100)
print("MASTER CONFIGURATION")
print("=" * 100)

print("Master configuration object created.")
print(
    f"Configuration sections: "
    f"{len(MASTER_CONFIG)}"
)

====================================================================================================
MASTER CONFIGURATION
====================================================================================================
Master configuration object created.
Configuration sections: 25

In [48]:
# ============================================================
# CELL 00.15.2 — FINAL MASTER YAML CONFIGURATION EXPORT
# ============================================================
#
# Purpose:
#   1. Convert every configuration value to YAML-safe
#      native Python objects.
#   2. Remove library-specific objects.
#   3. Save the permanent master configuration to Drive.
#   4. Reload the YAML immediately.
#   5. Validate the saved configuration.
#   6. Save a configuration manifest for reproducibility.
# ============================================================

from pathlib import Path
import json
import numbers
import yaml
import numpy as np


# ------------------------------------------------------------
# 1. UNIVERSAL YAML-SAFE CONVERSION
# ------------------------------------------------------------

def _yaml_safe(value):

    if value is None:
        return None

    if type(value) is str:
        return value

    if type(value) is int:
        return value

    if type(value) is float:
        return value

    if type(value) is bool:
        return value

    if isinstance(value, Path):
        return str(value)

    if isinstance(value, np.generic):
        return _yaml_safe(value.item())

    if isinstance(value, np.ndarray):
        return [
            _yaml_safe(v)
            for v in value.tolist()
        ]

    if isinstance(value, dict):
        return {
            str(_yaml_safe(key)): _yaml_safe(val)
            for key, val in value.items()
        }

    if isinstance(value, (list, tuple)):
        return [
            _yaml_safe(v)
            for v in value
        ]

    if isinstance(value, set):
        return [
            _yaml_safe(v)
            for v in sorted(
                value,
                key=lambda x: str(x)
            )
        ]

    if isinstance(value, numbers.Integral):
        return int(value)

    if isinstance(value, numbers.Real):
        return float(value)

    return str(value)


# ------------------------------------------------------------
# 2. REQUIRED OBJECTS
# ------------------------------------------------------------

if "MASTER_CONFIG" not in globals():
    raise RuntimeError(
        "MASTER_CONFIG is not defined. "
        "Run CELL 00.15.1 first."
    )

if "DIRECTORIES" not in globals():
    raise RuntimeError(
        "DIRECTORIES is not defined. "
        "Run CELL 00.14.1 first."
    )


# ------------------------------------------------------------
# 3. CONVERT MASTER CONFIGURATION
# ------------------------------------------------------------

MASTER_CONFIG_SERIALIZABLE = _yaml_safe(
    MASTER_CONFIG
)


# ------------------------------------------------------------
# 4. SERIALIZATION SAFETY CHECK
# ------------------------------------------------------------

try:

    json.dumps(
        MASTER_CONFIG_SERIALIZABLE,
        ensure_ascii=False
    )

except TypeError as error:

    raise TypeError(
        "MASTER_CONFIG contains a non-serializable object "
        f"after conversion: {error}"
    )


# ------------------------------------------------------------
# 5. CONFIGURATION DIRECTORY
# ------------------------------------------------------------

CONFIG_DIR = Path(
    DIRECTORIES["config"]
)

CONFIG_DIR.mkdir(
    parents=True,
    exist_ok=True
)

if not os.access(CONFIG_DIR, os.W_OK):
    raise PermissionError(
        f"Configuration directory is not writable: {CONFIG_DIR}"
    )


# ------------------------------------------------------------
# 6. MASTER YAML PATH
# ------------------------------------------------------------

CONFIG_PATH = (
    CONFIG_DIR / "config.yaml"
)


# ------------------------------------------------------------
# 7. SAVE MASTER YAML
# ------------------------------------------------------------

with open(
    CONFIG_PATH,
    "w",
    encoding="utf-8"
) as file:

    yaml.safe_dump(
        MASTER_CONFIG_SERIALIZABLE,
        file,
        sort_keys=False,
        allow_unicode=True,
        default_flow_style=False,
        indent=2,
        width=120
    )


# ------------------------------------------------------------
# 8. VERIFY SAVED FILE
# ------------------------------------------------------------

if not CONFIG_PATH.exists():
    raise RuntimeError(
        "Master configuration file was not created."
    )

if CONFIG_PATH.stat().st_size == 0:
    raise RuntimeError(
        "Master configuration file is empty."
    )


# ------------------------------------------------------------
# 9. RELOAD SAVED YAML
# ------------------------------------------------------------

with open(
    CONFIG_PATH,
    "r",
    encoding="utf-8"
) as file:

    MASTER_CONFIG_LOADED = yaml.safe_load(file)


if not isinstance(
    MASTER_CONFIG_LOADED,
    dict
):

    raise RuntimeError(
        "Reloaded MASTER_CONFIG is not a dictionary."
    )


# ------------------------------------------------------------
# 10. VERIFY PROJECT ROOT
# ------------------------------------------------------------

saved_project_root = str(
    MASTER_CONFIG_SERIALIZABLE["project_root"]
)

expected_project_root = str(
    PROJECT_ROOT
)

assert (
    saved_project_root == expected_project_root
), (
    "PROJECT_ROOT mismatch in saved configuration.\n"
    f"Expected: {expected_project_root}\n"
    f"Saved:    {saved_project_root}"
)


# ------------------------------------------------------------
# 11. REQUIRED CONFIGURATION SECTIONS
# ------------------------------------------------------------

EXPECTED_CONFIG_SECTIONS = [

    "project",
    "environment",
    "reproducibility",
    "project_root",
    "directories",
    "datasets",
    "dataset_paths",
    "feature_target",
    "feature_type_policy",
    "missingness",
    "split",
    "candidate_strategies",
    "strategy_selection_policy",
    "llm",
    "llm_output_schema",
    "evaluation",
    "statistical",
    "robustness",
    "utility_weights",
    "utility_score_definition",
    "confidence_thresholds",
    "confidence_policy",
    "experiment_scenarios",
    "experiment_design",
    "notebook_registry"
]

MISSING_SECTIONS = [
    section
    for section in EXPECTED_CONFIG_SECTIONS
    if section not in MASTER_CONFIG_SERIALIZABLE
]

if MISSING_SECTIONS:

    raise RuntimeError(
        "Master configuration is incomplete. "
        f"Missing sections: {MISSING_SECTIONS}"
    )


# ------------------------------------------------------------
# 12. VERIFY RELOADED CONFIGURATION
# ------------------------------------------------------------

for section in EXPECTED_CONFIG_SECTIONS:

    assert section in MASTER_CONFIG_LOADED, (
        f"Reloaded YAML is missing section: {section}"
    )


# ------------------------------------------------------------
# 13. VERIFY DATASET REGISTRY
# ------------------------------------------------------------

SAVED_DATASETS = (
    MASTER_CONFIG_LOADED["datasets"]
)

assert isinstance(
    SAVED_DATASETS,
    dict
)

assert set(SAVED_DATASETS.keys()) == set(
    DATASET_REGISTRY.keys()
)


# ------------------------------------------------------------
# 14. VERIFY DATASET PATH REGISTRY
# ------------------------------------------------------------

SAVED_DATASET_PATHS = (
    MASTER_CONFIG_LOADED["dataset_paths"]
)

assert set(
    SAVED_DATASET_PATHS.keys()
) == set(
    DATASET_PATHS.keys()
)


# ------------------------------------------------------------
# 15. WRITE CONFIGURATION MANIFEST
# ------------------------------------------------------------

MANIFEST_PATH = (
    CONFIG_DIR
    / "configuration_manifest.json"
)

MANIFEST = {

    "configuration_file":
        str(CONFIG_PATH),

    "configuration_size_bytes":
        int(CONFIG_PATH.stat().st_size),

    "configuration_sections":
        list(
            MASTER_CONFIG_SERIALIZABLE.keys()
        ),

    "expected_sections":
        EXPECTED_CONFIG_SECTIONS,

    "missing_required_sections":
        MISSING_SECTIONS,

    "dataset_count":
        len(SAVED_DATASETS),

    "datasets":
        list(SAVED_DATASETS.keys()),

    "yaml_serialization":
        "PASSED",

    "yaml_reload":
        "PASSED",

    "json_serialization":
        "PASSED",

    "project_root_validation":
        "PASSED",

    "dataset_registry_validation":
        "PASSED",

    "dataset_path_validation":
        "PASSED"
}

with open(
    MANIFEST_PATH,
    "w",
    encoding="utf-8"
) as file:

    json.dump(
        MANIFEST,
        file,
        indent=2,
        ensure_ascii=False
    )


# ------------------------------------------------------------
# 16. FINAL OUTPUT
# ------------------------------------------------------------

print()
print("=" * 100)
print("AIR-LLM MASTER CONFIGURATION EXPORT")
print("=" * 100)

print(
    f"Master YAML configuration : {CONFIG_PATH}"
)

print(
    f"Configuration size         : "
    f"{CONFIG_PATH.stat().st_size:,} bytes"
)

print(
    f"Manifest                   : {MANIFEST_PATH}"
)

print(
    "YAML serialization         : PASSED"
)

print(
    "YAML reload validation     : PASSED"
)

print(
    "JSON serialization         : PASSED"
)

print(
    "Project root validation    : PASSED"
)

print(
    "Dataset registry           : PASSED"
)

print(
    "Dataset path registry      : PASSED"
)

print(
    f"Configuration sections     : "
    f"{len(MASTER_CONFIG_SERIALIZABLE)}"
)

print()
print("Required configuration sections: ")

for section in EXPECTED_CONFIG_SECTIONS:

    print(f"  [OK] {section}")

print("=" * 100)
print("CELL 00.15.2 COMPLETED SUCCESSFULLY")
print("=" * 100)

====================================================================================================
AIR-LLM MASTER CONFIGURATION EXPORT
====================================================================================================
Master YAML configuration : /content/drive/MyDrive/AIR_LLM_Research/config/config.yaml
Configuration size         : 13,191 bytes
Manifest                   : /content/drive/MyDrive/AIR_LLM_Research/config/configuration_manifest.json
YAML serialization         : PASSED
YAML reload validation     : PASSED
JSON serialization         : PASSED
Project root validation    : PASSED
Dataset registry           : PASSED
Dataset path registry      : PASSED
Configuration sections     : 25

Required configuration sections:
  [OK] project
  [OK] environment
  [OK] reproducibility
  [OK] project_root
  [OK] directories
  [OK] datasets
  [OK] dataset_paths
  [OK] feature_target
  [OK] feature_type_policy
  [OK] missingness
  [OK] split
  [OK] candidate_strategies
  [OK] strategy_selection_policy
  [OK] llm
  [OK] llm_output_schema
  [OK] evaluation
  [OK] statistical
  [OK] robustness
  [OK] utility_weights
  [OK] utility_score_definition
  [OK] confidence_thresholds
  [OK] confidence_policy
  [OK] experiment_scenarios
  [OK] experiment_design
  [OK] notebook_registry
====================================================================================================
CELL 00.15.2 COMPLETED SUCCESSFULLY
====================================================================================================

In [49]:
# ============================================================
# CELL 00.15.3 — SAVE DATASET REGISTRY
# ============================================================

DATASET_REGISTRY_PATH = (
    Path(DIRECTORIES["config"])
    / "dataset_registry.yaml"
)

DATASET_REGISTRY_SERIALIZABLE = _yaml_safe(
    DATASET_REGISTRY
)

with open(
    DATASET_REGISTRY_PATH,
    "w",
    encoding="utf-8"
) as file:

    yaml.safe_dump(
        DATASET_REGISTRY_SERIALIZABLE,
        file,
        sort_keys=False,
        allow_unicode=True,
        default_flow_style=False,
        indent=2
    )

if not DATASET_REGISTRY_PATH.exists():
    raise RuntimeError(
        "Dataset registry was not saved."
    )

if DATASET_REGISTRY_PATH.stat().st_size == 0:
    raise RuntimeError(
        "Dataset registry file is empty."
    )


# ------------------------------------------------------------
# RELOAD AND VALIDATE
# ------------------------------------------------------------

with open(
    DATASET_REGISTRY_PATH,
    "r",
    encoding="utf-8"
) as file:

    DATASET_REGISTRY_LOADED = yaml.safe_load(file)

assert isinstance(
    DATASET_REGISTRY_LOADED,
    dict
)

assert set(
    DATASET_REGISTRY_LOADED.keys()
) == set(
    DATASET_REGISTRY.keys()
)

print("=" * 100)
print("DATASET REGISTRY PERSISTENCE")
print("=" * 100)

print(
    f"Registry path : {DATASET_REGISTRY_PATH}"
)

print(
    f"Datasets      : {len(DATASET_REGISTRY_LOADED)}"
)

print(
    f"File size     : "
    f"{DATASET_REGISTRY_PATH.stat().st_size:,} bytes"
)

print("Save validation   : PASSED")
print("Reload validation : PASSED")
print("=" * 100)

====================================================================================================
DATASET REGISTRY PERSISTENCE
====================================================================================================
Registry path : /content/drive/MyDrive/AIR_LLM_Research/config/dataset_registry.yaml
Datasets      : 3
File size     : 1,225 bytes
Save validation   : PASSED
Reload validation : PASSED
====================================================================================================

In [50]:
# ============================================================
# CELL 00.15.4 — SAVE FEATURE / TARGET REGISTRY
# ============================================================

FEATURE_TARGET_REGISTRY_PATH = (
    Path(DIRECTORIES["config"])
    / "feature_target_registry.yaml"
)

FEATURE_TARGET_REGISTRY_SERIALIZABLE = _yaml_safe(
    FEATURE_TARGET_REGISTRY
)

with open(
    FEATURE_TARGET_REGISTRY_PATH,
    "w",
    encoding="utf-8"
) as file:

    yaml.safe_dump(
        FEATURE_TARGET_REGISTRY_SERIALIZABLE,
        file,
        sort_keys=False,
        allow_unicode=True,
        default_flow_style=False,
        indent=2
    )


# ------------------------------------------------------------
# VERIFY SAVED FILE
# ------------------------------------------------------------

if not FEATURE_TARGET_REGISTRY_PATH.exists():
    raise RuntimeError(
        "Feature/target registry was not saved."
    )

if FEATURE_TARGET_REGISTRY_PATH.stat().st_size == 0:
    raise RuntimeError(
        "Feature/target registry file is empty."
    )


# ------------------------------------------------------------
# RELOAD AND VALIDATE
# ------------------------------------------------------------

with open(
    FEATURE_TARGET_REGISTRY_PATH,
    "r",
    encoding="utf-8"
) as file:

    FEATURE_TARGET_REGISTRY_LOADED = (
        yaml.safe_load(file)
    )

assert isinstance(
    FEATURE_TARGET_REGISTRY_LOADED,
    dict
)

assert set(
    FEATURE_TARGET_REGISTRY_LOADED.keys()
) == set(
    FEATURE_TARGET_REGISTRY.keys()
)


# ------------------------------------------------------------
# VALIDATE DATASET TARGET CONSISTENCY
# ------------------------------------------------------------

for dataset_id, config in (
    FEATURE_TARGET_REGISTRY_LOADED.items()
):

    assert dataset_id in DATASET_REGISTRY, (
        f"Unknown dataset in feature/target registry: "
        f"{dataset_id}"
    )

    assert (
        config["target"]
        == DATASET_REGISTRY[dataset_id]["target"]
    ), (
        f"Target mismatch for {dataset_id}: "
        f"{config['target']} != "
        f"{DATASET_REGISTRY[dataset_id]['target']}"
    )


# ------------------------------------------------------------
# FINAL OUTPUT
# ------------------------------------------------------------

print("=" * 100)
print("FEATURE / TARGET REGISTRY PERSISTENCE")
print("=" * 100)

print(
    f"Registry path : "
    f"{FEATURE_TARGET_REGISTRY_PATH}"
)

print(
    f"Datasets      : "
    f"{len(FEATURE_TARGET_REGISTRY_LOADED)}"
)

print(
    f"File size     : "
    f"{FEATURE_TARGET_REGISTRY_PATH.stat().st_size:,} bytes"
)

print("Save validation      : PASSED")
print("Reload validation    : PASSED")
print("Target consistency   : PASSED")

print("=" * 100)

====================================================================================================
FEATURE / TARGET REGISTRY PERSISTENCE
====================================================================================================
Registry path : /content/drive/MyDrive/AIR_LLM_Research/config/feature_target_registry.yaml
Datasets      : 3
File size     : 543 bytes
Save validation      : PASSED
Reload validation    : PASSED
Target consistency   : PASSED
====================================================================================================

In [51]:
# ============================================================
# CELL 00.15.5 — SAVE EXPERIMENT SCENARIO REGISTRY
# ============================================================

SCENARIO_REGISTRY_PATH = (
    Path(DIRECTORIES["config"])
    / "experiment_scenario_registry.yaml"
)

SCENARIO_REGISTRY_SERIALIZABLE = _yaml_safe(
    EXPERIMENT_SCENARIO_REGISTRY
)

with open(
    SCENARIO_REGISTRY_PATH,
    "w",
    encoding="utf-8"
) as file:

    yaml.safe_dump(
        SCENARIO_REGISTRY_SERIALIZABLE,
        file,
        sort_keys=False,
        allow_unicode=True,
        default_flow_style=False,
        indent=2
    )


# ------------------------------------------------------------
# VERIFY SAVED FILE
# ------------------------------------------------------------

assert SCENARIO_REGISTRY_PATH.exists(), (
    "Experiment scenario registry was not saved."
)

assert SCENARIO_REGISTRY_PATH.stat().st_size > 0, (
    "Experiment scenario registry file is empty."
)


# ------------------------------------------------------------
# RELOAD SAVED REGISTRY
# ------------------------------------------------------------

with open(
    SCENARIO_REGISTRY_PATH,
    "r",
    encoding="utf-8"
) as file:

    EXPERIMENT_SCENARIO_REGISTRY_LOADED = (
        yaml.safe_load(file)
    )


# ------------------------------------------------------------
# BASIC VALIDATION
# ------------------------------------------------------------

assert isinstance(
    EXPERIMENT_SCENARIO_REGISTRY_LOADED,
    dict
)

assert set(
    EXPERIMENT_SCENARIO_REGISTRY_LOADED.keys()
) == set(
    EXPERIMENT_SCENARIO_REGISTRY.keys()
)


# ------------------------------------------------------------
# SCENARIO VALIDATION
# ------------------------------------------------------------

for scenario_id, scenario in (
    EXPERIMENT_SCENARIO_REGISTRY_LOADED.items()
):

    assert (
        scenario["scenario_id"]
        == scenario_id
    )

    assert (
        scenario["mechanism"]
        in MISSINGNESS_CONFIG["mechanisms"]
    )

    assert (
        scenario["missingness_rate"]
        in MISSINGNESS_CONFIG["rates"]
    )

    assert (
        scenario["repetitions"]
        == MISSINGNESS_CONFIG["repetitions"]
    )

    assert (
        scenario["target_excluded"]
        == MISSINGNESS_CONFIG["target_excluded"]
    )

    assert isinstance(
        scenario["random_seed"],
        int
    )

    assert (
        scenario["random_seed"] >= SEED
    ), (
        f"{scenario_id}: invalid scenario seed."
    )


# ------------------------------------------------------------
# FINAL OUTPUT
# ------------------------------------------------------------

print("=" * 100)
print("EXPERIMENT SCENARIO REGISTRY PERSISTENCE")
print("=" * 100)

print(
    f"Registry path : {SCENARIO_REGISTRY_PATH}"
)

print(
    f"Scenarios     : "
    f"{len(EXPERIMENT_SCENARIO_REGISTRY_LOADED)}"
)

print(
    f"File size     : "
    f"{SCENARIO_REGISTRY_PATH.stat().st_size:,} bytes"
)

print("Save validation       : PASSED")
print("Reload validation     : PASSED")
print("Scenario validation   : PASSED")

print("=" * 100)

====================================================================================================
EXPERIMENT SCENARIO REGISTRY PERSISTENCE
====================================================================================================
Registry path : /content/drive/MyDrive/AIR_LLM_Research/config/experiment_scenario_registry.yaml
Scenarios     : 15
File size     : 2,425 bytes
Save validation       : PASSED
Reload validation     : PASSED
Scenario validation   : PASSED
====================================================================================================

In [52]:
# ============================================================
# CELL 00.15.6 — SAVE EXPERIMENT DESIGN
# ============================================================

EXPERIMENT_DESIGN_PATH = (
    Path(DIRECTORIES["config"])
    / "experiment_design.yaml"
)

EXPERIMENT_DESIGN_SERIALIZABLE = _yaml_safe(
    EXPERIMENT_DESIGN
)

with open(
    EXPERIMENT_DESIGN_PATH,
    "w",
    encoding="utf-8"
) as file:

    yaml.safe_dump(
        EXPERIMENT_DESIGN_SERIALIZABLE,
        file,
        sort_keys=False,
        allow_unicode=True,
        default_flow_style=False,
        indent=2
    )


# ------------------------------------------------------------
# VERIFY SAVED FILE
# ------------------------------------------------------------

assert EXPERIMENT_DESIGN_PATH.exists(), (
    "Experiment design was not saved."
)

assert EXPERIMENT_DESIGN_PATH.stat().st_size > 0, (
    "Experiment design file is empty."
)


# ------------------------------------------------------------
# RELOAD
# ------------------------------------------------------------

with open(
    EXPERIMENT_DESIGN_PATH,
    "r",
    encoding="utf-8"
) as file:

    EXPERIMENT_DESIGN_LOADED = yaml.safe_load(file)


# ------------------------------------------------------------
# BASIC VALIDATION
# ------------------------------------------------------------

assert isinstance(
    EXPERIMENT_DESIGN_LOADED,
    dict
)


# ------------------------------------------------------------
# VALIDATE DATASETS
# ------------------------------------------------------------

assert (
    EXPERIMENT_DESIGN_LOADED["datasets"]
    == EXPERIMENT_DESIGN["datasets"]
)


assert (
    EXPERIMENT_DESIGN_LOADED["n_datasets"]
    == EXPERIMENT_DESIGN["n_datasets"]
)


# ------------------------------------------------------------
# VALIDATE MISSINGNESS DESIGN
# ------------------------------------------------------------

assert (
    EXPERIMENT_DESIGN_LOADED[
        "missingness_mechanisms"
    ]
    == EXPERIMENT_DESIGN[
        "missingness_mechanisms"
    ]
)


assert (
    EXPERIMENT_DESIGN_LOADED[
        "missingness_rates"
    ]
    == EXPERIMENT_DESIGN[
        "missingness_rates"
    ]
)


assert (
    EXPERIMENT_DESIGN_LOADED[
        "n_mechanisms"
    ]
    == len(
        MISSINGNESS_CONFIG["mechanisms"]
    )
)


assert (
    EXPERIMENT_DESIGN_LOADED[
        "n_rates"
    ]
    == len(
        MISSINGNESS_CONFIG["rates"]
    )
)


# ------------------------------------------------------------
# VALIDATE REPETITIONS
# ------------------------------------------------------------

assert (
    EXPERIMENT_DESIGN_LOADED[
        "repetitions_per_scenario"
    ]
    == MISSINGNESS_CONFIG[
        "repetitions"
    ]
)


# ------------------------------------------------------------
# VALIDATE CANDIDATE STRATEGIES
# ------------------------------------------------------------

assert (
    EXPERIMENT_DESIGN_LOADED[
        "candidate_strategies"
    ]
    == CANDIDATE_STRATEGIES
)


assert (
    EXPERIMENT_DESIGN_LOADED[
        "n_candidate_strategies"
    ]
    == len(CANDIDATE_STRATEGIES)
)


# ------------------------------------------------------------
# VALIDATE EXPERIMENTAL POLICIES
# ------------------------------------------------------------

assert (
    EXPERIMENT_DESIGN_LOADED[
        "feature_level_selection"
    ]
    is True
)


assert (
    EXPERIMENT_DESIGN_LOADED[
        "target_excluded"
    ] is True
)


# ------------------------------------------------------------
# VALIDATE SCENARIO REGISTRY CONSISTENCY
# ------------------------------------------------------------

assert (
    EXPERIMENT_DESIGN_LOADED[
        "scenarios_per_dataset"
    ]
    == len(
        EXPERIMENT_SCENARIO_REGISTRY
    )
), (
    "Experiment design and scenario registry "
    "are inconsistent."
)


# ------------------------------------------------------------
# VALIDATE TOTAL EXPERIMENT RUNS
# ------------------------------------------------------------

EXPECTED_TOTAL_RUNS = (
    len(DATASETS)
    * len(EXPERIMENT_SCENARIO_REGISTRY)
    * MISSINGNESS_CONFIG["repetitions"]
)

print("=" * 100)
print("EXPERIMENT DESIGN PERSISTENCE")
print("=" * 100)

print(
    f"Design path : {EXPERIMENT_DESIGN_PATH}"
)

print(
    f"File size   : "
    f"{EXPERIMENT_DESIGN_PATH.stat().st_size:,} bytes"
)

print(
    f"Datasets    : {len(DATASETS)}"
)

print(
    f"Scenarios   : "
    f"{len(EXPERIMENT_SCENARIO_REGISTRY)}"
)

print(
    f"Repetitions : "
    f"{MISSINGNESS_CONFIG['repetitions']}"
)

print(
    f"Total runs  : "
    f"{EXPECTED_TOTAL_RUNS}"
)

print()
print("Save validation       : PASSED")
print("Reload validation     : PASSED")
print("Scenario consistency  : PASSED")
print("Strategy consistency  : PASSED")
print("Experimental design   : PASSED")

print("=" * 100)

====================================================================================================
EXPERIMENT DESIGN PERSISTENCE
====================================================================================================
Design path : /content/drive/MyDrive/AIR_LLM_Research/config/experiment_design.yaml
File size   : 495 bytes
Datasets    : 3
Scenarios   : 15
Repetitions : 5
Total runs  : 225

Save validation       : PASSED
Reload validation     : PASSED
Scenario consistency  : PASSED
Strategy consistency  : PASSED
Experimental design   : PASSED
====================================================================================================

In [53]:
# ============================================================
# CELL 00.15.7 — SAVE CONFIGURATION SNAPSHOT
# ============================================================

CONFIG_SNAPSHOT_PATH = (
    Path(DIRECTORIES["artifacts"])
    / "configuration_snapshot.json"
)

CONFIG_SNAPSHOT = {

    "created_at":
        datetime.now(timezone.utc).isoformat(),

    "project":
        PROJECT_NAME,

    "project_version":
        PROJECT_VERSION,

    "experiment_version":
        EXPERIMENT_VERSION,

    "configuration_version":
        CONFIGURATION_VERSION,

    "seed":
        SEED,

    "package_versions":
        PACKAGE_VERSIONS,

    "runtime":
        RUNTIME_INFO,

    "datasets":
        DATASETS,

    "scenarios":
        list(
            EXPERIMENT_SCENARIO_REGISTRY.keys()
        ),

    "candidate_strategies":
        CANDIDATE_STRATEGIES
}


# ------------------------------------------------------------
# CONVERT TO JSON-SAFE OBJECT
# ------------------------------------------------------------

CONFIG_SNAPSHOT_SERIALIZABLE = _yaml_safe(
    CONFIG_SNAPSHOT
)


# ------------------------------------------------------------
# SAVE SNAPSHOT
# ------------------------------------------------------------

with open(
    CONFIG_SNAPSHOT_PATH,
    "w",
    encoding="utf-8"
) as file:

    json.dump(
        CONFIG_SNAPSHOT_SERIALIZABLE,
        file,
        indent=4,
        ensure_ascii=False
    )


# ------------------------------------------------------------
# VERIFY FILE
# ------------------------------------------------------------

assert CONFIG_SNAPSHOT_PATH.exists(), (
    "Configuration snapshot was not saved."
)

assert CONFIG_SNAPSHOT_PATH.stat().st_size > 0, (
    "Configuration snapshot is empty."
)


# ------------------------------------------------------------
# RELOAD SNAPSHOT
# ------------------------------------------------------------

with open(
    CONFIG_SNAPSHOT_PATH,
    "r",
    encoding="utf-8"
) as file:

    CONFIG_SNAPSHOT_LOADED = json.load(file)


# ------------------------------------------------------------
# VALIDATE SNAPSHOT
# ------------------------------------------------------------

assert isinstance(
    CONFIG_SNAPSHOT_LOADED,
    dict
)

assert (
    CONFIG_SNAPSHOT_LOADED["project"]
    == PROJECT_NAME
)

assert (
    CONFIG_SNAPSHOT_LOADED["project_version"]
    == PROJECT_VERSION
)

assert (
    CONFIG_SNAPSHOT_LOADED["experiment_version"]
    == EXPERIMENT_VERSION
)

assert (
    CONFIG_SNAPSHOT_LOADED["configuration_version"]
    == CONFIGURATION_VERSION
)

assert (
    CONFIG_SNAPSHOT_LOADED["seed"]
    == SEED
)

assert (
    CONFIG_SNAPSHOT_LOADED["datasets"]
    == DATASETS
)

assert (
    CONFIG_SNAPSHOT_LOADED["scenarios"]
    == list(
        EXPERIMENT_SCENARIO_REGISTRY.keys()
    )
)

assert (
    CONFIG_SNAPSHOT_LOADED[
        "candidate_strategies"
    ]
    == CANDIDATE_STRATEGIES
)


# ------------------------------------------------------------
# FINAL OUTPUT
# ------------------------------------------------------------

print("=" * 100)
print("CONFIGURATION SNAPSHOT")
print("=" * 100)

print(
    f"Snapshot path : {CONFIG_SNAPSHOT_PATH}"
)

print(
    f"File size     : "
    f"{CONFIG_SNAPSHOT_PATH.stat().st_size:,} bytes"
)

print(
    f"Datasets      : {len(DATASETS)}"
)

print(
    f"Scenarios     : "
    f"{len(EXPERIMENT_SCENARIO_REGISTRY)}"
)

print(
    f"Strategies    : {len(CANDIDATE_STRATEGIES)}"
)

print()
print("Save validation   : PASSED")
print("Reload validation : PASSED")
print("Content validation: PASSED")

print("=" * 100)

====================================================================================================
CONFIGURATION SNAPSHOT
====================================================================================================
Snapshot path : /content/drive/MyDrive/AIR_LLM_Research/artifacts/configuration_snapshot.json
File size     : 1,241 bytes
Datasets      : 3
Scenarios     : 15
Strategies    : 7

Save validation   : PASSED
Reload validation : PASSED
Content validation: PASSED
====================================================================================================

In [55]:
# ============================================================
# CELL 00.15.8 — EXPERIMENT TRACKING TEMPLATE
# ============================================================

EXPERIMENT_TRACKING_COLUMNS = [

    "experiment_id",
    "dataset_id",
    "scenario_id",
    "mechanism",
    "missingness_rate",
    "repetition",
    "feature",
    "feature_type",
    "candidate_strategy",
    "llm_recommendation",
    "final_strategy",
    "llm_confidence",
    "fallback_used",
    "status",
    "timestamp"
]

EXPERIMENT_TRACKING_PATH = (
    Path(DIRECTORIES["logs"])
    / "experiment_tracking.csv"
)


# ------------------------------------------------------------
# CREATE OR MIGRATE TRACKING FILE
# ------------------------------------------------------------

if EXPERIMENT_TRACKING_PATH.exists():

    EXISTING_TRACKING_DF = pd.read_csv(
        EXPERIMENT_TRACKING_PATH
    )

    EXISTING_COLUMNS = list(
        EXISTING_TRACKING_DF.columns
    )

    # --------------------------------------------------------
    # Existing schema already correct
    # --------------------------------------------------------

    if EXISTING_COLUMNS == EXPERIMENT_TRACKING_COLUMNS:

        EXPERIMENT_TRACKING_DF = (
            EXISTING_TRACKING_DF
        )

    # --------------------------------------------------------
    # Existing file has data but older schema
    # --------------------------------------------------------

    else:

        print(
            "Existing experiment tracking schema differs "
            "from the current research schema."
        )

        print(
            f"Existing columns : {EXISTING_COLUMNS}"
        )

        print(
            f"Required columns : {EXPERIMENT_TRACKING_COLUMNS}"
        )

        # Preserve existing data.
        # Add missing columns without deleting records.

        EXPERIMENT_TRACKING_DF = (
            EXISTING_TRACKING_DF.copy()
        )

        for column in EXPERIMENT_TRACKING_COLUMNS:

            if column not in EXPERIMENT_TRACKING_DF.columns:

                EXPERIMENT_TRACKING_DF[column] = pd.NA

        # Keep the new canonical column order.
        EXPERIMENT_TRACKING_DF = (
            EXPERIMENT_TRACKING_DF[
                EXPERIMENT_TRACKING_COLUMNS
            ]
        )

        # Save migrated schema.
        EXPERIMENT_TRACKING_DF.to_csv(
            EXPERIMENT_TRACKING_PATH,
            index=False
        )

        print(
            "Existing tracking file migrated "
            "to the canonical schema."
        )


# ------------------------------------------------------------
# CREATE NEW FILE IF ABSENT
# ------------------------------------------------------------

else:

    EXPERIMENT_TRACKING_DF = pd.DataFrame(
        columns=EXPERIMENT_TRACKING_COLUMNS
    )

    EXPERIMENT_TRACKING_DF.to_csv(
        EXPERIMENT_TRACKING_PATH,
        index=False
    )


# ------------------------------------------------------------
# FINAL VALIDATION
# ------------------------------------------------------------

assert EXPERIMENT_TRACKING_PATH.exists(), (
    "Experiment tracking file was not created."
)

EXPERIMENT_TRACKING_DF = pd.read_csv(
    EXPERIMENT_TRACKING_PATH
)

assert (
    list(EXPERIMENT_TRACKING_DF.columns)
    == EXPERIMENT_TRACKING_COLUMNS
), (
    "Experiment tracking schema migration failed."
)


# ------------------------------------------------------------
# FINAL OUTPUT
# ------------------------------------------------------------

print("=" * 100)
print("EXPERIMENT TRACKING TEMPLATE")
print("=" * 100)

print(
    f"Tracking path : {EXPERIMENT_TRACKING_PATH}"
)

print(
    f"Columns       : "
    f"{len(EXPERIMENT_TRACKING_COLUMNS)}"
)

print(
    f"Existing rows : "
    f"{len(EXPERIMENT_TRACKING_DF)}"
)

print("File validation   : PASSED")
print("Schema validation : PASSED")

print("=" * 100)

Existing experiment tracking schema differs from the current research schema.
Existing columns : ['experiment_id', 'dataset', 'missingness_mechanism', 'missingness_rate', 'repetition', 'candidate_method', 'selected_method', 'status', 'seed', 'timestamp']
Required columns : ['experiment_id', 'dataset_id', 'scenario_id', 'mechanism', 'missingness_rate', 'repetition', 'feature', 'feature_type', 'candidate_strategy', 'llm_recommendation', 'final_strategy', 'llm_confidence', 'fallback_used', 'status', 'timestamp']
Existing tracking file migrated to the canonical schema.
====================================================================================================
EXPERIMENT TRACKING TEMPLATE
====================================================================================================
Tracking path : /content/drive/MyDrive/AIR_LLM_Research/logs/experiment_tracking.csv
Columns       : 15
Existing rows : 0
File validation   : PASSED
Schema validation : PASSED
====================================================================================================

In [56]:
# ============================================================
# CELL 00.15.9 — RESULTS INDEX TEMPLATE
# ============================================================

RESULT_COLUMNS = [

    "result_id",
    "dataset_id",
    "scenario_id",
    "repetition",
    "feature",
    "feature_type",
    "method",
    "metric",
    "value",
    "timestamp"
]

RESULT_INDEX_PATH = (
    Path(DIRECTORIES["results_processed"])
    / "results_index.csv"
)


# ------------------------------------------------------------
# CREATE OR MIGRATE RESULTS INDEX
# ------------------------------------------------------------

if RESULT_INDEX_PATH.exists():

    RESULTS_INDEX_DF = pd.read_csv(
        RESULT_INDEX_PATH
    )

    EXISTING_RESULT_COLUMNS = list(
        RESULTS_INDEX_DF.columns
    )

    # --------------------------------------------------------
    # Existing schema is already correct
    # --------------------------------------------------------

    if (
        EXISTING_RESULT_COLUMNS
        == RESULT_COLUMNS
    ):

        pass

    # --------------------------------------------------------
    # Existing schema is older/different
    # --------------------------------------------------------

    else:

        print(
            "Existing results index schema differs "
            "from the current research schema."
        )

        print(
            f"Existing columns : "
            f"{EXISTING_RESULT_COLUMNS}"
        )

        print(
            f"Required columns : "
            f"{RESULT_COLUMNS}"
        )

        # Preserve all existing records.
        # Add missing canonical columns.

        for column in RESULT_COLUMNS:

            if column not in RESULTS_INDEX_DF.columns:

                RESULTS_INDEX_DF[column] = pd.NA

        # Keep only the canonical research schema
        # in the canonical order.

        RESULTS_INDEX_DF = (
            RESULTS_INDEX_DF[
                RESULT_COLUMNS
            ]
        )

        RESULTS_INDEX_DF.to_csv(
            RESULT_INDEX_PATH,
            index=False
        )

        print(
            "Existing results index migrated "
            "to the canonical schema."
        )


# ------------------------------------------------------------
# CREATE NEW INDEX IF ABSENT
# ------------------------------------------------------------

else:

    RESULTS_INDEX_DF = pd.DataFrame(
        columns=RESULT_COLUMNS
    )

    RESULTS_INDEX_DF.to_csv(
        RESULT_INDEX_PATH,
        index=False
    )


# ------------------------------------------------------------
# FINAL VALIDATION
# ------------------------------------------------------------

assert RESULT_INDEX_PATH.exists(), (
    "Results index was not created."
)

RESULTS_INDEX_DF = pd.read_csv(
    RESULT_INDEX_PATH
)

assert (
    list(RESULTS_INDEX_DF.columns)
    == RESULT_COLUMNS
), (
    "Results index schema validation failed."
)


# ------------------------------------------------------------
# FINAL OUTPUT
# ------------------------------------------------------------

print("=" * 100)
print("RESULTS INDEX")
print("=" * 100)

print(
    f"Results index : {RESULT_INDEX_PATH}"
)

print(
    f"Columns       : {len(RESULT_COLUMNS)}"
)

print(
    f"Existing rows : {len(RESULTS_INDEX_DF)}"
)

print("File validation   : PASSED")
print("Schema validation : PASSED")

print("=" * 100)

Existing results index schema differs from the current research schema.
Existing columns : ['result_id', 'dataset', 'missingness_mechanism', 'missingness_rate', 'repetition', 'method', 'metric', 'value', 'timestamp']
Required columns : ['result_id', 'dataset_id', 'scenario_id', 'repetition', 'feature', 'feature_type', 'method', 'metric', 'value', 'timestamp']
Existing results index migrated to the canonical schema.
====================================================================================================
RESULTS INDEX
====================================================================================================
Results index : /content/drive/MyDrive/AIR_LLM_Research/results/processed/results_index.csv
Columns       : 10
Existing rows : 0
File validation   : PASSED
Schema validation : PASSED
====================================================================================================

In [57]:
# ============================================================
# CELL 00.15.10 — PUBLICATION TABLE INDEX
# ============================================================

PUBLICATION_TABLE_COLUMNS = [

    "table_id",
    "table_name",
    "source_notebook",
    "description",
    "file_path",
    "status"
]

PUBLICATION_TABLE_INDEX_PATH = (
    Path(DIRECTORIES["tables"])
    / "publication_table_index.csv"
)


# ------------------------------------------------------------
# CREATE OR MIGRATE PUBLICATION TABLE INDEX
# ------------------------------------------------------------

if PUBLICATION_TABLE_INDEX_PATH.exists():

    PUBLICATION_TABLE_INDEX_DF = pd.read_csv(
        PUBLICATION_TABLE_INDEX_PATH
    )

    EXISTING_PUBLICATION_COLUMNS = list(
        PUBLICATION_TABLE_INDEX_DF.columns
    )

    # --------------------------------------------------------
    # Existing schema is already correct
    # --------------------------------------------------------

    if (
        EXISTING_PUBLICATION_COLUMNS
        == PUBLICATION_TABLE_COLUMNS
    ):

        pass

    # --------------------------------------------------------
    # Existing schema is older/different
    # --------------------------------------------------------

    else:

        print(
            "Existing publication table index schema "
            "differs from the current schema."
        )

        print(
            f"Existing columns : "
            f"{EXISTING_PUBLICATION_COLUMNS}"
        )

        print(
            f"Required columns : "
            f"{PUBLICATION_TABLE_COLUMNS}"
        )

        # Preserve existing records.
        # Add missing canonical columns.

        for column in PUBLICATION_TABLE_COLUMNS:

            if column not in (
                PUBLICATION_TABLE_INDEX_DF.columns
            ):

                PUBLICATION_TABLE_INDEX_DF[column] = pd.NA

        PUBLICATION_TABLE_INDEX_DF = (
            PUBLICATION_TABLE_INDEX_DF[
                PUBLICATION_TABLE_COLUMNS
            ]
        )

        PUBLICATION_TABLE_INDEX_DF.to_csv(
            PUBLICATION_TABLE_INDEX_PATH,
            index=False
        )

        print(
            "Existing publication table index "
            "migrated successfully."
        )


# ------------------------------------------------------------
# CREATE NEW INDEX IF ABSENT
# ------------------------------------------------------------

else:

    PUBLICATION_TABLE_INDEX_DF = pd.DataFrame(
        columns=PUBLICATION_TABLE_COLUMNS
    )

    PUBLICATION_TABLE_INDEX_DF.to_csv(
        PUBLICATION_TABLE_INDEX_PATH,
        index=False
    )


# ------------------------------------------------------------
# FINAL VALIDATION
# ------------------------------------------------------------

assert (
    PUBLICATION_TABLE_INDEX_PATH.exists()
), (
    "Publication table index was not created."
)

PUBLICATION_TABLE_INDEX_DF = pd.read_csv(
    PUBLICATION_TABLE_INDEX_PATH
)

assert (
    list(
        PUBLICATION_TABLE_INDEX_DF.columns
    )
    == PUBLICATION_TABLE_COLUMNS
), (
    "Publication table index schema validation failed."
)


# ------------------------------------------------------------
# FINAL OUTPUT
# ------------------------------------------------------------

print("=" * 100)
print("PUBLICATION TABLE INDEX")
print("=" * 100)

print(
    f"Index path    : "
    f"{PUBLICATION_TABLE_INDEX_PATH}"
)

print(
    f"Columns       : "
    f"{len(PUBLICATION_TABLE_COLUMNS)}"
)

print(
    f"Existing rows : "
    f"{len(PUBLICATION_TABLE_INDEX_DF)}"
)

print("File validation   : PASSED")
print("Schema validation : PASSED")

print("=" * 100)

====================================================================================================
PUBLICATION TABLE INDEX
====================================================================================================
Index path    : /content/drive/MyDrive/AIR_LLM_Research/results/tables/publication_table_index.csv
Columns       : 6
Existing rows : 0
File validation   : PASSED
Schema validation : PASSED
====================================================================================================

In [59]:
# ============================================================
# CELL 00.15.11 — RESEARCH MANIFEST
# ============================================================

SCENARIO_COUNT = len(
    EXPERIMENT_SCENARIO_REGISTRY
)

SCENARIOS_PER_DATASET = (
    len(MISSINGNESS_CONFIG["mechanisms"])
    * len(MISSINGNESS_CONFIG["rates"])
)

REPETITIONS_PER_SCENARIO = (
    MISSINGNESS_CONFIG["repetitions"]
)

TOTAL_SCENARIO_RUNS = (
    len(DATASETS)
    * SCENARIOS_PER_DATASET
)

TOTAL_EXPERIMENT_RUNS = (
    TOTAL_SCENARIO_RUNS
    * REPETITIONS_PER_SCENARIO
)


# ------------------------------------------------------------
# RESEARCH MANIFEST
# ------------------------------------------------------------

RESEARCH_MANIFEST = {

    "project_name":
        PROJECT_NAME,

    "project_code":
        PROJECT_CODE,

    "project_version":
        PROJECT_VERSION,

    "experiment_version":
        EXPERIMENT_VERSION,

    "configuration_version":
        CONFIGURATION_VERSION,

    "created_at":
        datetime.now(timezone.utc).isoformat(),

    "random_seed":
        SEED,

    "datasets":
        DATASETS,

    "n_datasets":
        len(DATASETS),

    "missingness_mechanisms":
        MISSINGNESS_CONFIG["mechanisms"],

    "n_mechanisms":
        len(
            MISSINGNESS_CONFIG["mechanisms"]
        ),

    "missingness_rates":
        MISSINGNESS_CONFIG["rates"],

    "n_rates":
        len(
            MISSINGNESS_CONFIG["rates"]
        ),

    "repetitions":
        REPETITIONS_PER_SCENARIO,

    "candidate_strategies":
        CANDIDATE_STRATEGIES,

    "n_candidate_strategies":
        len(CANDIDATE_STRATEGIES),

    "evaluation_metrics":
        EVALUATION_METRICS,

    "utility_weights":
        UTILITY_WEIGHTS,

    "confidence_thresholds":
        CONFIDENCE_THRESHOLDS,

    "scenario_count":
        SCENARIO_COUNT,

    "scenarios_per_dataset":
        SCENARIOS_PER_DATASET,

    "total_scenario_runs":
        TOTAL_SCENARIO_RUNS,

    "total_experiment_runs":
        TOTAL_EXPERIMENT_RUNS
}


# ------------------------------------------------------------
# MANIFEST PATH
# ------------------------------------------------------------

RESEARCH_MANIFEST_PATH = (
    Path(DIRECTORIES["artifacts"])
    / "research_manifest.json"
)


# ------------------------------------------------------------
# JSON-SAFE CONVERSION
# ------------------------------------------------------------

RESEARCH_MANIFEST_SERIALIZABLE = _yaml_safe(
    RESEARCH_MANIFEST
)


# ------------------------------------------------------------
# SAVE
# ------------------------------------------------------------

with open(
    RESEARCH_MANIFEST_PATH,
    "w",
    encoding="utf-8"
) as file:

    json.dump(
        RESEARCH_MANIFEST_SERIALIZABLE,
        file,
        indent=4,
        ensure_ascii=False
    )


# ------------------------------------------------------------
# VERIFY FILE
# ------------------------------------------------------------

assert RESEARCH_MANIFEST_PATH.exists(), (
    "Research manifest was not saved."
)

assert RESEARCH_MANIFEST_PATH.stat().st_size > 0, (
    "Research manifest is empty."
)


# ------------------------------------------------------------
# RELOAD
# ------------------------------------------------------------

with open(
    RESEARCH_MANIFEST_PATH,
    "r",
    encoding="utf-8"
) as file:

    RESEARCH_MANIFEST_LOADED = json.load(file)


# ------------------------------------------------------------
# VALIDATE MANIFEST
# ------------------------------------------------------------

assert isinstance(
    RESEARCH_MANIFEST_LOADED,
    dict
)

assert (
    RESEARCH_MANIFEST_LOADED["project_name"]
    == PROJECT_NAME
)

assert (
    RESEARCH_MANIFEST_LOADED["project_code"]
    == PROJECT_CODE
)

assert (
    RESEARCH_MANIFEST_LOADED["random_seed"]
    == SEED
)

assert (
    RESEARCH_MANIFEST_LOADED["datasets"]
    == DATASETS
)

assert (
    RESEARCH_MANIFEST_LOADED[
        "missingness_mechanisms"
    ]
    == MISSINGNESS_CONFIG[
        "mechanisms"
    ]
)

assert (
    RESEARCH_MANIFEST_LOADED[
        "missingness_rates"
    ]
    == MISSINGNESS_CONFIG[
        "rates"
    ]
)

assert (
    RESEARCH_MANIFEST_LOADED[
        "repetitions"
    ]
    == REPETITIONS_PER_SCENARIO
)

assert (
    RESEARCH_MANIFEST_LOADED[
        "candidate_strategies"
    ]
    == CANDIDATE_STRATEGIES
)

assert (
    RESEARCH_MANIFEST_LOADED[
        "scenario_count"
    ]
    == SCENARIO_COUNT
)

assert (
    RESEARCH_MANIFEST_LOADED[
        "scenarios_per_dataset"
    ]
    == SCENARIOS_PER_DATASET
)

assert (
    RESEARCH_MANIFEST_LOADED[
        "total_scenario_runs"
    ]
    == TOTAL_SCENARIO_RUNS
)

assert (
    RESEARCH_MANIFEST_LOADED[
        "total_experiment_runs"
    ]
    == TOTAL_EXPERIMENT_RUNS
)


# ------------------------------------------------------------
# FINAL OUTPUT
# ------------------------------------------------------------

print("=" * 100)
print("AIR-LLM RESEARCH MANIFEST")
print("=" * 100)

print(
    f"Manifest path          : "
    f"{RESEARCH_MANIFEST_PATH}"
)

print(
    f"Datasets               : "
    f"{len(DATASETS)}"
)

print(
    f"Scenarios per dataset  : "
    f"{SCENARIOS_PER_DATASET}"
)

print(
    f"Total scenario runs    : "
    f"{TOTAL_SCENARIO_RUNS}"
)

print(
    f"Repetitions            : "
    f"{REPETITIONS_PER_SCENARIO}"
)

print(
    f"Total experiment runs  : "
    f"{TOTAL_EXPERIMENT_RUNS}"
)

print()
print("Save validation        : PASSED")
print("Reload validation      : PASSED")
print("Content validation     : PASSED")

print("=" * 100)

====================================================================================================
AIR-LLM RESEARCH MANIFEST
====================================================================================================
Manifest path          : /content/drive/MyDrive/AIR_LLM_Research/artifacts/research_manifest.json
Datasets               : 3
Scenarios per dataset  : 15
Total scenario runs    : 45
Repetitions            : 5
Total experiment runs  : 225

Save validation        : PASSED
Reload validation      : PASSED
Content validation     : PASSED
====================================================================================================

In [60]:
# ============================================================
# CELL 00.16.1 — CONFIGURATION VALIDATION
# ============================================================

VALIDATION_RESULTS = {}


# ------------------------------------------------------------
# PROJECT
# ------------------------------------------------------------

VALIDATION_RESULTS[
    "project_root_defined"
] = (
    PROJECT_ROOT is not None
    and Path(PROJECT_ROOT).exists()
)


# ------------------------------------------------------------
# DATASETS
# ------------------------------------------------------------

VALIDATION_RESULTS[
    "three_datasets_configured"
] = (
    len(DATASETS) == 3
)

VALIDATION_RESULTS[
    "dataset_targets_defined"
] = all(
    "target" in metadata
    and metadata["target"]
    for metadata in DATASET_REGISTRY.values()
)

VALIDATION_RESULTS[
    "dataset_registry_complete"
] = (
    set(DATASET_REGISTRY.keys())
    == set(DATASETS)
)


# ------------------------------------------------------------
# FEATURE / TARGET
# ------------------------------------------------------------

VALIDATION_RESULTS[
    "feature_target_registry_complete"
] = (
    set(FEATURE_TARGET_REGISTRY.keys())
    == set(DATASETS)
)

VALIDATION_RESULTS[
    "target_consistency"
] = all(
    FEATURE_TARGET_REGISTRY[dataset_id]["target"]
    == DATASET_REGISTRY[dataset_id]["target"]
    for dataset_id in DATASETS
)


# ------------------------------------------------------------
# MISSINGNESS
# ------------------------------------------------------------

VALIDATION_RESULTS[
    "missingness_mechanisms_valid"
] = set(
    MISSINGNESS_CONFIG["mechanisms"]
).issubset(
    {"MCAR", "MAR", "MNAR"}
)

VALIDATION_RESULTS[
    "missingness_rates_valid"
] = all(
    0 < rate < 1
    for rate in MISSINGNESS_CONFIG["rates"]
)

VALIDATION_RESULTS[
    "missingness_repetitions_valid"
] = (
    MISSINGNESS_CONFIG["repetitions"] >= 1
)


# ------------------------------------------------------------
# CANDIDATE STRATEGIES
# ------------------------------------------------------------

VALIDATION_RESULTS[
    "candidate_strategies_defined"
] = (
    len(CANDIDATE_STRATEGIES) > 0
)

VALIDATION_RESULTS[
    "candidate_registry_consistent"
] = (
    set(CANDIDATE_STRATEGIES)
    == set(CANDIDATE_STRATEGY_REGISTRY.keys())
)


# ------------------------------------------------------------
# STRATEGY SELECTION
# ------------------------------------------------------------

VALIDATION_RESULTS[
    "feature_level_selection_enabled"
] = (
    STRATEGY_SELECTION_POLICY[
        "selection_granularity"
    ]
    == "feature_level"
)

VALIDATION_RESULTS[
    "empirical_validation_enabled"
] = (
    STRATEGY_SELECTION_POLICY[
        "empirical_validation"
    ]
    is True
)


# ------------------------------------------------------------
# UTILITY
# ------------------------------------------------------------

VALIDATION_RESULTS[
    "utility_weights_sum_to_one"
] = np.isclose(
    sum(UTILITY_WEIGHTS.values()),
    1.0
)


# ------------------------------------------------------------
# CONFIDENCE
# ------------------------------------------------------------

VALIDATION_RESULTS[
    "confidence_thresholds_valid"
] = (
    0
    <= CONFIDENCE_THRESHOLDS["low"]
    <= CONFIDENCE_THRESHOLDS["medium"]
    <= CONFIDENCE_THRESHOLDS["high"]
    <= 1
)

VALIDATION_RESULTS[
    "minimum_confidence_valid"
] = (
    0
    <= CONFIDENCE_THRESHOLDS[
        "minimum_selection_confidence"
    ]
    <= 1
)


# ------------------------------------------------------------
# SCENARIO REGISTRY
# ------------------------------------------------------------

EXPECTED_SCENARIO_COUNT_CALCULATED = (
    len(MISSINGNESS_CONFIG["mechanisms"])
    * len(MISSINGNESS_CONFIG["rates"])
)

VALIDATION_RESULTS[
    "scenario_registry_complete"
] = (
    len(EXPERIMENT_SCENARIO_REGISTRY)
    == EXPECTED_SCENARIO_COUNT_CALCULATED
)


# ------------------------------------------------------------
# SCENARIO CONTENT
# ------------------------------------------------------------

VALIDATION_RESULTS[
    "scenario_mechanisms_valid"
] = all(
    scenario["mechanism"]
    in MISSINGNESS_CONFIG["mechanisms"]
    for scenario
    in EXPERIMENT_SCENARIO_REGISTRY.values()
)

VALIDATION_RESULTS[
    "scenario_rates_valid"
] = all(
    scenario["missingness_rate"]
    in MISSINGNESS_CONFIG["rates"]
    for scenario
    in EXPERIMENT_SCENARIO_REGISTRY.values()
)

VALIDATION_RESULTS[
    "scenario_repetitions_valid"
] = all(
    scenario["repetitions"]
    == MISSINGNESS_CONFIG["repetitions"]
    for scenario
    in EXPERIMENT_SCENARIO_REGISTRY.values()
)


# ------------------------------------------------------------
# EXPERIMENT DESIGN
# ------------------------------------------------------------

EXPECTED_TOTAL_RUNS = (
    len(DATASETS)
    * EXPECTED_SCENARIO_COUNT_CALCULATED
    * MISSINGNESS_CONFIG["repetitions"]
)

VALIDATION_RESULTS[
    "experiment_run_count_valid"
] = (
    TOTAL_EXPERIMENT_RUNS
    == EXPECTED_TOTAL_RUNS
)


# ------------------------------------------------------------
# DIRECTORIES
# ------------------------------------------------------------

VALIDATION_RESULTS[
    "all_directories_exist"
] = all(
    path.exists()
    and path.is_dir()
    for path in DIRECTORIES.values()
)


# ------------------------------------------------------------
# CONFIGURATION FILES
# ------------------------------------------------------------

VALIDATION_RESULTS[
    "master_config_exists"
] = CONFIG_PATH.exists()

VALIDATION_RESULTS[
    "dataset_registry_file_exists"
] = DATASET_REGISTRY_PATH.exists()

VALIDATION_RESULTS[
    "feature_target_registry_file_exists"
] = FEATURE_TARGET_REGISTRY_PATH.exists()

VALIDATION_RESULTS[
    "scenario_registry_file_exists"
] = SCENARIO_REGISTRY_PATH.exists()

VALIDATION_RESULTS[
    "experiment_design_exists"
] = EXPERIMENT_DESIGN_PATH.exists()


# ------------------------------------------------------------
# REPRODUCIBILITY ARTIFACTS
# ------------------------------------------------------------

VALIDATION_RESULTS[
    "configuration_snapshot_exists"
] = CONFIG_SNAPSHOT_PATH.exists()

VALIDATION_RESULTS[
    "research_manifest_exists"
] = RESEARCH_MANIFEST_PATH.exists()


# ------------------------------------------------------------
# TRACKING FILES
# ------------------------------------------------------------

VALIDATION_RESULTS[
    "tracking_template_exists"
] = EXPERIMENT_TRACKING_PATH.exists()

VALIDATION_RESULTS[
    "results_index_exists"
] = RESULT_INDEX_PATH.exists()

VALIDATION_RESULTS[
    "publication_index_exists"
] = PUBLICATION_TABLE_INDEX_PATH.exists()


# ------------------------------------------------------------
# VALIDATION DATAFRAME
# ------------------------------------------------------------

VALIDATION_DF = pd.DataFrame(
    [
        {
            "validation": key,
            "status": (
                "PASS"
                if value
                else "FAIL"
            )
        }
        for key, value
        in VALIDATION_RESULTS.items()
    ]
)

display(VALIDATION_DF)


# ------------------------------------------------------------
# FAILURE REPORT
# ------------------------------------------------------------

FAILED_VALIDATIONS = [
    key
    for key, value
    in VALIDATION_RESULTS.items()
    if not value
]

if FAILED_VALIDATIONS:

    print("=" * 100)
    print("CONFIGURATION VALIDATION FAILED")
    print("=" * 100)

    for item in FAILED_VALIDATIONS:
        print(f"  FAIL : {item}")

    raise AssertionError(
        "Configuration validation failed. "
        "Fix the listed validation(s) before "
        "continuing to Notebook 01."
    )


# ------------------------------------------------------------
# FINAL STATUS
# ------------------------------------------------------------

print("=" * 100)
print("CONFIGURATION VALIDATION: PASSED")
print("=" * 100)

print(
    f"Datasets          : {len(DATASETS)}"
)

print(
    f"Scenarios         : "
    f"{EXPECTED_SCENARIO_COUNT_CALCULATED}"
)

print(
    f"Repetitions       : "
    f"{MISSINGNESS_CONFIG['repetitions']}"
)

print(
    f"Total experiment runs : "
    f"{EXPECTED_TOTAL_RUNS}"
)

print(
    f"Validation checks : "
    f"{len(VALIDATION_RESULTS)}"
)

print("=" * 100)

                             validation status
0                  project_root_defined   PASS
1             three_datasets_configured   PASS
2               dataset_targets_defined   PASS
3             dataset_registry_complete   PASS
4      feature_target_registry_complete   PASS
5                    target_consistency   PASS
6          missingness_mechanisms_valid   PASS
7               missingness_rates_valid   PASS
8         missingness_repetitions_valid   PASS
9          candidate_strategies_defined   PASS
10        candidate_registry_consistent   PASS
11      feature_level_selection_enabled   PASS
12         empirical_validation_enabled   PASS
13           utility_weights_sum_to_one   PASS
14          confidence_thresholds_valid   PASS
15             minimum_confidence_valid   PASS
16           scenario_registry_complete   PASS
17            scenario_mechanisms_valid   PASS
18                 scenario_rates_valid   PASS
19           scenario_repetitions_valid   PASS
20           experiment_run_count_valid   PASS
21                all_directories_exist   PASS
22                 master_config_exists   PASS
23         dataset_registry_file_exists   PASS
24  feature_target_registry_file_exists   PASS
25        scenario_registry_file_exists   PASS
26             experiment_design_exists   PASS
27        configuration_snapshot_exists   PASS
28             research_manifest_exists   PASS
29             tracking_template_exists   PASS
30                 results_index_exists   PASS
31             publication_index_exists   PASS

====================================================================================================
CONFIGURATION VALIDATION: PASSED
====================================================================================================
Datasets          : 3
Scenarios         : 15
Repetitions       : 5
Total experiment runs : 225
Validation checks : 32
====================================================================================================

In [61]:
# ============================================================
# CELL 00.16.2 — REPRODUCIBILITY VALIDATION
# ============================================================

REPRODUCIBILITY_RESULTS = {

    "global_seed":
        SEED == 42,

    "python_hash_seed":
        os.environ.get("PYTHONHASHSEED")
        == str(SEED),

    "numpy_available":
        np.__version__ is not None,

    "pandas_available":
        pd.__version__ is not None,

    "scipy_available":
        scipy.__version__ is not None,

    "sklearn_available":
        SKLEARN_VERSION is not None,

    "yaml_available":
        yaml.__version__ is not None,

    "configuration_version_defined":
        CONFIGURATION_VERSION == "CONFIG-v1",

    "deterministic_configuration":
        PYTORCH_REPRODUCIBILITY[
            "deterministic"
        ] is True,

    "configuration_snapshot_saved":
        CONFIG_SNAPSHOT_PATH.exists()
        and CONFIG_SNAPSHOT_PATH.stat().st_size > 0,

    "research_manifest_saved":
        RESEARCH_MANIFEST_PATH.exists()
        and RESEARCH_MANIFEST_PATH.stat().st_size > 0,

    "master_configuration_saved":
        CONFIG_PATH.exists()
        and CONFIG_PATH.stat().st_size > 0,

    "dataset_registry_saved":
        DATASET_REGISTRY_PATH.exists()
        and DATASET_REGISTRY_PATH.stat().st_size > 0,

    "feature_target_registry_saved":
        FEATURE_TARGET_REGISTRY_PATH.exists()
        and FEATURE_TARGET_REGISTRY_PATH.stat().st_size > 0,

    "scenario_registry_saved":
        SCENARIO_REGISTRY_PATH.exists()
        and SCENARIO_REGISTRY_PATH.stat().st_size > 0,

    "experiment_design_saved":
        EXPERIMENT_DESIGN_PATH.exists()
        and EXPERIMENT_DESIGN_PATH.stat().st_size > 0
}


REPRODUCIBILITY_DF = pd.DataFrame(
    [
        {
            "check": key,
            "status": (
                "PASS"
                if value
                else "FAIL"
            )
        }
        for key, value
        in REPRODUCIBILITY_RESULTS.items()
    ]
)


display(REPRODUCIBILITY_DF)


# ------------------------------------------------------------
# FAILURE REPORT
# ------------------------------------------------------------

FAILED_REPRODUCIBILITY = [
    key
    for key, value
    in REPRODUCIBILITY_RESULTS.items()
    if not value
]

if FAILED_REPRODUCIBILITY:

    print("=" * 100)
    print("REPRODUCIBILITY VALIDATION FAILED")
    print("=" * 100)

    for item in FAILED_REPRODUCIBILITY:
        print(f"  FAIL : {item}")

    raise AssertionError(
        "Reproducibility validation failed."
    )


print("=" * 100)
print("REPRODUCIBILITY VALIDATION: PASSED")
print("=" * 100)

print(
    f"Seed                  : {SEED}"
)

print(
    f"Configuration         : {CONFIG_PATH}"
)

print(
    f"Research manifest     : {RESEARCH_MANIFEST_PATH}"
)

print(
    f"Configuration snapshot: {CONFIG_SNAPSHOT_PATH}"
)

print("=" * 100)

                            check status
0                     global_seed   PASS
1                python_hash_seed   PASS
2                 numpy_available   PASS
3                pandas_available   PASS
4                 scipy_available   PASS
5               sklearn_available   PASS
6                  yaml_available   PASS
7   configuration_version_defined   PASS
8     deterministic_configuration   PASS
9    configuration_snapshot_saved   PASS
10        research_manifest_saved   PASS
11     master_configuration_saved   PASS
12         dataset_registry_saved   PASS
13  feature_target_registry_saved   PASS
14        scenario_registry_saved   PASS
15        experiment_design_saved   PASS

====================================================================================================
REPRODUCIBILITY VALIDATION: PASSED
====================================================================================================
Seed                  : 42
Configuration         : /content/drive/MyDrive/AIR_LLM_Research/config/config.yaml
Research manifest     : /content/drive/MyDrive/AIR_LLM_Research/artifacts/research_manifest.json
Configuration snapshot: /content/drive/MyDrive/AIR_LLM_Research/artifacts/configuration_snapshot.json
====================================================================================================

In [62]:
# ============================================================
# CELL 00.16.3 — FINAL CONFIGURATION LOCK
# ============================================================

CONFIGURATION_LOCK = {

    "status":
        "LOCKED",

    "project":
        PROJECT_NAME,

    "project_code":
        PROJECT_CODE,

    "project_version":
        PROJECT_VERSION,

    "experiment_version":
        EXPERIMENT_VERSION,

    "configuration_version":
        CONFIGURATION_VERSION,

    "locked_at":
        datetime.now(timezone.utc).isoformat(),

    "random_seed":
        SEED,

    "datasets":
        DATASETS,

    "scenario_count":
        len(EXPERIMENT_SCENARIO_REGISTRY),

    "candidate_strategy_count":
        len(CANDIDATE_STRATEGIES),

    "configuration_file":
        str(CONFIG_PATH),

    "research_manifest":
        str(RESEARCH_MANIFEST_PATH)
}


# ------------------------------------------------------------
# LOCK PATH
# ------------------------------------------------------------

CONFIGURATION_LOCK_PATH = (
    Path(DIRECTORIES["artifacts"])
    / "configuration_lock.json"
)


# ------------------------------------------------------------
# SAVE CONFIGURATION LOCK
# ------------------------------------------------------------

with open(
    CONFIGURATION_LOCK_PATH,
    "w",
    encoding="utf-8"
) as file:

    json.dump(
        CONFIGURATION_LOCK,
        file,
        indent=4,
        ensure_ascii=False,
        default=str
    )


# ------------------------------------------------------------
# VERIFY LOCK FILE
# ------------------------------------------------------------

assert CONFIGURATION_LOCK_PATH.exists(), (
    "Configuration lock was not saved."
)

assert CONFIGURATION_LOCK_PATH.stat().st_size > 0, (
    "Configuration lock file is empty."
)


# ------------------------------------------------------------
# RELOAD LOCK
# ------------------------------------------------------------

with open(
    CONFIGURATION_LOCK_PATH,
    "r",
    encoding="utf-8"
) as file:

    CONFIGURATION_LOCK_LOADED = json.load(file)


# ------------------------------------------------------------
# VALIDATE LOCK
# ------------------------------------------------------------

assert (
    CONFIGURATION_LOCK_LOADED["status"]
    == "LOCKED"
)

assert (
    CONFIGURATION_LOCK_LOADED["project_code"]
    == PROJECT_CODE
)

assert (
    CONFIGURATION_LOCK_LOADED["configuration_version"]
    == CONFIGURATION_VERSION
)

assert (
    CONFIGURATION_LOCK_LOADED["random_seed"]
    == SEED
)

assert (
    CONFIGURATION_LOCK_LOADED["datasets"]
    == DATASETS
)

assert (
    CONFIGURATION_LOCK_LOADED["scenario_count"]
    == len(EXPERIMENT_SCENARIO_REGISTRY)
)

assert (
    CONFIGURATION_LOCK_LOADED[
        "candidate_strategy_count"
    ]
    == len(CANDIDATE_STRATEGIES)
)


# ------------------------------------------------------------
# FINAL OUTPUT
# ------------------------------------------------------------

print("=" * 100)
print("AIR-LLM CONFIGURATION LOCK")
print("=" * 100)

print(
    f"Status       : "
    f"{CONFIGURATION_LOCK_LOADED['status']}"
)

print(
    f"Version      : "
    f"{CONFIGURATION_LOCK_LOADED['configuration_version']}"
)

print(
    f"Seed         : "
    f"{CONFIGURATION_LOCK_LOADED['random_seed']}"
)

print(
    f"Datasets     : "
    f"{len(CONFIGURATION_LOCK_LOADED['datasets'])}"
)

print(
    f"Scenarios    : "
    f"{CONFIGURATION_LOCK_LOADED['scenario_count']}"
)

print(
    f"Strategies   : "
    f"{CONFIGURATION_LOCK_LOADED['candidate_strategy_count']}"
)

print(
    f"Lock File    : "
    f"{CONFIGURATION_LOCK_PATH}"
)

print()
print("Lock save validation    : PASSED")
print("Lock reload validation  : PASSED")
print("Lock content validation: PASSED")

print("=" * 100)
print("CONFIGURATION SUCCESSFULLY LOCKED")
print("=" * 100)

====================================================================================================
AIR-LLM CONFIGURATION LOCK
====================================================================================================
Status       : LOCKED
Version      : CONFIG-v1
Seed         : 42
Datasets     : 3
Scenarios    : 15
Strategies   : 7
Lock File    : /content/drive/MyDrive/AIR_LLM_Research/artifacts/configuration_lock.json

Lock save validation    : PASSED
Lock reload validation  : PASSED
Lock content validation: PASSED
====================================================================================================
CONFIGURATION SUCCESSFULLY LOCKED
====================================================================================================

In [63]:
# ============================================================
# CELL 00.16.4 — FINAL NOTEBOOK STATUS
# ============================================================

print("\n")
print("=" * 100)
print("AIR-LLM — NOTEBOOK 00 COMPLETE")
print("=" * 100)


# ------------------------------------------------------------
# PROJECT
# ------------------------------------------------------------

print("\nPROJECT")
print("-" * 100)

print(f"Project              : {PROJECT_NAME}")
print(f"Project Code         : {PROJECT_CODE}")
print(f"Project Version      : {PROJECT_VERSION}")
print(f"Experiment Version   : {EXPERIMENT_VERSION}")
print(f"Configuration        : {CONFIGURATION_VERSION}")
print(f"Project Root         : {PROJECT_ROOT}")


# ------------------------------------------------------------
# DATASETS
# ------------------------------------------------------------

print("\nDATASETS")
print("-" * 100)

for dataset_id in DATASETS:

    metadata = DATASET_REGISTRY[dataset_id]

    print(
        f"{dataset_id:20s} | "
        f"{metadata['dataset_name']:30s} | "
        f"Target: {metadata['target']}"
    )


# ------------------------------------------------------------
# EXPERIMENT DESIGN
# ------------------------------------------------------------

print("\nEXPERIMENT DESIGN")
print("-" * 100)

print(
    f"Missingness mechanisms : "
    f"{MISSINGNESS_CONFIG['mechanisms']}"
)

print(
    f"Missingness rates      : "
    f"{MISSINGNESS_CONFIG['rates']}"
)

print(
    f"Repetitions            : "
    f"{MISSINGNESS_CONFIG['repetitions']}"
)

print(
    f"Scenarios per dataset  : "
    f"{SCENARIOS_PER_DATASET}"
)

print(
    f"Total scenario runs    : "
    f"{TOTAL_SCENARIO_RUNS}"
)

print(
    f"Total experiment runs  : "
    f"{TOTAL_EXPERIMENT_RUNS}"
)


# ------------------------------------------------------------
# STRATEGY SELECTION
# ------------------------------------------------------------

print("\nSTRATEGY SELECTION")
print("-" * 100)

print(
    f"Candidate strategies   : "
    f"{len(CANDIDATE_STRATEGIES)}"
)

print(
    f"Feature-level selection: "
    f"{STRATEGY_SELECTION_POLICY['selection_granularity']}"
)

print(
    f"LLM enabled            : "
    f"{LLM_CONFIG['enabled']}"
)

print(
    f"Minimum confidence     : "
    f"{CONFIDENCE_THRESHOLDS['minimum_selection_confidence']}"
)


# ------------------------------------------------------------
# REPRODUCIBILITY
# ------------------------------------------------------------

print("\nREPRODUCIBILITY")
print("-" * 100)

print(f"Seed                   : {SEED}")
print(f"Device                 : {DEVICE}")
print(f"GPU                    : {GPU_NAME}")

print(
    f"Configuration locked   : "
    f"{CONFIGURATION_LOCK_LOADED['status']}"
)


# ------------------------------------------------------------
# CONFIGURATION FILES
# ------------------------------------------------------------

print("\nCONFIGURATION FILES")
print("-" * 100)

print(
    f"Master Config           : "
    f"{CONFIG_PATH}"
)

print(
    f"Dataset Registry        : "
    f"{DATASET_REGISTRY_PATH}"
)

print(
    f"Feature/Target Registry : "
    f"{FEATURE_TARGET_REGISTRY_PATH}"
)

print(
    f"Scenario Registry       : "
    f"{SCENARIO_REGISTRY_PATH}"
)

print(
    f"Experiment Design       : "
    f"{EXPERIMENT_DESIGN_PATH}"
)

print(
    f"Research Manifest       : "
    f"{RESEARCH_MANIFEST_PATH}"
)

print(
    f"Configuration Lock      : "
    f"{CONFIGURATION_LOCK_PATH}"
)


# ------------------------------------------------------------
# FINAL FILE VALIDATION
# ------------------------------------------------------------

FINAL_ARTIFACTS = {

    "master_config":
        CONFIG_PATH,

    "dataset_registry":
        DATASET_REGISTRY_PATH,

    "feature_target_registry":
        FEATURE_TARGET_REGISTRY_PATH,

    "scenario_registry":
        SCENARIO_REGISTRY_PATH,

    "experiment_design":
        EXPERIMENT_DESIGN_PATH,

    "research_manifest":
        RESEARCH_MANIFEST_PATH,

    "configuration_lock":
        CONFIGURATION_LOCK_PATH
}

FINAL_ARTIFACT_STATUS = {

    name:
        path.exists()
        and path.stat().st_size > 0

    for name, path
    in FINAL_ARTIFACTS.items()
}

FAILED_ARTIFACTS = [
    name
    for name, status
    in FINAL_ARTIFACT_STATUS.items()
    if not status
]


# ------------------------------------------------------------
# FINAL VALIDATION
# ------------------------------------------------------------

assert not FAILED_ARTIFACTS, (
    "Notebook 00 cannot be marked complete. "
    f"Missing/empty artifacts: {FAILED_ARTIFACTS}"
)

assert all(
    VALIDATION_RESULTS.values()
), (
    "Notebook 00 configuration validation failed."
)

assert all(
    REPRODUCIBILITY_RESULTS.values()
), (
    "Notebook 00 reproducibility validation failed."
)

assert (
    CONFIGURATION_LOCK_LOADED["status"]
    == "LOCKED"
)


# ------------------------------------------------------------
# FINAL STATUS
# ------------------------------------------------------------

print("\n" + "=" * 100)
print("FINAL NOTEBOOK 00 VALIDATION")
print("=" * 100)

print(
    f"Configuration checks : "
    f"{len(VALIDATION_RESULTS)}"
)

print(
    f"Reproducibility checks: "
    f"{len(REPRODUCIBILITY_RESULTS)}"
)

print(
    f"Artifacts validated   : "
    f"{len(FINAL_ARTIFACTS)}"
)

print(
    f"Configuration status  : LOCKED"
)

print(
    f"Experiment runs       : "
    f"{TOTAL_EXPERIMENT_RUNS}"
)

print("=" * 100)
print("ALL NOTEBOOK 00 VALIDATIONS PASSED")
print("AIR-LLM RESEARCH CONFIGURATION IS READY FOR NOTEBOOK 01")
print("=" * 100)

====================================================================================================
AIR-LLM — NOTEBOOK 00 COMPLETE
====================================================================================================

PROJECT
----------------------------------------------------------------------------------------------------
Project              : AIR-LLM Research Project
Project Code         : AIR-LLM
Project Version      : 1.0
Experiment Version   : AIR-LLM-v1
Configuration        : CONFIG-v1
Project Root         : /content/drive/MyDrive/AIR_LLM_Research

DATASETS
----------------------------------------------------------------------------------------------------
adult_income         | Adult Income                   | Target: income
bank_marketing       | Bank Marketing                 | Target: y
diabetes_130us       | Diabetes 130-US Hospitals      | Target: readmitted

EXPERIMENT DESIGN
----------------------------------------------------------------------------------------------------
Missingness mechanisms : ['MCAR', 'MAR', 'MNAR']
Missingness rates      : [0.1, 0.2, 0.3, 0.4, 0.5]
Repetitions            : 5
Scenarios per dataset  : 15
Total scenario runs    : 45
Total experiment runs  : 225

STRATEGY SELECTION
----------------------------------------------------------------------------------------------------
Candidate strategies   : 7
Feature-level selection: feature_level
LLM enabled            : True
Minimum confidence     : 0.6

REPRODUCIBILITY
----------------------------------------------------------------------------------------------------
Seed                   : 42
Device                 : cpu
GPU                    : CPU
Configuration locked   : LOCKED

CONFIGURATION FILES
----------------------------------------------------------------------------------------------------
Master Config           : /content/drive/MyDrive/AIR_LLM_Research/config/config.yaml
Dataset Registry        : /content/drive/MyDrive/AIR_LLM_Research/config/dataset_registry.yaml
Feature/Target Registry : /content/drive/MyDrive/AIR_LLM_Research/config/feature_target_registry.yaml
Scenario Registry       : /content/drive/MyDrive/AIR_LLM_Research/config/experiment_scenario_registry.yaml
Experiment Design       : /content/drive/MyDrive/AIR_LLM_Research/config/experiment_design.yaml
Research Manifest       : /content/drive/MyDrive/AIR_LLM_Research/artifacts/research_manifest.json
Configuration Lock      : /content/drive/MyDrive/AIR_LLM_Research/artifacts/configuration_lock.json

====================================================================================================
FINAL NOTEBOOK 00 VALIDATION
====================================================================================================
Configuration checks : 32
Reproducibility checks: 16
Artifacts validated   : 7
Configuration status  : LOCKED
Experiment runs       : 225
====================================================================================================
ALL NOTEBOOK 00 VALIDATIONS PASSED
AIR-LLM RESEARCH CONFIGURATION IS READY FOR NOTEBOOK 01
====================================================================================================