<a href="https://colab.research.google.com/github/amzad-786githumb/AIR_LLM_Research/blob/main/00_Project_Configuration.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# ============================================================
# CELL 00.1 — AIR-LLM PROJECT CONFIGURATION
# ============================================================

PROJECT_NAME = "AIR-LLM Research Project"
PROJECT_CODE = "AIR-LLM"
PROJECT_VERSION = "1.0"
EXPERIMENT_VERSION = "AIR-LLM-v1"

print("=" * 100)
print("AIR-LLM — PROJECT CONFIGURATION")
print("=" * 100)
print(f"Project          : {PROJECT_NAME}")
print(f"Project Code     : {PROJECT_CODE}")
print(f"Project Version  : {PROJECT_VERSION}")
print(f"Experiment       : {EXPERIMENT_VERSION}")
print("=" * 100)

====================================================================================================
AIR-LLM — PROJECT CONFIGURATION
====================================================================================================
Project          : AIR-LLM Research Project
Project Code     : AIR-LLM
Project Version  : 1.0
Experiment       : AIR-LLM-v1
====================================================================================================

In [2]:
# ============================================================
# CELL 00.1.1 — ENVIRONMENT SETUP
# ============================================================

import os
import sys
import json
import random
import platform
import warnings
import subprocess
from pathlib import Path
from datetime import datetime, timezone

warnings.filterwarnings("ignore")

print("=" * 100)
print("AIR-LLM RESEARCH PROJECT")
print("00 — PROJECT CONFIGURATION")
print("=" * 100)

print(f"Python      : {sys.version.split()[0]}")
print(f"Platform    : {platform.platform()}")
print(f"Execution   : {datetime.now(timezone.utc).isoformat()}")
print("=" * 100)

====================================================================================================
AIR-LLM RESEARCH PROJECT
00 — PROJECT CONFIGURATION
====================================================================================================
Python      : 3.12.13
Platform    : Linux-6.6.122+-x86_64-with-glibc2.35
Execution   : 2026-08-18T11:13:01.842995+00:00
====================================================================================================

In [3]:
# ============================================================
# CELL 00.1.3 — CORE LIBRARY IMPORTS
# ============================================================

import numpy as np
import pandas as pd
import scipy
import sklearn
import yaml

from sklearn import __version__ as SKLEARN_VERSION

print("Core libraries imported successfully.")

Core libraries imported successfully.

In [4]:
# ============================================================
# CELL 00.1.4 — PYTORCH ENVIRONMENT
# ============================================================

try:
    import torch

    TORCH_AVAILABLE = True
    TORCH_VERSION = torch.__version__

except ImportError:

    torch = None
    TORCH_AVAILABLE = False
    TORCH_VERSION = None

print(f"PyTorch available : {TORCH_AVAILABLE}")
print(f"PyTorch version   : {TORCH_VERSION}")

PyTorch available : True
PyTorch version   : 2.11.0+cpu

In [5]:
# ============================================================
# CELL 00.2.1 — PACKAGE VERSION REGISTRY
# ============================================================

PACKAGE_VERSIONS = {

    "python": platform.python_version(),

    "numpy": np.__version__,

    "pandas": pd.__version__,

    "scipy": scipy.__version__,

    "scikit_learn": SKLEARN_VERSION,

    "pyyaml": yaml.__version__,

    "torch": TORCH_VERSION
}

PACKAGE_VERSION_DF = pd.DataFrame(
    [
        {
            "package": package,
            "version": version
        }
        for package, version
        in PACKAGE_VERSIONS.items()
    ]
)

display(PACKAGE_VERSION_DF)

print("Package versions captured successfully.")

        package     version
0        python     3.12.13
1         numpy       2.0.2
2        pandas       2.2.2
3         scipy      1.16.3
4  scikit_learn       1.6.1
5        pyyaml       6.0.3
6         torch  2.11.0+cpu

Package versions captured successfully.

In [6]:
# ============================================================
# CELL 00.2.2 — HARDWARE / RUNTIME INFORMATION
# ============================================================

if TORCH_AVAILABLE:

    DEVICE = (
        "cuda"
        if torch.cuda.is_available()
        else "cpu"
    )

    if torch.cuda.is_available():

        GPU_NAME = torch.cuda.get_device_name(0)
        GPU_COUNT = torch.cuda.device_count()
        CUDA_VERSION = torch.version.cuda

    else:

        GPU_NAME = "CPU"
        GPU_COUNT = 0
        CUDA_VERSION = None

else:

    DEVICE = "cpu"
    GPU_NAME = "CPU"
    GPU_COUNT = 0
    CUDA_VERSION = None


RUNTIME_INFO = {

    "python_version":
        PACKAGE_VERSIONS["python"],

    "platform":
        platform.platform(),

    "processor":
        platform.processor(),

    "device":
        DEVICE,

    "gpu_name":
        GPU_NAME,

    "gpu_count":
        GPU_COUNT,

    "cuda_version":
        CUDA_VERSION
}

print("=" * 100)
print("RUNTIME INFORMATION")
print("=" * 100)

for key, value in RUNTIME_INFO.items():
    print(f"{key:20s}: {value}")

====================================================================================================
RUNTIME INFORMATION
====================================================================================================
python_version      : 3.12.13
platform            : Linux-6.6.122+-x86_64-with-glibc2.35
processor           : x86_64
device              : cpu
gpu_name            : CPU
gpu_count           : 0
cuda_version        : None

In [7]:
# ============================================================
# CELL 00.3.1 — GLOBAL RANDOM SEED
# ============================================================

SEED = 42

os.environ["PYTHONHASHSEED"] = str(SEED)

random.seed(SEED)
np.random.seed(SEED)

print(f"Global random seed: {SEED}")

Global random seed: 42

In [8]:
# ============================================================
# CELL 00.3.2 — PYTORCH REPRODUCIBILITY
# ============================================================

PYTORCH_REPRODUCIBILITY = {

    "seed": SEED,

    "deterministic": True,

    "benchmark": False
}

if TORCH_AVAILABLE:

    torch.manual_seed(SEED)

    if torch.cuda.is_available():

        torch.cuda.manual_seed(SEED)
        torch.cuda.manual_seed_all(SEED)

        torch.backends.cudnn.deterministic = True
        torch.backends.cudnn.benchmark = False

print("Random seed configuration applied.")

Random seed configuration applied.

In [9]:
# ============================================================
# CELL 00.4.1 — GOOGLE DRIVE
# ============================================================

from google.colab import drive

drive.mount(
    "/content/drive",
    force_remount=False
)

print("Google Drive mounted successfully.")

Mounted at /content/drive
Google Drive mounted successfully.

In [10]:
# ============================================================
# CELL 00.4.2 — PROJECT ROOT
# ============================================================

PROJECT_ROOT = Path(
    "/content/drive/MyDrive/AIR_LLM_Research"
)

print(f"Project Root:\n{PROJECT_ROOT}")

Project Root:
/content/drive/MyDrive/AIR_LLM_Research

In [11]:
# ============================================================
# CELL 00.4.3 — PROJECT IDENTITY
# ============================================================

PROJECT_NAME = "AIR-LLM Research Project"

PROJECT_CODE = "AIR-LLM"

PROJECT_VERSION = "1.0"

EXPERIMENT_VERSION = "AIR-LLM-v1"

CONFIGURATION_VERSION = "CONFIG-v1"

print("=" * 100)
print("PROJECT IDENTITY")
print("=" * 100)

print(f"Project              : {PROJECT_NAME}")
print(f"Project Code         : {PROJECT_CODE}")
print(f"Project Version      : {PROJECT_VERSION}")
print(f"Experiment Version   : {EXPERIMENT_VERSION}")
print(f"Configuration        : {CONFIGURATION_VERSION}")
print(f"Project Root         : {PROJECT_ROOT}")

====================================================================================================
PROJECT IDENTITY
====================================================================================================
Project              : AIR-LLM Research Project
Project Code         : AIR-LLM
Project Version      : 1.0
Experiment Version   : AIR-LLM-v1
Configuration        : CONFIG-v1
Project Root         : /content/drive/MyDrive/AIR_LLM_Research

In [12]:
# ============================================================
# CELL 00.5.1 — DATASET REGISTRY
# ============================================================

DATASET_REGISTRY = {

    "adult_income": {

        "dataset_name":
            "Adult Income",

        "raw_file":
            "adult_income.csv",

        "processed_file":
            "adult_income_processed.csv",

        "target":
            "income",

        "task":
            "classification",

        "domain":
            "socioeconomic",

        "expected_mixed_type":
            True
    },

    "bank_marketing": {

        "dataset_name":
            "Bank Marketing",

        "raw_file":
            "bank_marketing.csv",

        "processed_file":
            "bank_marketing_processed.csv",

        "target":
            "y",

        "task":
            "classification",

        "domain":
            "financial_marketing",

        "expected_mixed_type":
            True
    },

    "diabetes_130us": {

        "dataset_name":
            "Diabetes 130-US Hospitals",

        "raw_file":
            "diabetes_130us.csv",

        "processed_file":
            "diabetes_130us_processed.csv",

        "target":
            "readmitted",

        "task":
            "classification",

        "domain":
            "healthcare",

        "expected_mixed_type":
            True
    }
}

DATASETS = list(
    DATASET_REGISTRY.keys()
)

print("=" * 100)
print("DATASET REGISTRY")
print("=" * 100)

for dataset_id, metadata in DATASET_REGISTRY.items():

    print(
        f"{dataset_id:20s} | "
        f"{metadata['dataset_name']:30s} | "
        f"Target: {metadata['target']}"
    )

====================================================================================================
DATASET REGISTRY
====================================================================================================
adult_income         | Adult Income                   | Target: income
bank_marketing       | Bank Marketing                 | Target: y
diabetes_130us       | Diabetes 130-US Hospitals      | Target: readmitted

In [13]:
# ============================================================
# CELL 00.5.2 — DATASET PATH REGISTRY
# ============================================================

DATASET_PATHS = {}

for dataset_id, metadata in DATASET_REGISTRY.items():

    DATASET_PATHS[dataset_id] = {

        "raw":
            PROJECT_ROOT
            / "data"
            / "raw"
            / metadata["raw_file"],

        "processed":
            PROJECT_ROOT
            / "data"
            / "processed"
            / metadata["processed_file"]
    }

for dataset_id, paths in DATASET_PATHS.items():

    print(f"\n{dataset_id}")
    print(f"  Raw       : {paths['raw']}")
    print(f"  Processed : {paths['processed']}")

adult_income
  Raw       : /content/drive/MyDrive/AIR_LLM_Research/data/raw/adult_income.csv
  Processed : /content/drive/MyDrive/AIR_LLM_Research/data/processed/adult_income_processed.csv

bank_marketing
  Raw       : /content/drive/MyDrive/AIR_LLM_Research/data/raw/bank_marketing.csv
  Processed : /content/drive/MyDrive/AIR_LLM_Research/data/processed/bank_marketing_processed.csv

diabetes_130us
  Raw       : /content/drive/MyDrive/AIR_LLM_Research/data/raw/diabetes_130us.csv
  Processed : /content/drive/MyDrive/AIR_LLM_Research/data/processed/diabetes_130us_processed.csv

In [14]:
# ============================================================
# CELL 00.5.3 — DATASET REGISTRY VALIDATION
# ============================================================

REQUIRED_DATASET_FIELDS = [
    "dataset_name",
    "raw_file",
    "processed_file",
    "target",
    "task",
    "domain"
]

for dataset_id, metadata in DATASET_REGISTRY.items():

    for field in REQUIRED_DATASET_FIELDS:

        assert field in metadata, (
            f"{dataset_id}: missing field '{field}'"
        )

    assert metadata["task"] == "classification"

assert set(DATASETS) == {
    "adult_income",
    "bank_marketing",
    "diabetes_130us"
}

print("Dataset registry validation: PASSED")

Dataset registry validation: PASSED

In [15]:
# ============================================================
# CELL 00.6.1 — FEATURE / TARGET CONFIGURATION
# ============================================================

FEATURE_TARGET_REGISTRY = {

    "adult_income": {

        "target": "income",

        "numeric_features": None,

        "categorical_features": None,

        "excluded_features": [],

        "feature_detection": "automatic",

        "target_excluded_from_imputation": True
    },

    "bank_marketing": {

        "target": "y",

        "numeric_features": None,

        "categorical_features": None,

        "excluded_features": [],

        "feature_detection": "automatic",

        "target_excluded_from_imputation": True
    },

    "diabetes_130us": {

        "target": "readmitted",

        "numeric_features": None,

        "categorical_features": None,

        "excluded_features": [],

        "feature_detection": "automatic",

        "target_excluded_from_imputation": True
    }
}

for dataset_id, config in FEATURE_TARGET_REGISTRY.items():

    assert dataset_id in DATASET_REGISTRY

    assert (
        config["target"]
        == DATASET_REGISTRY[dataset_id]["target"]
    )

print("=" * 100)
print("FEATURE / TARGET CONFIGURATION")
print("=" * 100)

for dataset_id, config in FEATURE_TARGET_REGISTRY.items():

    print(
        f"{dataset_id:20s} | "
        f"Target: {config['target']:15s} | "
        f"Automatic feature detection: "
        f"{config['feature_detection']}"
    )

====================================================================================================
FEATURE / TARGET CONFIGURATION
====================================================================================================
adult_income         | Target: income          | Automatic feature detection: automatic
bank_marketing       | Target: y               | Automatic feature detection: automatic
diabetes_130us       | Target: readmitted      | Automatic feature detection: automatic

In [16]:
# ============================================================
# CELL 00.6.2 — FEATURE TYPE DETECTION POLICY
# ============================================================

FEATURE_TYPE_POLICY = {

    "numeric_detection": {

        "method": "pandas_numeric_dtype"
    },

    "categorical_detection": {

        "method":
            "object_category_bool_string_dtype"
    },

    "target_handling": {

        "exclude_from_imputation": True
    },

    "identifier_handling": {

        "detect_and_flag": True,

        "automatic_imputation": False
    },

    "constant_features": {

        "detect": True,

        "flag": True
    }
}

print(
    json.dumps(
        FEATURE_TYPE_POLICY,
        indent=4
    )
)

{
    "numeric_detection": {
        "method": "pandas_numeric_dtype"
    },
    "categorical_detection": {
        "method": "object_category_bool_string_dtype"
    },
    "target_handling": {
        "exclude_from_imputation": true
    },
    "identifier_handling": {
        "detect_and_flag": true,
        "automatic_imputation": false
    },
    "constant_features": {
        "detect": true,
        "flag": true
    }
}

In [17]:
# ============================================================
# CELL 00.7.1 — MISSINGNESS CONFIGURATION
# ============================================================

MISSINGNESS_CONFIG = {

    "mechanisms": [

        "MCAR",

        "MAR"
    ],

    "rates": [

        0.10,
        0.20,
        0.30,
        0.40,
        0.50
    ],

    "repetitions": 5,

    "random_seed": SEED,

    "target_excluded": True,

    "preserve_original_data": True,

    "feature_level_generation": True,

    "same_scenario_across_methods": True,

    "same_scenario_across_datasets": True,

    "missingness_indicator_saved": True
}

print("=" * 100)
print("MISSINGNESS CONFIGURATION")
print("=" * 100)

for key, value in MISSINGNESS_CONFIG.items():

    print(f"{key:35s}: {value}")

====================================================================================================
MISSINGNESS CONFIGURATION
====================================================================================================
mechanisms                         : ['MCAR', 'MAR']
rates                              : [0.1, 0.2, 0.3, 0.4, 0.5]
repetitions                        : 5
random_seed                        : 42
target_excluded                    : True
preserve_original_data             : True
feature_level_generation           : True
same_scenario_across_methods       : True
same_scenario_across_datasets      : True
missingness_indicator_saved        : True

In [18]:
# ============================================================
# CELL 00.7.2 — DATA SPLIT CONFIGURATION
# ============================================================

SPLIT_CONFIG = {

    "train_size": 0.70,

    "validation_size": 0.15,

    "test_size": 0.15,

    "random_state": SEED,

    "stratify_target": True,

    "preserve_test_ground_truth": True
}

assert np.isclose(
    SPLIT_CONFIG["train_size"]
    + SPLIT_CONFIG["validation_size"]
    + SPLIT_CONFIG["test_size"],
    1.0
)

print("Train      :", SPLIT_CONFIG["train_size"])
print("Validation :", SPLIT_CONFIG["validation_size"])
print("Test       :", SPLIT_CONFIG["test_size"])

Train      : 0.7
Validation : 0.15
Test       : 0.15

In [19]:
# ============================================================
# CELL 00.7.3 — MISSINGNESS VALIDATION
# ============================================================

assert set(
    MISSINGNESS_CONFIG["mechanisms"]
).issubset({"MCAR", "MAR"})

assert all(
    0 < rate < 1
    for rate in MISSINGNESS_CONFIG["rates"]
)

assert (
    MISSINGNESS_CONFIG["repetitions"]
    >= 1
)

assert (
    MISSINGNESS_CONFIG["target_excluded"]
    is True
)

print("Missingness configuration validation: PASSED")

Missingness configuration validation: PASSED

In [20]:
# ============================================================
# CELL 00.8.1 — CANDIDATE STRATEGY REGISTRY
# ============================================================

CANDIDATE_STRATEGY_REGISTRY = {

    "Mean": {

        "family": "statistical",

        "supported_types": [
            "numerical"
        ],

        "multivariate": False,

        "nonlinear": False,

        "requires_training": False
    },

    "Median": {

        "family": "statistical",

        "supported_types": [
            "numerical"
        ],

        "multivariate": False,

        "nonlinear": False,

        "requires_training": False
    },

    "Mode": {

        "family": "statistical",

        "supported_types": [
            "categorical"
        ],

        "multivariate": False,

        "nonlinear": False,

        "requires_training": False
    },

    "KNN": {

        "family": "machine_learning",

        "supported_types": [
            "numerical",
            "categorical"
        ],

        "multivariate": True,

        "nonlinear": True,

        "requires_training": False
    },

    "IterativeImputer": {

        "family": "machine_learning",

        "supported_types": [
            "numerical"
        ],

        "multivariate": True,

        "nonlinear": False,

        "requires_training": True
    },

    "RandomForest": {

        "family": "machine_learning",

        "supported_types": [
            "numerical",
            "categorical"
        ],

        "multivariate": True,

        "nonlinear": True,

        "requires_training": True
    },

    "MissForest": {

        "family": "machine_learning",

        "supported_types": [
            "numerical",
            "categorical"
        ],

        "multivariate": True,

        "nonlinear": True,

        "requires_training": True
    }
}

CANDIDATE_STRATEGIES = list(
    CANDIDATE_STRATEGY_REGISTRY.keys()
)

print("=" * 100)
print("CANDIDATE STRATEGY REGISTRY")
print("=" * 100)

for method, properties in (
    CANDIDATE_STRATEGY_REGISTRY.items()
):

    print(
        f"{method:22s} | "
        f"{properties['family']:18s} | "
        f"Types: {properties['supported_types']}"
    )

====================================================================================================
CANDIDATE STRATEGY REGISTRY
====================================================================================================
Mean                   | statistical        | Types: ['numerical']
Median                 | statistical        | Types: ['numerical']
Mode                   | statistical        | Types: ['categorical']
KNN                    | machine_learning   | Types: ['numerical', 'categorical']
IterativeImputer       | machine_learning   | Types: ['numerical']
RandomForest           | machine_learning   | Types: ['numerical', 'categorical']
MissForest             | machine_learning   | Types: ['numerical', 'categorical']

In [21]:
# ============================================================
# CELL 00.8.2 — STRATEGY SELECTION POLICY
# ============================================================

STRATEGY_SELECTION_POLICY = {

    "selection_granularity":
        "feature_level",

    "candidate_pool":
        "all_compatible_methods",

    "llm_role":
        "recommendation_and_reasoning",

    "empirical_validation":
        True,

    "final_selection":
        "best_supported_strategy",

    "fallback_strategy":
        "best_empirical_candidate",

    "target_imputation":
        False,

    "selection_explanation":
        True
}

print(
    json.dumps(
        STRATEGY_SELECTION_POLICY,
        indent=4
    )
)

{
    "selection_granularity": "feature_level",
    "candidate_pool": "all_compatible_methods",
    "llm_role": "recommendation_and_reasoning",
    "empirical_validation": true,
    "final_selection": "best_supported_strategy",
    "fallback_strategy": "best_empirical_candidate",
    "target_imputation": false,
    "selection_explanation": true
}

In [22]:
# ============================================================
# CELL 00.9.1 — LLM CONFIGURATION
# ============================================================

LLM_CONFIG = {

    "enabled": True,

    "temperature": 0.0,

    "deterministic": True,

    "feature_level_reasoning": True,

    "data_evidence_required": True,

    "missingness_mechanism_required": True,

    "feature_type_required": True,

    "missingness_rate_required": True,

    "candidate_capability_matching": True,

    "strategy_justification_required": True,

    "confidence_required": True,

    "explanation_required": True,

    "structured_output": True,

    "single_final_recommendation": True,

    "fallback_to_empirical_evidence": True,

    "max_recommendations": 1,

    "api_key_storage":
        "environment_variable_only",

    "api_key_persistence":
        False
}

print("=" * 100)
print("LLM CONFIGURATION")
print("=" * 100)

for key, value in LLM_CONFIG.items():

    print(f"{key:40s}: {value}")

====================================================================================================
LLM CONFIGURATION
====================================================================================================
enabled                                 : True
temperature                             : 0.0
deterministic                           : True
feature_level_reasoning                 : True
data_evidence_required                  : True
missingness_mechanism_required          : True
feature_type_required                   : True
missingness_rate_required               : True
candidate_capability_matching           : True
strategy_justification_required         : True
confidence_required                     : True
explanation_required                    : True
structured_output                       : True
single_final_recommendation             : True
fallback_to_empirical_evidence          : True
max_recommendations                     : 1
api_key_storage                         : environment_variable_only
api_key_persistence                     : False

In [23]:
# ============================================================
# CELL 00.9.2 — LLM DECISION OUTPUT SCHEMA
# ============================================================

LLM_OUTPUT_SCHEMA = {

    "dataset_id": "string",

    "feature": "string",

    "feature_type": "numerical|categorical",

    "missingness_mechanism": "MCAR|MAR",

    "missingness_rate": "float",

    "data_evidence": "string",

    "recommended_strategy": "string",

    "reasoning": "string",

    "confidence": "float",

    "alternative_strategy": "string|null",

    "final_decision": "string",

    "fallback_used": "boolean"
}

print(
    json.dumps(
        LLM_OUTPUT_SCHEMA,
        indent=4
    )
)

{
    "dataset_id": "string",
    "feature": "string",
    "feature_type": "numerical|categorical",
    "missingness_mechanism": "MCAR|MAR",
    "missingness_rate": "float",
    "data_evidence": "string",
    "recommended_strategy": "string",
    "reasoning": "string",
    "confidence": "float",
    "alternative_strategy": "string|null",
    "final_decision": "string",
    "fallback_used": "boolean"
}

In [24]:
# ============================================================
# CELL 00.10.1 — IMPUTATION EVALUATION
# ============================================================

EVALUATION_METRICS = {

    "numerical": [

        "MAE",

        "RMSE"
    ],

    "categorical": [

        "Accuracy",

        "F1"
    ],

    "distribution": [

        "KS",

        "Wasserstein"
    ],

    "relationship": [

        "Correlation_Preservation"
    ],

    "downstream": [

        "Accuracy",

        "F1",

        "ROC_AUC"
    ]
}

print("=" * 100)
print("EVALUATION METRICS")
print("=" * 100)

for category, metrics in EVALUATION_METRICS.items():

    print(f"\n{category.upper()}")

    for metric in metrics:

        print(f"  • {metric}")

====================================================================================================
EVALUATION METRICS
====================================================================================================

NUMERICAL
  • MAE
  • RMSE

CATEGORICAL
  • Accuracy
  • F1

DISTRIBUTION
  • KS
  • Wasserstein

RELATIONSHIP
  • Correlation_Preservation

DOWNSTREAM
  • Accuracy
  • F1
  • ROC_AUC

In [25]:
# ============================================================
# CELL 00.10.2 — STATISTICAL EVALUATION CONFIGURATION
# ============================================================

STATISTICAL_CONFIG = {

    "alpha": 0.05,

    "confidence_level": 0.95,

    "paired_comparison": True,

    "multiple_comparison_correction": "Holm",

    "effect_size": True,

    "confidence_interval": True,

    "report_mean": True,

    "report_standard_deviation": True,

    "report_median": True
}

print(
    json.dumps(
        STATISTICAL_CONFIG,
        indent=4
    )
)

{
    "alpha": 0.05,
    "confidence_level": 0.95,
    "paired_comparison": true,
    "multiple_comparison_correction": "Holm",
    "effect_size": true,
    "confidence_interval": true,
    "report_mean": true,
    "report_standard_deviation": true,
    "report_median": true
}

In [26]:
# ============================================================
# CELL 00.10.3 — ROBUSTNESS EVALUATION
# ============================================================

ROBUSTNESS_CONFIG = {

    "enabled": True,

    "cross_dataset": True,

    "cross_missingness_rate": True,

    "cross_missingness_mechanism": True,

    "method_consistency": True,

    "mean_rank": True,

    "rank_variability": True,

    "failure_rate": True,

    "performance_variability": True
}

print(
    json.dumps(
        ROBUSTNESS_CONFIG,
        indent=4
    )
)

{
    "enabled": true,
    "cross_dataset": true,
    "cross_missingness_rate": true,
    "cross_missingness_mechanism": true,
    "method_consistency": true,
    "mean_rank": true,
    "rank_variability": true,
    "failure_rate": true,
    "performance_variability": true
}

In [27]:
# ============================================================
# CELL 00.11.1 — UTILITY WEIGHTS
# ============================================================

UTILITY_WEIGHTS = {

    "imputation_accuracy": 0.40,

    "distribution_fidelity": 0.20,

    "downstream_utility": 0.20,

    "computational_efficiency": 0.10,

    "robustness": 0.10
}

UTILITY_WEIGHT_SUM = sum(
    UTILITY_WEIGHTS.values()
)

assert np.isclose(
    UTILITY_WEIGHT_SUM,
    1.0
), "Utility weights must sum to 1.0."

print("=" * 100)
print("UTILITY WEIGHTS")
print("=" * 100)

for criterion, weight in UTILITY_WEIGHTS.items():

    print(
        f"{criterion:30s}: {weight:.2f}"
    )

print(
    f"\nTotal: {UTILITY_WEIGHT_SUM:.2f}"
)

====================================================================================================
UTILITY WEIGHTS
====================================================================================================
imputation_accuracy           : 0.40
distribution_fidelity         : 0.20
downstream_utility            : 0.20
computational_efficiency      : 0.10
robustness                    : 0.10

Total: 1.00

In [28]:
# ============================================================
# CELL 00.11.2 — UTILITY SCORE DEFINITION
# ============================================================

UTILITY_SCORE_DEFINITION = {

    "formula":
        "U = Σ(w_i × normalized_score_i)",

    "higher_is_better": [

        "imputation_accuracy",

        "distribution_fidelity",

        "downstream_utility",

        "computational_efficiency",

        "robustness"
    ],

    "normalization":
        "metric-specific normalization before aggregation",

    "weight_sum":
        1.0
}

print(
    json.dumps(
        UTILITY_SCORE_DEFINITION,
        indent=4
    )
)

{
    "formula": "U = \u03a3(w_i \u00d7 normalized_score_i)",
    "higher_is_better": [
        "imputation_accuracy",
        "distribution_fidelity",
        "downstream_utility",
        "computational_efficiency",
        "robustness"
    ],
    "normalization": "metric-specific normalization before aggregation",
    "weight_sum": 1.0
}

In [29]:
# ============================================================
# CELL 00.12.1 — CONFIDENCE THRESHOLDS
# ============================================================

CONFIDENCE_THRESHOLDS = {

    "high": 0.80,

    "medium": 0.60,

    "low": 0.00,

    "minimum_selection_confidence": 0.60,

    "minimum_evidence_confidence": 0.60
}

assert (
    0.0
    <= CONFIDENCE_THRESHOLDS["low"]
    <= CONFIDENCE_THRESHOLDS["medium"]
    <= CONFIDENCE_THRESHOLDS["high"]
    <= 1.0
)

assert (
    0.0
    <= CONFIDENCE_THRESHOLDS[
        "minimum_selection_confidence"
    ]
    <= 1.0
)

print("=" * 100)
print("CONFIDENCE THRESHOLDS")
print("=" * 100)

for key, value in CONFIDENCE_THRESHOLDS.items():

    print(
        f"{key:40s}: {value:.2f}"
    )

====================================================================================================
CONFIDENCE THRESHOLDS
====================================================================================================
high                                    : 0.80
medium                                  : 0.60
low                                     : 0.00
minimum_selection_confidence            : 0.60
minimum_evidence_confidence             : 0.60

In [30]:
# ============================================================
# CELL 00.12.2 — CONFIDENCE DECISION POLICY
# ============================================================

CONFIDENCE_POLICY = {

    "high":
        "accept recommendation",

    "medium":
        "accept only with empirical support",

    "low":
        "use empirical fallback",

    "below_minimum":
        "reject standalone LLM recommendation",

    "empirical_validation_required":
        True
}

print(
    json.dumps(
        CONFIDENCE_POLICY,
        indent=4
    )
)

{
    "high": "accept recommendation",
    "medium": "accept only with empirical support",
    "low": "use empirical fallback",
    "below_minimum": "reject standalone LLM recommendation",
    "empirical_validation_required": true
}

In [31]:
# ============================================================
# CELL 00.13.1 — EXPERIMENT SCENARIO REGISTRY
# ============================================================

EXPERIMENT_SCENARIO_REGISTRY = {}

scenario_number = 1

for mechanism in MISSINGNESS_CONFIG["mechanisms"]:

    for rate in MISSINGNESS_CONFIG["rates"]:

        scenario_id = (
            f"S{scenario_number:02d}"
        )

        EXPERIMENT_SCENARIO_REGISTRY[
            scenario_id
        ] = {

            "scenario_id":
                scenario_id,

            "mechanism":
                mechanism,

            "missingness_rate":
                rate,

            "repetitions":
                MISSINGNESS_CONFIG["repetitions"],

            "target_excluded":
                MISSINGNESS_CONFIG["target_excluded"],

            "random_seed":
                SEED
        }

        scenario_number += 1


SCENARIO_REGISTRY_DF = pd.DataFrame(
    EXPERIMENT_SCENARIO_REGISTRY
).T.reset_index(drop=True)

display(SCENARIO_REGISTRY_DF)

print(
    f"Total experimental scenarios: "
    f"{len(EXPERIMENT_SCENARIO_REGISTRY)}"
)

,scenario_id,mechanism,missingness_rate,repetitions,target_excluded,random_seed
0,S01,MCAR,0.1,5,True,42
1,S02,MCAR,0.2,5,True,42
2,S03,MCAR,0.3,5,True,42
3,S04,MCAR,0.4,5,True,42
4,S05,MCAR,0.5,5,True,42
5,S06,MAR,0.1,5,True,42
6,S07,MAR,0.2,5,True,42
7,S08,MAR,0.3,5,True,42
8,S09,MAR,0.4,5,True,42
9,S10,MAR,0.5,5,True,42

Total experimental scenarios: 10

In [32]:
# ============================================================
# CELL 00.13.2 — COMPLETE EXPERIMENTAL DESIGN
# ============================================================

EXPERIMENT_DESIGN = {

    "datasets":
        DATASETS,

    "missingness_mechanisms":
        MISSINGNESS_CONFIG["mechanisms"],

    "missingness_rates":
        MISSINGNESS_CONFIG["rates"],

    "repetitions":
        MISSINGNESS_CONFIG["repetitions"],

    "candidate_strategies":
        CANDIDATE_STRATEGIES,

    "feature_level_selection":
        True,

    "target_excluded":
        True
}

TOTAL_SCENARIO_RUNS = (
    len(DATASETS)
    * len(MISSINGNESS_CONFIG["mechanisms"])
    * len(MISSINGNESS_CONFIG["rates"])
    * MISSINGNESS_CONFIG["repetitions"]
)

print("=" * 100)
print("EXPERIMENTAL DESIGN")
print("=" * 100)

for key, value in EXPERIMENT_DESIGN.items():

    print(f"{key:30s}: {value}")

print(
    f"\nDataset × Scenario × Repetition runs: "
    f"{TOTAL_SCENARIO_RUNS}"
)

====================================================================================================
EXPERIMENTAL DESIGN
====================================================================================================
datasets                      : ['adult_income', 'bank_marketing', 'diabetes_130us']
missingness_mechanisms        : ['MCAR', 'MAR']
missingness_rates             : [0.1, 0.2, 0.3, 0.4, 0.5]
repetitions                   : 5
candidate_strategies          : ['Mean', 'Median', 'Mode', 'KNN', 'IterativeImputer', 'RandomForest', 'MissForest']
feature_level_selection       : True
target_excluded               : True

Dataset × Scenario × Repetition runs: 150

In [33]:
# ============================================================
# CELL 00.13.3 — SCENARIO VALIDATION
# ============================================================

EXPECTED_SCENARIO_COUNT = (
    len(MISSINGNESS_CONFIG["mechanisms"])
    * len(MISSINGNESS_CONFIG["rates"])
)

assert (
    len(EXPERIMENT_SCENARIO_REGISTRY)
    == EXPECTED_SCENARIO_COUNT
)

for scenario_id, scenario in (
    EXPERIMENT_SCENARIO_REGISTRY.items()
):

    assert scenario["scenario_id"] == scenario_id

    assert scenario["mechanism"] in {
        "MCAR",
        "MAR"
    }

    assert (
        scenario["missingness_rate"]
        in MISSINGNESS_CONFIG["rates"]
    )

    assert (
        scenario["repetitions"]
        == MISSINGNESS_CONFIG["repetitions"]
    )

print("Experiment scenario validation: PASSED")

Experiment scenario validation: PASSED

In [34]:
# ============================================================
# CELL 00.14.1 — PROJECT DIRECTORY CONFIGURATION
# ============================================================

DIRECTORIES = {

    "root":
        PROJECT_ROOT,

    "config":
        PROJECT_ROOT / "config",

    "data":
        PROJECT_ROOT / "data",

    "data_raw":
        PROJECT_ROOT / "data" / "raw",

    "data_processed":
        PROJECT_ROOT / "data" / "processed",

    "data_reference":
        PROJECT_ROOT / "data" / "reference",

    "experiments":
        PROJECT_ROOT / "experiments",

    "missingness":
        PROJECT_ROOT
        / "experiments"
        / "missingness",

    "imputation":
        PROJECT_ROOT
        / "experiments"
        / "imputation",

    "llm":
        PROJECT_ROOT
        / "experiments"
        / "llm",

    "evaluation":
        PROJECT_ROOT
        / "experiments"
        / "evaluation",

    "robustness":
        PROJECT_ROOT
        / "experiments"
        / "robustness",

    "models":
        PROJECT_ROOT / "models",

    "results":
        PROJECT_ROOT / "results",

    "results_raw":
        PROJECT_ROOT
        / "results"
        / "raw",

    "results_processed":
        PROJECT_ROOT
        / "results"
        / "processed",

    "tables":
        PROJECT_ROOT
        / "results"
        / "tables",

    "figures":
        PROJECT_ROOT
        / "results"
        / "figures",

    "reports":
        PROJECT_ROOT / "reports",

    "logs":
        PROJECT_ROOT / "logs",

    "artifacts":
        PROJECT_ROOT / "artifacts"
}

for name, path in DIRECTORIES.items():

    path.mkdir(
        parents=True,
        exist_ok=True
    )

print("=" * 100)
print("PROJECT DIRECTORIES CREATED / VERIFIED")
print("=" * 100)

for name, path in DIRECTORIES.items():

    print(
        f"{name:25s}: {path}"
    )

====================================================================================================
PROJECT DIRECTORIES CREATED / VERIFIED
====================================================================================================
root                     : /content/drive/MyDrive/AIR_LLM_Research
config                   : /content/drive/MyDrive/AIR_LLM_Research/config
data                     : /content/drive/MyDrive/AIR_LLM_Research/data
data_raw                 : /content/drive/MyDrive/AIR_LLM_Research/data/raw
data_processed           : /content/drive/MyDrive/AIR_LLM_Research/data/processed
data_reference           : /content/drive/MyDrive/AIR_LLM_Research/data/reference
experiments              : /content/drive/MyDrive/AIR_LLM_Research/experiments
missingness              : /content/drive/MyDrive/AIR_LLM_Research/experiments/missingness
imputation               : /content/drive/MyDrive/AIR_LLM_Research/experiments/imputation
llm                      : /content/drive/MyDrive/AIR_LLM_Research/experiments/llm
evaluation               : /content/drive/MyDrive/AIR_LLM_Research/experiments/evaluation
robustness               : /content/drive/MyDrive/AIR_LLM_Research/experiments/robustness
models                   : /content/drive/MyDrive/AIR_LLM_Research/models
results                  : /content/drive/MyDrive/AIR_LLM_Research/results
results_raw              : /content/drive/MyDrive/AIR_LLM_Research/results/raw
results_processed        : /content/drive/MyDrive/AIR_LLM_Research/results/processed
tables                   : /content/drive/MyDrive/AIR_LLM_Research/results/tables
figures                  : /content/drive/MyDrive/AIR_LLM_Research/results/figures
reports                  : /content/drive/MyDrive/AIR_LLM_Research/reports
logs                     : /content/drive/MyDrive/AIR_LLM_Research/logs
artifacts                : /content/drive/MyDrive/AIR_LLM_Research/artifacts

In [35]:
# ============================================================
# CELL 00.14.2 — DIRECTORY VALIDATION
# ============================================================

DIRECTORY_VALIDATION = []

for name, path in DIRECTORIES.items():

    DIRECTORY_VALIDATION.append({

        "directory":
            name,

        "path":
            str(path),

        "exists":
            path.exists(),

        "is_directory":
            path.is_dir()
    })

DIRECTORY_VALIDATION_DF = pd.DataFrame(
    DIRECTORY_VALIDATION
)

display(DIRECTORY_VALIDATION_DF)

assert (
    DIRECTORY_VALIDATION_DF["exists"].all()
)

assert (
    DIRECTORY_VALIDATION_DF["is_directory"].all()
)

print("All project directories validated successfully.")

,directory,path,exists,is_directory
0,root,/content/drive/MyDrive/AIR_LLM_Research,True,True
1,config,/content/drive/MyDrive/AIR_LLM_Research/config,True,True
2,data,/content/drive/MyDrive/AIR_LLM_Research/data,True,True
3,data_raw,/content/drive/MyDrive/AIR_LLM_Research/data/raw,True,True
4,data_processed,/content/drive/MyDrive/AIR_LLM_Research/data/p...,True,True
5,data_reference,/content/drive/MyDrive/AIR_LLM_Research/data/r...,True,True
6,experiments,/content/drive/MyDrive/AIR_LLM_Research/experi...,True,True
7,missingness,/content/drive/MyDrive/AIR_LLM_Research/experi...,True,True
8,imputation,/content/drive/MyDrive/AIR_LLM_Research/experi...,True,True
9,llm,/content/drive/MyDrive/AIR_LLM_Research/experi...,True,True
10,evaluation,/content/drive/MyDrive/AIR_LLM_Research/experi...,True,True
11,robustness,/content/drive/MyDrive/AIR_LLM_Research/experi...,True,True
12,models,/content/drive/MyDrive/AIR_LLM_Research/models,True,True
13,results,/content/drive/MyDrive/AIR_LLM_Research/results,True,True
14,results_raw,/content/drive/MyDrive/AIR_LLM_Research/result...,True,True
15,results_processed,/content/drive/MyDrive/AIR_LLM_Research/result...,True,True
16,tables,/content/drive/MyDrive/AIR_LLM_Research/result...,True,True
17,figures,/content/drive/MyDrive/AIR_LLM_Research/result...,True,True
18,reports,/content/drive/MyDrive/AIR_LLM_Research/reports,True,True
19,logs,/content/drive/MyDrive/AIR_LLM_Research/logs,True,True
20,artifacts,/content/drive/MyDrive/AIR_LLM_Research/artifacts,True,True

All project directories validated successfully.

In [36]:
# ============================================================
# CELL 00.15.1 — MASTER CONFIGURATION
# ============================================================

MASTER_CONFIG = {

    "project": {

        "name":
            PROJECT_NAME,

        "code":
            PROJECT_CODE,

        "version":
            PROJECT_VERSION,

        "experiment_version":
            EXPERIMENT_VERSION,

        "configuration_version":
            CONFIGURATION_VERSION
    },

    "environment": {

        "packages":
            PACKAGE_VERSIONS,

        "runtime":
            RUNTIME_INFO
    },

    "reproducibility": {

        "seed":
            SEED,

        "pytorch":
            PYTORCH_REPRODUCIBILITY
    },

    "project_root":
        str(PROJECT_ROOT),

    "datasets":
        DATASET_REGISTRY,

    "dataset_paths": {

        dataset_id: {

            key: str(value)

            for key, value
            in paths.items()
        }

        for dataset_id, paths
        in DATASET_PATHS.items()
    },

    "feature_target":
        FEATURE_TARGET_REGISTRY,

    "feature_type_policy":
        FEATURE_TYPE_POLICY,

    "missingness":
        MISSINGNESS_CONFIG,

    "split":
        SPLIT_CONFIG,

    "candidate_strategies":
        CANDIDATE_STRATEGY_REGISTRY,

    "strategy_selection_policy":
        STRATEGY_SELECTION_POLICY,

    "llm":
        LLM_CONFIG,

    "llm_output_schema":
        LLM_OUTPUT_SCHEMA,

    "evaluation":
        EVALUATION_METRICS,

    "statistical":
        STATISTICAL_CONFIG,

    "robustness":
        ROBUSTNESS_CONFIG,

    "utility_weights":
        UTILITY_WEIGHTS,

    "utility_score_definition":
        UTILITY_SCORE_DEFINITION,

    "confidence_thresholds":
        CONFIDENCE_THRESHOLDS,

    "confidence_policy":
        CONFIDENCE_POLICY,

    "experiment_scenarios":
        EXPERIMENT_SCENARIO_REGISTRY,

    "experiment_design":
        EXPERIMENT_DESIGN,

    "notebook_registry": {

        "00":
            "00_Project_Configuration.ipynb",

        "01":
            "01_Dataset_Preparation.ipynb",

        "02":
            "02_Data_Preprocessing_and_Splitting.ipynb",

        "03":
            "03_Missingness_Generation.ipynb",

        "04":
            "04_Candidate_Imputation_Methods.ipynb",

        "05":
            "05_LLM_Recommendation_and_Strategy_Selection.ipynb",

        "06":
            "06_AIR_LLM_Imputation.ipynb",

        "07":
            "07_Imputation_Evaluation.ipynb",

        "08":
            "08_Dataset_Wise_Analysis.ipynb",

        "09":
            "09_Cross_Dataset_Robustness_and_Interpretation.ipynb",

        "10":
            "10_Final_Research_Reporting.ipynb"
    }
}

print("Master configuration object created.")

Master configuration object created.

In [37]:
# ============================================================
# CELL 00.15.2 — FINAL MASTER YAML CONFIGURATION EXPORT
# ============================================================
#
# Purpose:
#   1. Convert EVERY configuration value to a YAML-safe
#      native Python object.
#   2. Remove library-specific objects such as torch version
#      objects, NumPy scalars, Path objects, etc.
#   3. Save the permanent master configuration.
#   4. Reload the YAML immediately.
#   5. Validate that the saved configuration is usable by
#      all future AIR-LLM research notebooks.
#
# This cell is intentionally self-contained.
# ============================================================

from pathlib import Path
import json
import numbers
import yaml
import numpy as np


# ------------------------------------------------------------
# 1. UNIVERSAL YAML-SAFE CONVERSION
# ------------------------------------------------------------

def _yaml_safe(value):
    """
    Recursively convert arbitrary Python/library objects into
    standard Python objects supported by yaml.safe_dump().
    """

    # None
    if value is None:
        return None

    # Native primitive types
    if type(value) is str:
        return value

    if type(value) is int:
        return value

    if type(value) is float:
        return value

    if type(value) is bool:
        return value

    # pathlib.Path
    if isinstance(value, Path):
        return str(value)

    # NumPy scalar types
    if isinstance(value, np.generic):
        return _yaml_safe(value.item())

    # NumPy arrays
    if isinstance(value, np.ndarray):
        return [
            _yaml_safe(v)
            for v in value.tolist()
        ]

    # Dictionaries
    if isinstance(value, dict):
        return {
            str(_yaml_safe(key)): _yaml_safe(val)
            for key, val in value.items()
        }

    # Lists / tuples
    if isinstance(value, (list, tuple)):
        return [
            _yaml_safe(v)
            for v in value
        ]

    # Sets
    if isinstance(value, set):
        return [
            _yaml_safe(v)
            for v in sorted(
                value,
                key=lambda x: str(x)
            )
        ]

    # Numeric library objects
    if isinstance(value, numbers.Integral):
        return int(value)

    if isinstance(value, numbers.Real):
        return float(value)

    # Objects such as torch.__version__,
    # packaging.version.Version, etc.
    #
    # Convert everything remaining into an ordinary string.
    return str(value)


# ------------------------------------------------------------
# 2. REBUILD MASTER CONFIGURATION
# ------------------------------------------------------------

if "MASTER_CONFIG" not in globals():
    raise RuntimeError(
        "MASTER_CONFIG is not defined. "
        "Run the previous configuration cells "
        "00.1–00.14 before running CELL 00.15.2."
    )

MASTER_CONFIG_SERIALIZABLE = _yaml_safe(
    MASTER_CONFIG
)


# ------------------------------------------------------------
# 3. FINAL SAFETY CHECK
# ------------------------------------------------------------

# Convert to JSON first.
#
# JSON only accepts standard Python types and therefore provides
# an additional guarantee that no library-specific object remains.

try:

    json.dumps(
        MASTER_CONFIG_SERIALIZABLE,
        ensure_ascii=False
    )

except TypeError as error:

    raise TypeError(
        "MASTER_CONFIG still contains a non-serializable "
        f"object after conversion: {error}"
    )


# ------------------------------------------------------------
# 4. ENSURE CONFIGURATION DIRECTORY EXISTS
# ------------------------------------------------------------

if "DIRECTORIES" not in globals():
    raise RuntimeError(
        "DIRECTORIES is not defined. "
        "Run CELL 00.14 before CELL 00.15.2."
    )

CONFIG_DIR = Path(
    DIRECTORIES["config"]
)

CONFIG_DIR.mkdir(
    parents=True,
    exist_ok=True
)


# ------------------------------------------------------------
# 5. MASTER YAML PATH
# ------------------------------------------------------------

CONFIG_PATH = (
    CONFIG_DIR / "config.yaml"
)


# ------------------------------------------------------------
# 6. SAVE MASTER YAML
# ------------------------------------------------------------

with open(
    CONFIG_PATH,
    "w",
    encoding="utf-8"
) as file:

    yaml.safe_dump(
        MASTER_CONFIG_SERIALIZABLE,
        file,
        sort_keys=False,
        allow_unicode=True,
        default_flow_style=False,
        indent=2,
        width=120
    )


# ------------------------------------------------------------
# 7. VERIFY FILE EXISTS
# ------------------------------------------------------------

if not CONFIG_PATH.exists():
    raise RuntimeError(
        "Master configuration file was not created."
    )

if CONFIG_PATH.stat().st_size == 0:
    raise RuntimeError(
        "Master configuration file is empty."
    )


# ------------------------------------------------------------
# 8. RELOAD SAVED YAML
# ------------------------------------------------------------

with open(
    CONFIG_PATH,
    "r",
    encoding="utf-8"
) as file:

    MASTER_CONFIG_LOADED = yaml.safe_load(file)


# ------------------------------------------------------------
# 9. VALIDATE RELOADED CONFIGURATION
# ------------------------------------------------------------

if not isinstance(
    MASTER_CONFIG_LOADED,
    dict
):

    raise RuntimeError(
        "Reloaded MASTER_CONFIG is not a dictionary."
    )


# ------------------------------------------------------------
# 10. VERIFY PROJECT ROOT
# ------------------------------------------------------------

if "project_root" in MASTER_CONFIG_SERIALIZABLE:

    saved_project_root = str(
        MASTER_CONFIG_SERIALIZABLE["project_root"]
    )

    if "PROJECT_ROOT" in globals():

        expected_project_root = str(
            PROJECT_ROOT
        )

        if saved_project_root != expected_project_root:

            raise RuntimeError(
                "PROJECT_ROOT mismatch in saved configuration.\n"
                f"Expected: {expected_project_root}\n"
                f"Saved:    {saved_project_root}"
            )


# ------------------------------------------------------------
# 11. VERIFY DATASET REGISTRY
# ------------------------------------------------------------

if "datasets" in MASTER_CONFIG_SERIALIZABLE:

    saved_datasets = (
        MASTER_CONFIG_SERIALIZABLE["datasets"]
    )

    if not isinstance(
        saved_datasets,
        dict
    ):

        raise RuntimeError(
            "Dataset registry is not a dictionary."
        )


# ------------------------------------------------------------
# 12. VERIFY IMPORTANT CONFIGURATION SECTIONS
# ------------------------------------------------------------

EXPECTED_CONFIG_SECTIONS = [

    "datasets",
    "features",
    "missingness",
    "candidate_strategies",
    "llm",
    "evaluation",
    "utility_weights",
    "confidence_thresholds",
    "experiment_scenarios"
]

PRESENT_SECTIONS = [
    key
    for key in EXPECTED_CONFIG_SECTIONS
    if key in MASTER_CONFIG_SERIALIZABLE
]

MISSING_SECTIONS = [
    key
    for key in EXPECTED_CONFIG_SECTIONS
    if key not in MASTER_CONFIG_SERIALIZABLE
]

if MISSING_SECTIONS:

    print(
        "WARNING — Configuration sections not found:"
    )

    for section in MISSING_SECTIONS:
        print(f"  - {section}")


# ------------------------------------------------------------
# 13. WRITE A HUMAN-READABLE CONFIGURATION MANIFEST
# ------------------------------------------------------------

MANIFEST_PATH = (
    CONFIG_DIR
    / "configuration_manifest.json"
)

MANIFEST = {

    "configuration_file":
        str(CONFIG_PATH),

    "configuration_size_bytes":
        int(CONFIG_PATH.stat().st_size),

    "configuration_sections":
        list(
            MASTER_CONFIG_SERIALIZABLE.keys()
        ),

    "expected_sections":
        EXPECTED_CONFIG_SECTIONS,

    "present_required_sections":
        PRESENT_SECTIONS,

    "missing_required_sections":
        MISSING_SECTIONS,

    "yaml_reload_success":
        True,

    "yaml_serialization":
        "PASSED",

    "json_serialization":
        "PASSED"
}


with open(
    MANIFEST_PATH,
    "w",
    encoding="utf-8"
) as file:

    json.dump(
        MANIFEST,
        file,
        indent=2,
        ensure_ascii=False
    )


# ------------------------------------------------------------
# 14. FINAL OUTPUT
# ------------------------------------------------------------

print()
print("=" * 100)
print("AIR-LLM MASTER CONFIGURATION EXPORT")
print("=" * 100)

print(
    f"Master YAML configuration : {CONFIG_PATH}"
)

print(
    f"Configuration size         : "
    f"{CONFIG_PATH.stat().st_size:,} bytes"
)

print(
    f"Manifest                   : {MANIFEST_PATH}"
)

print(
    f"YAML serialization         : PASSED"
)

print(
    f"YAML reload validation     : PASSED"
)

print(
    f"JSON serialization         : PASSED"
)

print(
    f"Configuration sections     : "
    f"{len(MASTER_CONFIG_SERIALIZABLE)}"
)

print()
print("Required configuration sections:")

for section in EXPECTED_CONFIG_SECTIONS:

    status = (
        "OK"
        if section in MASTER_CONFIG_SERIALIZABLE
        else "MISSING"
    )

    print(
        f"  [{status}] {section}"
    )

print("=" * 100)
print("CELL 00.15.2 COMPLETED SUCCESSFULLY")
print("=" * 100)

WARNING — Configuration sections not found:
  - features

====================================================================================================
AIR-LLM MASTER CONFIGURATION EXPORT
====================================================================================================
Master YAML configuration : /content/drive/MyDrive/AIR_LLM_Research/config/config.yaml
Configuration size         : 9,455 bytes
Manifest                   : /content/drive/MyDrive/AIR_LLM_Research/config/configuration_manifest.json
YAML serialization         : PASSED
YAML reload validation     : PASSED
JSON serialization         : PASSED
Configuration sections     : 24

Required configuration sections:
  [OK] datasets
  [MISSING] features
  [OK] missingness
  [OK] candidate_strategies
  [OK] llm
  [OK] evaluation
  [OK] utility_weights
  [OK] confidence_thresholds
  [OK] experiment_scenarios
====================================================================================================
CELL 00.15.2 COMPLETED SUCCESSFULLY
====================================================================================================

In [38]:
# ============================================================
# CELL 00.15.3 — SAVE DATASET REGISTRY
# ============================================================

DATASET_REGISTRY_PATH = (
    DIRECTORIES["config"]
    / "dataset_registry.yaml"
)

with open(
    DATASET_REGISTRY_PATH,
    "w",
    encoding="utf-8"
) as file:

    yaml.safe_dump(
        DATASET_REGISTRY,
        file,
        sort_keys=False,
        allow_unicode=True
    )

print(
    f"Dataset registry saved:\n"
    f"{DATASET_REGISTRY_PATH}"
)

Dataset registry saved:
/content/drive/MyDrive/AIR_LLM_Research/config/dataset_registry.yaml

In [39]:
# ============================================================
# CELL 00.15.4 — SAVE FEATURE / TARGET REGISTRY
# ============================================================

FEATURE_TARGET_REGISTRY_PATH = (
    DIRECTORIES["config"]
    / "feature_target_registry.yaml"
)

with open(
    FEATURE_TARGET_REGISTRY_PATH,
    "w",
    encoding="utf-8"
) as file:

    yaml.safe_dump(
        FEATURE_TARGET_REGISTRY,
        file,
        sort_keys=False,
        allow_unicode=True
    )

print(
    f"Feature/target registry saved:\n"
    f"{FEATURE_TARGET_REGISTRY_PATH}"
)

Feature/target registry saved:
/content/drive/MyDrive/AIR_LLM_Research/config/feature_target_registry.yaml

In [40]:
# ============================================================
# CELL 00.15.5 — SAVE EXPERIMENT SCENARIO REGISTRY
# ============================================================

SCENARIO_REGISTRY_PATH = (
    DIRECTORIES["config"]
    / "experiment_scenario_registry.yaml"
)

with open(
    SCENARIO_REGISTRY_PATH,
    "w",
    encoding="utf-8"
) as file:

    yaml.safe_dump(
        EXPERIMENT_SCENARIO_REGISTRY,
        file,
        sort_keys=False,
        allow_unicode=True
    )

print(
    f"Scenario registry saved:\n"
    f"{SCENARIO_REGISTRY_PATH}"
)

Scenario registry saved:
/content/drive/MyDrive/AIR_LLM_Research/config/experiment_scenario_registry.yaml

In [41]:
# ============================================================
# CELL 00.15.6 — SAVE EXPERIMENT DESIGN
# ============================================================

EXPERIMENT_DESIGN_PATH = (
    DIRECTORIES["config"]
    / "experiment_design.yaml"
)

with open(
    EXPERIMENT_DESIGN_PATH,
    "w",
    encoding="utf-8"
) as file:

    yaml.safe_dump(
        EXPERIMENT_DESIGN,
        file,
        sort_keys=False,
        allow_unicode=True
    )

print(
    f"Experiment design saved:\n"
    f"{EXPERIMENT_DESIGN_PATH}"
)

Experiment design saved:
/content/drive/MyDrive/AIR_LLM_Research/config/experiment_design.yaml

In [42]:
# ============================================================
# CELL 00.15.7 — SAVE CONFIGURATION SNAPSHOT
# ============================================================

CONFIG_SNAPSHOT_PATH = (
    DIRECTORIES["artifacts"]
    / "configuration_snapshot.json"
)

CONFIG_SNAPSHOT = {

    "created_at":
        datetime.now(timezone.utc).isoformat(),

    "project":
        PROJECT_NAME,

    "project_version":
        PROJECT_VERSION,

    "experiment_version":
        EXPERIMENT_VERSION,

    "configuration_version":
        CONFIGURATION_VERSION,

    "seed":
        SEED,

    "package_versions":
        PACKAGE_VERSIONS,

    "runtime":
        RUNTIME_INFO,

    "datasets":
        DATASETS,

    "scenarios":
        list(
            EXPERIMENT_SCENARIO_REGISTRY.keys()
        ),

    "candidate_strategies":
        CANDIDATE_STRATEGIES
}

with open(
    CONFIG_SNAPSHOT_PATH,
    "w",
    encoding="utf-8"
) as file:

    json.dump(
        CONFIG_SNAPSHOT,
        file,
        indent=4,
        default=str
    )

print(
    f"Configuration snapshot saved:\n"
    f"{CONFIG_SNAPSHOT_PATH}"
)

Configuration snapshot saved:
/content/drive/MyDrive/AIR_LLM_Research/artifacts/configuration_snapshot.json

In [43]:
# ============================================================
# CELL 00.15.8 — EXPERIMENT TRACKING TEMPLATE
# ============================================================

EXPERIMENT_TRACKING_COLUMNS = [

    "experiment_id",

    "dataset_id",

    "scenario_id",

    "mechanism",

    "missingness_rate",

    "repetition",

    "feature",

    "feature_type",

    "candidate_strategy",

    "llm_recommendation",

    "final_strategy",

    "llm_confidence",

    "fallback_used",

    "status",

    "timestamp"
]

EXPERIMENT_TRACKING_PATH = (
    DIRECTORIES["logs"]
    / "experiment_tracking.csv"
)

if not EXPERIMENT_TRACKING_PATH.exists():

    pd.DataFrame(
        columns=EXPERIMENT_TRACKING_COLUMNS
    ).to_csv(
        EXPERIMENT_TRACKING_PATH,
        index=False
    )

print(
    f"Experiment tracking template:\n"
    f"{EXPERIMENT_TRACKING_PATH}"
)

Experiment tracking template:
/content/drive/MyDrive/AIR_LLM_Research/logs/experiment_tracking.csv

In [44]:
# ============================================================
# CELL 00.15.9 — RESULTS INDEX TEMPLATE
# ============================================================

RESULT_COLUMNS = [

    "result_id",

    "dataset_id",

    "scenario_id",

    "repetition",

    "feature",

    "feature_type",

    "method",

    "metric",

    "value",

    "timestamp"
]

RESULT_INDEX_PATH = (
    DIRECTORIES["results_processed"]
    / "results_index.csv"
)

if not RESULT_INDEX_PATH.exists():

    pd.DataFrame(
        columns=RESULT_COLUMNS
    ).to_csv(
        RESULT_INDEX_PATH,
        index=False
    )

print(
    f"Results index:\n"
    f"{RESULT_INDEX_PATH}"
)

Results index:
/content/drive/MyDrive/AIR_LLM_Research/results/processed/results_index.csv

In [45]:

# ============================================================
# CELL 00.15.10 — PUBLICATION TABLE INDEX
# ============================================================

PUBLICATION_TABLE_COLUMNS = [

    "table_id",

    "table_name",

    "source_notebook",

    "description",

    "file_path",

    "status"
]

PUBLICATION_TABLE_INDEX_PATH = (
    DIRECTORIES["tables"]
    / "publication_table_index.csv"
)

if not PUBLICATION_TABLE_INDEX_PATH.exists():

    pd.DataFrame(
        columns=PUBLICATION_TABLE_COLUMNS
    ).to_csv(
        PUBLICATION_TABLE_INDEX_PATH,
        index=False
    )

print(
    f"Publication table index:\n"
    f"{PUBLICATION_TABLE_INDEX_PATH}"
)

Publication table index:
/content/drive/MyDrive/AIR_LLM_Research/results/tables/publication_table_index.csv

In [46]:
# ============================================================
# CELL 00.15.11 — RESEARCH MANIFEST
# ============================================================

RESEARCH_MANIFEST = {

    "project_name":
        PROJECT_NAME,

    "project_code":
        PROJECT_CODE,

    "project_version":
        PROJECT_VERSION,

    "experiment_version":
        EXPERIMENT_VERSION,

    "configuration_version":
        CONFIGURATION_VERSION,

    "created_at":
        datetime.now(timezone.utc).isoformat(),

    "random_seed":
        SEED,

    "datasets":
        DATASETS,

    "missingness_mechanisms":
        MISSINGNESS_CONFIG["mechanisms"],

    "missingness_rates":
        MISSINGNESS_CONFIG["rates"],

    "repetitions":
        MISSINGNESS_CONFIG["repetitions"],

    "candidate_strategies":
        CANDIDATE_STRATEGIES,

    "evaluation_metrics":
        EVALUATION_METRICS,

    "utility_weights":
        UTILITY_WEIGHTS,

    "confidence_thresholds":
        CONFIDENCE_THRESHOLDS,

    "scenario_count":
        len(
            EXPERIMENT_SCENARIO_REGISTRY
        ),

    "total_scenario_runs":
        TOTAL_SCENARIO_RUNS
}

RESEARCH_MANIFEST_PATH = (
    DIRECTORIES["artifacts"]
    / "research_manifest.json"
)

with open(
    RESEARCH_MANIFEST_PATH,
    "w",
    encoding="utf-8"
) as file:

    json.dump(
        RESEARCH_MANIFEST,
        file,
        indent=4,
        default=str
    )

print(
    f"Research manifest saved:\n"
    f"{RESEARCH_MANIFEST_PATH}"
)

Research manifest saved:
/content/drive/MyDrive/AIR_LLM_Research/artifacts/research_manifest.json

In [47]:
# ============================================================
# CELL 00.16.1 — CONFIGURATION VALIDATION
# ============================================================

VALIDATION_RESULTS = {}

# Project
VALIDATION_RESULTS[
    "project_root_defined"
] = PROJECT_ROOT is not None

# Dataset
VALIDATION_RESULTS[
    "three_datasets_configured"
] = len(DATASETS) == 3

VALIDATION_RESULTS[
    "dataset_targets_defined"
] = all(
    "target" in metadata
    for metadata
    in DATASET_REGISTRY.values()
)

# Feature / target
VALIDATION_RESULTS[
    "feature_target_registry_complete"
] = (
    set(FEATURE_TARGET_REGISTRY.keys())
    == set(DATASETS)
)

# Missingness
VALIDATION_RESULTS[
    "missingness_mechanisms_valid"
] = set(
    MISSINGNESS_CONFIG["mechanisms"]
).issubset({"MCAR", "MAR"})

VALIDATION_RESULTS[
    "missingness_rates_valid"
] = all(
    0 < rate < 1
    for rate
    in MISSINGNESS_CONFIG["rates"]
)

# Candidate strategies
VALIDATION_RESULTS[
    "candidate_strategies_defined"
] = len(CANDIDATE_STRATEGIES) > 0

# Utility
VALIDATION_RESULTS[
    "utility_weights_sum_to_one"
] = np.isclose(
    sum(UTILITY_WEIGHTS.values()),
    1.0
)

# Confidence
VALIDATION_RESULTS[
    "confidence_thresholds_valid"
] = (
    0 <= CONFIDENCE_THRESHOLDS["low"]
    <= CONFIDENCE_THRESHOLDS["medium"]
    <= CONFIDENCE_THRESHOLDS["high"]
    <= 1
)

# Scenarios
VALIDATION_RESULTS[
    "scenario_registry_complete"
] = (
    len(EXPERIMENT_SCENARIO_REGISTRY)
    == EXPECTED_SCENARIO_COUNT
)

# Directories
VALIDATION_RESULTS[
    "all_directories_exist"
] = all(
    path.exists()
    and path.is_dir()
    for path in DIRECTORIES.values()
)

# Configuration files
VALIDATION_RESULTS[
    "master_config_exists"
] = CONFIG_PATH.exists()

VALIDATION_RESULTS[
    "dataset_registry_file_exists"
] = DATASET_REGISTRY_PATH.exists()

VALIDATION_RESULTS[
    "scenario_registry_file_exists"
] = SCENARIO_REGISTRY_PATH.exists()

VALIDATION_RESULTS[
    "experiment_design_exists"
] = EXPERIMENT_DESIGN_PATH.exists()

# Tracking files
VALIDATION_RESULTS[
    "tracking_template_exists"
] = EXPERIMENT_TRACKING_PATH.exists()

VALIDATION_RESULTS[
    "results_index_exists"
] = RESULT_INDEX_PATH.exists()

VALIDATION_RESULTS[
    "publication_index_exists"
] = PUBLICATION_TABLE_INDEX_PATH.exists()

VALIDATION_DF = pd.DataFrame(
    [
        {
            "validation":
                key,

            "status":
                "PASS"
                if value
                else "FAIL"
        }

        for key, value
        in VALIDATION_RESULTS.items()
    ]
)

display(VALIDATION_DF)

assert all(
    VALIDATION_RESULTS.values()
)

print("Configuration validation: PASSED")

                          validation status
0               project_root_defined   PASS
1          three_datasets_configured   PASS
2            dataset_targets_defined   PASS
3   feature_target_registry_complete   PASS
4       missingness_mechanisms_valid   PASS
5            missingness_rates_valid   PASS
6       candidate_strategies_defined   PASS
7         utility_weights_sum_to_one   PASS
8        confidence_thresholds_valid   PASS
9         scenario_registry_complete   PASS
10             all_directories_exist   PASS
11              master_config_exists   PASS
12      dataset_registry_file_exists   PASS
13     scenario_registry_file_exists   PASS
14          experiment_design_exists   PASS
15          tracking_template_exists   PASS
16              results_index_exists   PASS
17          publication_index_exists   PASS

Configuration validation: PASSED

In [48]:
# ============================================================
# CELL 00.16.2 — REPRODUCIBILITY VALIDATION
# ============================================================

REPRODUCIBILITY_RESULTS = {

    "global_seed":
        SEED == 42,

    "python_hash_seed":
        os.environ.get("PYTHONHASHSEED")
        == str(SEED),

    "numpy_available":
        np.__version__ is not None,

    "pandas_available":
        pd.__version__ is not None,

    "scipy_available":
        scipy.__version__ is not None,

    "sklearn_available":
        SKLEARN_VERSION is not None,

    "yaml_available":
        yaml.__version__ is not None,

    "configuration_version_defined":
        CONFIGURATION_VERSION == "CONFIG-v1",

    "deterministic_configuration":
        PYTORCH_REPRODUCIBILITY[
            "deterministic"
        ] is True,

    "configuration_snapshot_saved":
        CONFIG_SNAPSHOT_PATH.exists(),

    "research_manifest_saved":
        RESEARCH_MANIFEST_PATH.exists(),

    "master_configuration_saved":
        CONFIG_PATH.exists()
}

REPRODUCIBILITY_DF = pd.DataFrame(
    [
        {
            "check":
                key,

            "status":
                "PASS"
                if value
                else "FAIL"
        }

        for key, value
        in REPRODUCIBILITY_RESULTS.items()
    ]
)

display(REPRODUCIBILITY_DF)

assert all(
    REPRODUCIBILITY_RESULTS.values()
)

print("Reproducibility validation: PASSED")

                            check status
0                     global_seed   PASS
1                python_hash_seed   PASS
2                 numpy_available   PASS
3                pandas_available   PASS
4                 scipy_available   PASS
5               sklearn_available   PASS
6                  yaml_available   PASS
7   configuration_version_defined   PASS
8     deterministic_configuration   PASS
9    configuration_snapshot_saved   PASS
10        research_manifest_saved   PASS
11     master_configuration_saved   PASS

Reproducibility validation: PASSED

In [49]:
# ============================================================
# CELL 00.16.3 — FINAL CONFIGURATION LOCK
# ============================================================

CONFIGURATION_LOCK = {

    "status":
        "LOCKED",

    "project":
        PROJECT_NAME,

    "project_code":
        PROJECT_CODE,

    "project_version":
        PROJECT_VERSION,

    "experiment_version":
        EXPERIMENT_VERSION,

    "configuration_version":
        CONFIGURATION_VERSION,

    "locked_at":
        datetime.now(timezone.utc).isoformat(),

    "random_seed":
        SEED,

    "datasets":
        DATASETS,

    "scenario_count":
        len(EXPERIMENT_SCENARIO_REGISTRY),

    "candidate_strategy_count":
        len(CANDIDATE_STRATEGIES),

    "configuration_file":
        str(CONFIG_PATH),

    "research_manifest":
        str(RESEARCH_MANIFEST_PATH)
}

CONFIGURATION_LOCK_PATH = (
    DIRECTORIES["artifacts"]
    / "configuration_lock.json"
)

with open(
    CONFIGURATION_LOCK_PATH,
    "w",
    encoding="utf-8"
) as file:

    json.dump(
        CONFIGURATION_LOCK,
        file,
        indent=4,
        default=str
    )

print("=" * 100)
print("AIR-LLM CONFIGURATION LOCK")
print("=" * 100)

print(
    f"Status       : "
    f"{CONFIGURATION_LOCK['status']}"
)

print(
    f"Version      : "
    f"{CONFIGURATION_LOCK['configuration_version']}"
)

print(
    f"Locked At    : "
    f"{CONFIGURATION_LOCK['locked_at']}"
)

print(
    f"Lock File    : "
    f"{CONFIGURATION_LOCK_PATH}"
)

====================================================================================================
AIR-LLM CONFIGURATION LOCK
====================================================================================================
Status       : LOCKED
Version      : CONFIG-v1
Locked At    : 2026-08-18T11:14:53.479624+00:00
Lock File    : /content/drive/MyDrive/AIR_LLM_Research/artifacts/configuration_lock.json

In [50]:
# ============================================================
# CELL 00.16.4 — FINAL NOTEBOOK STATUS
# ============================================================

print("\n")
print("=" * 100)
print("AIR-LLM — NOTEBOOK 00 COMPLETE")
print("=" * 100)

print("\nPROJECT")
print("-" * 100)
print(f"Project              : {PROJECT_NAME}")
print(f"Project Code         : {PROJECT_CODE}")
print(f"Project Version      : {PROJECT_VERSION}")
print(f"Experiment Version   : {EXPERIMENT_VERSION}")
print(f"Configuration        : {CONFIGURATION_VERSION}")
print(f"Project Root         : {PROJECT_ROOT}")

print("\nDATASETS")
print("-" * 100)

for dataset_id in DATASETS:

    metadata = DATASET_REGISTRY[dataset_id]

    print(
        f"{dataset_id:20s} | "
        f"{metadata['dataset_name']:30s} | "
        f"Target: {metadata['target']}"
    )

print("\nEXPERIMENT DESIGN")
print("-" * 100)
print(
    f"Missingness mechanisms : "
    f"{MISSINGNESS_CONFIG['mechanisms']}"
)

print(
    f"Missingness rates      : "
    f"{MISSINGNESS_CONFIG['rates']}"
)

print(
    f"Repetitions            : "
    f"{MISSINGNESS_CONFIG['repetitions']}"
)

print(
    f"Scenarios              : "
    f"{len(EXPERIMENT_SCENARIO_REGISTRY)}"
)

print(
    f"Total scenario runs    : "
    f"{TOTAL_SCENARIO_RUNS}"
)

print("\nSTRATEGY SELECTION")
print("-" * 100)
print(
    f"Candidate strategies   : "
    f"{len(CANDIDATE_STRATEGIES)}"
)

print(
    f"Feature-level selection: "
    f"{STRATEGY_SELECTION_POLICY['selection_granularity']}"
)

print(
    f"LLM enabled            : "
    f"{LLM_CONFIG['enabled']}"
)

print(
    f"Minimum confidence     : "
    f"{CONFIDENCE_THRESHOLDS['minimum_selection_confidence']}"
)

print("\nREPRODUCIBILITY")
print("-" * 100)
print(f"Seed                   : {SEED}")
print(f"Device                 : {DEVICE}")
print(f"GPU                    : {GPU_NAME}")
print(f"Configuration locked   : YES")

print("\nCONFIGURATION FILES")
print("-" * 100)
print(f"Master Config           : {CONFIG_PATH}")
print(f"Dataset Registry        : {DATASET_REGISTRY_PATH}")
print(f"Feature/Target Registry : {FEATURE_TARGET_REGISTRY_PATH}")
print(f"Scenario Registry       : {SCENARIO_REGISTRY_PATH}")
print(f"Experiment Design       : {EXPERIMENT_DESIGN_PATH}")
print(f"Research Manifest       : {RESEARCH_MANIFEST_PATH}")
print(f"Configuration Lock      : {CONFIGURATION_LOCK_PATH}")

print("\n" + "=" * 100)
print("ALL NOTEBOOK 00 VALIDATIONS PASSED")
print("AIR-LLM RESEARCH CONFIGURATION IS READY FOR NOTEBOOK 01")
print("=" * 100)

====================================================================================================
AIR-LLM — NOTEBOOK 00 COMPLETE
====================================================================================================

PROJECT
----------------------------------------------------------------------------------------------------
Project              : AIR-LLM Research Project
Project Code         : AIR-LLM
Project Version      : 1.0
Experiment Version   : AIR-LLM-v1
Configuration        : CONFIG-v1
Project Root         : /content/drive/MyDrive/AIR_LLM_Research

DATASETS
----------------------------------------------------------------------------------------------------
adult_income         | Adult Income                   | Target: income
bank_marketing       | Bank Marketing                 | Target: y
diabetes_130us       | Diabetes 130-US Hospitals      | Target: readmitted

EXPERIMENT DESIGN
----------------------------------------------------------------------------------------------------
Missingness mechanisms : ['MCAR', 'MAR']
Missingness rates      : [0.1, 0.2, 0.3, 0.4, 0.5]
Repetitions            : 5
Scenarios              : 10
Total scenario runs    : 150

STRATEGY SELECTION
----------------------------------------------------------------------------------------------------
Candidate strategies   : 7
Feature-level selection: feature_level
LLM enabled            : True
Minimum confidence     : 0.6

REPRODUCIBILITY
----------------------------------------------------------------------------------------------------
Seed                   : 42
Device                 : cpu
GPU                    : CPU
Configuration locked   : YES

CONFIGURATION FILES
----------------------------------------------------------------------------------------------------
Master Config           : /content/drive/MyDrive/AIR_LLM_Research/config/config.yaml
Dataset Registry        : /content/drive/MyDrive/AIR_LLM_Research/config/dataset_registry.yaml
Feature/Target Registry : /content/drive/MyDrive/AIR_LLM_Research/config/feature_target_registry.yaml
Scenario Registry       : /content/drive/MyDrive/AIR_LLM_Research/config/experiment_scenario_registry.yaml
Experiment Design       : /content/drive/MyDrive/AIR_LLM_Research/config/experiment_design.yaml
Research Manifest       : /content/drive/MyDrive/AIR_LLM_Research/artifacts/research_manifest.json
Configuration Lock      : /content/drive/MyDrive/AIR_LLM_Research/artifacts/configuration_lock.json

====================================================================================================
ALL NOTEBOOK 00 VALIDATIONS PASSED
AIR-LLM RESEARCH CONFIGURATION IS READY FOR NOTEBOOK 01
====================================================================================================

In [51]:
# ============================================================
# CELL 00.16.2 — FINAL DRIVE PERSISTENCE VALIDATION
# ============================================================

from pathlib import Path

# ------------------------------------------------------------
# 1. Re-establish the canonical project root
# ------------------------------------------------------------

PROJECT_ROOT = Path(
    "/content/drive/MyDrive/AIR_LLM_Research"
)

# ------------------------------------------------------------
# 2. Required directories
# ------------------------------------------------------------

REQUIRED_DIRECTORIES = [
    PROJECT_ROOT / "config",
    PROJECT_ROOT / "data",
    PROJECT_ROOT / "data" / "raw",
    PROJECT_ROOT / "data" / "processed",
    PROJECT_ROOT / "data" / "reference",
    PROJECT_ROOT / "experiments",
    PROJECT_ROOT / "experiments" / "missingness",
    PROJECT_ROOT / "experiments" / "imputation",
    PROJECT_ROOT / "experiments" / "llm",
    PROJECT_ROOT / "experiments" / "evaluation",
    PROJECT_ROOT / "experiments" / "robustness",
    PROJECT_ROOT / "models",
    PROJECT_ROOT / "results",
    PROJECT_ROOT / "results" / "raw",
    PROJECT_ROOT / "results" / "processed",
    PROJECT_ROOT / "results" / "tables",
    PROJECT_ROOT / "results" / "figures",
    PROJECT_ROOT / "reports",
    PROJECT_ROOT / "logs",
    PROJECT_ROOT / "artifacts",
]

# ------------------------------------------------------------
# 3. Required configuration files
# ------------------------------------------------------------

REQUIRED_FILES = [
    PROJECT_ROOT / "config" / "config.yaml",
    PROJECT_ROOT / "config" / "dataset_registry.yaml",
    PROJECT_ROOT / "config" / "feature_target_registry.yaml",
    PROJECT_ROOT / "config" / "experiment_scenario_registry.yaml",
    PROJECT_ROOT / "config" / "experiment_design.yaml",
    PROJECT_ROOT / "artifacts" / "research_manifest.json",
    PROJECT_ROOT / "artifacts" / "configuration_lock.json",
]

# ------------------------------------------------------------
# 4. Verify directories
# ------------------------------------------------------------

missing_directories = [
    str(path)
    for path in REQUIRED_DIRECTORIES
    if not path.exists() or not path.is_dir()
]

# ------------------------------------------------------------
# 5. Verify files
# ------------------------------------------------------------

missing_files = [
    str(path)
    for path in REQUIRED_FILES
    if not path.exists() or not path.is_file()
]

# ------------------------------------------------------------
# 6. Verify files are non-empty
# ------------------------------------------------------------

empty_files = [
    str(path)
    for path in REQUIRED_FILES
    if path.exists() and path.stat().st_size == 0
]

# ------------------------------------------------------------
# 7. Final validation
# ------------------------------------------------------------

if missing_directories or missing_files or empty_files:

    print("=" * 100)
    print("AIR-LLM — DRIVE PERSISTENCE VALIDATION FAILED")
    print("=" * 100)

    if missing_directories:
        print("\nMissing directories:")
        for path in missing_directories:
            print(f"  ✗ {path}")

    if missing_files:
        print("\nMissing files:")
        for path in missing_files:
            print(f"  ✗ {path}")

    if empty_files:
        print("\nEmpty files:")
        for path in empty_files:
            print(f"  ✗ {path}")

    raise RuntimeError(
        "\nNotebook 00 configuration was NOT successfully persisted "
        "to Google Drive."
    )

# ------------------------------------------------------------
# 8. Success report
# ------------------------------------------------------------

print("=" * 100)
print("AIR-LLM — FINAL DRIVE PERSISTENCE VALIDATION")
print("=" * 100)

print("\nProject Root:")
print(PROJECT_ROOT)

print("\nRequired directories:")
for path in REQUIRED_DIRECTORIES:
    print(f"  ✓ {path}")

print("\nRequired configuration files:")
for path in REQUIRED_FILES:
    print(
        f"  ✓ {path} "
        f"({path.stat().st_size:,} bytes)"
    )

print("\n" + "=" * 100)
print("NOTEBOOK 00 CONFIGURATION PERSISTED SUCCESSFULLY")
print("GOOGLE DRIVE PERSISTENCE VALIDATION PASSED")
print("NOTEBOOK 02 IS NOW AUTHORIZED TO LOAD THE CONFIGURATION")
print("=" * 100)

====================================================================================================
AIR-LLM — FINAL DRIVE PERSISTENCE VALIDATION
====================================================================================================

Project Root:
/content/drive/MyDrive/AIR_LLM_Research

Required directories:
  ✓ /content/drive/MyDrive/AIR_LLM_Research/config
  ✓ /content/drive/MyDrive/AIR_LLM_Research/data
  ✓ /content/drive/MyDrive/AIR_LLM_Research/data/raw
  ✓ /content/drive/MyDrive/AIR_LLM_Research/data/processed
  ✓ /content/drive/MyDrive/AIR_LLM_Research/data/reference
  ✓ /content/drive/MyDrive/AIR_LLM_Research/experiments
  ✓ /content/drive/MyDrive/AIR_LLM_Research/experiments/missingness
  ✓ /content/drive/MyDrive/AIR_LLM_Research/experiments/imputation
  ✓ /content/drive/MyDrive/AIR_LLM_Research/experiments/llm
  ✓ /content/drive/MyDrive/AIR_LLM_Research/experiments/evaluation
  ✓ /content/drive/MyDrive/AIR_LLM_Research/experiments/robustness
  ✓ /content/drive/MyDrive/AIR_LLM_Research/models
  ✓ /content/drive/MyDrive/AIR_LLM_Research/results
  ✓ /content/drive/MyDrive/AIR_LLM_Research/results/raw
  ✓ /content/drive/MyDrive/AIR_LLM_Research/results/processed
  ✓ /content/drive/MyDrive/AIR_LLM_Research/results/tables
  ✓ /content/drive/MyDrive/AIR_LLM_Research/results/figures
  ✓ /content/drive/MyDrive/AIR_LLM_Research/reports
  ✓ /content/drive/MyDrive/AIR_LLM_Research/logs
  ✓ /content/drive/MyDrive/AIR_LLM_Research/artifacts

Required configuration files:
  ✓ /content/drive/MyDrive/AIR_LLM_Research/config/config.yaml (9,455 bytes)
  ✓ /content/drive/MyDrive/AIR_LLM_Research/config/dataset_registry.yaml (656 bytes)
  ✓ /content/drive/MyDrive/AIR_LLM_Research/config/feature_target_registry.yaml (543 bytes)
  ✓ /content/drive/MyDrive/AIR_LLM_Research/config/experiment_scenario_registry.yaml (1,245 bytes)
  ✓ /content/drive/MyDrive/AIR_LLM_Research/config/experiment_design.yaml (310 bytes)
  ✓ /content/drive/MyDrive/AIR_LLM_Research/artifacts/research_manifest.json (1,629 bytes)
  ✓ /content/drive/MyDrive/AIR_LLM_Research/artifacts/configuration_lock.json (638 bytes)

====================================================================================================
NOTEBOOK 00 CONFIGURATION PERSISTED SUCCESSFULLY
GOOGLE DRIVE PERSISTENCE VALIDATION PASSED
NOTEBOOK 02 IS NOW AUTHORIZED TO LOAD THE CONFIGURATION
====================================================================================================